import {ConjugationModel, ConjugationRules, VerbConjugationAnnotation, TenseMood} from "./index"


// Each verb has a description of the rules required to conjugate it properly.
// If there are no ConjugationRules (a value of "null"), then the verb is regular, and is conjugated normally.
// Otherwise, targhe ConjugationRules specify the minimal rules required for conjugating the verb.
export const morphophonemic_verb_conjugation_rules: {[infinitive: string]: ConjugationRules | null} = {
    // abrazar: null,
    // abrir: null,
    // abstener: {irregular_base: "tener"},
    // aburrir: null,
    // acabar: null,
    // aceptar: null,
    acercar: {model: "sacar"},
    acertar: {model: "acertar", stem_change_rule_id: "e:ie"},
    acordar: {model: "contar", stem_change_rule_id: "o:ue"},
    acostar: {stem_change_rule_id: "o:ue"},
    // actualizar: null,
    // acudir: null,
    // adormecer: null,
    // afeitar: null,
    // agarrar: null,
    // agradecer: null,
    // agredir: null,
    // alcanzar: null,
    almorzar: {model: "forzar", stem_change_rule_id: "o:ue"},
    // alzar: null,
    // amanecer: null,
    // amenazar: null,
    andar: {irregular_base: "andar"},
    // aparecer: null,
    aplicar: {model: "sacar"},
    apostar: {stem_change_rule_id: "o:ue"},
    aprobar: {stem_change_rule_id: "o:ue"},
    // amar: null,
    ampliar: {irregular_base: "vaciar"},
    // analizar: null,
    // aprender: null,
    // argüir: {model: "unfinished"}, // ChatGPT
    // arrancar: null,
    // arrodillar: null,
    ascender: {stem_change_rule_id: "e:ie"},
    // asegurar: null,
    // asistir: null,
    // asociar: null,
    atacar: {model: "sacar"},
    atender: {stem_change_rule_id: "e:ie"},
    // aterrizar: null,
    atraer: {irregular_base: "traer"},
    // avanzar: null,
    // ayudar: null,
    // bailar: null,
    // bañar: null,
    // bautizar: null,
    // beber: null,
    bendecir: {irregular_base: "decir"},
    // bloquear: null,
    // brincar: null,
    // bucear: null,
    buscar: {model: "sacar"},
    caber: {irregular_base: "caber"}, // ChatGPT
    caer: {irregular_base: "caer"},
    calentar: {stem_change_rule_id: "e:ie"},
    // cambiar: null,
    // caminar: null,
    // canalizar: null,
    // cantar: null,
    // cazar: null,
    // celebrar: null,
    // cenar: null,
    // TODO: check ceñir
    cerrar: {model: "acertar", stem_change_rule_id: "e:ie"},
    // cepillar: null,
    checar: {model: "sacar"},
    // chequear: null,
    // chocar: null,
    // coger: null,
    // colocar: null,
    comenzar: {stem_change_rule_id: "e:ie"},
    // comer: null,
    // compartir: null,
    competir: {stem_change_rule_id: "e:i"},
    // completar: null,
    componer: {irregular_base: "poner"},
    // comprar: null,
    // comprender: null,
    comprobar: {stem_change_rule_id: "o:ue"},
    // comprometer: null,
    // comunicar: null,
    // conceptualizar: null,
    concertar: {stem_change_rule_id: "e:ie"},
    concordar: {stem_change_rule_id: "o:ue"},
    conducir: {irregular_base: "conducir"}, 
    // conectar: null,
    confesar: {stem_change_rule_id: "e:ie"},
    confiar: {irregular_base: "vaciar"},
    // confundir: null,
    conmover: {stem_change_rule_id: "o:ue"},
    // conocer: null, // ChatGPT
    conseguir: {irregular_base: "seguir", stem_change_rule_id: "e:i"},    // except for yo, similar to {stem_change_rule_id: "e:ie"},
    // considerar: null,
    construir: {irregular_base: "huir"},
    contar: {stem_change_rule_id: "o:ue"},
    contener: {irregular_base: "tener"},
    // contestar: null,
    contraer: {irregular_base: "traer"},
    contribuir: {irregular_base: "huir"},
    // conversar: null,
    convertir: {stem_change_rule_id: "e:ie"},
    convocar: {model: "sacar"},
    coproducir: {irregular_base: "conducir"},
    corregir: {stem_change_rule_id: "e:i"},
    // correr: null,
    costar: {stem_change_rule_id: "o:ue"},
    // cotizar: null,
    // crear: null,
    // crecer: null,
    // creer: null,  // ChatGPT
    // creer: {model: "leer"},
    criar: {irregular_base: "vaciar"},
    criticar: {model: "sacar"},
    // cruzar: null,
    dar: {irregular_base: "dar"},
    // deber: null,
    // decidir: null,
    decir: {irregular_base: "decir", stem_change_rule_id: "e:i"},
    dedicar: {model: "sacar"},
    defender: {stem_change_rule_id: "e:ie"},
    // dejar: null,
    delinquir: {model: "unfinished"}, // ChatGPT
    // democratizar: null,
    demostrar: {stem_change_rule_id: "o:ue"},
    derrocar: {model: "sacar"},
    // desaparecer: null,
    desaprobar: {stem_change_rule_id: "o:ue"},
    // desayunar: null,
    // descansar: null,
    descomponer: {irregular_base: "poner"},
    desconfiar: {irregular_base: "vaciar"},
    // desear: null,
    // describir: null,
    deshacer: {irregular_base: "hacer"},
    // despedir: null,
    despertar: {stem_change_rule_id: "e:ie"},
    destruir: {irregular_base: "huir"},
    desviar: {irregular_base: "vaciar"},
    devolver: {stem_change_rule_id: "o:ue"},
    // dibujar: null,
    // dictar: null,
    // difundir: null,    // podcasts, news
    // disparar: null,    // news
    disponer: {irregular_base: "poner"},
    // dividir: null,
    disminuir: {irregular_base: "huir"},
    disolver: {stem_change_rule_id: "o:ue"},
    distraer: {irregular_base: "traer"},
    distribuir: {irregular_base: "huir"},
    doler: {stem_change_rule_id: "o:ue"},
    dormir: {stem_change_rule_id: "o:ue"},
    // desembocar: null,
    desoír: {irregular_base: "oír"},
    // desproteger: null,
    // detener: {irregular_base: "tener"}, individual_accents: {CmdPos: {s2: ["detén"]},
    // disfrazar: null,
    // duchar: null,
    duplicar: {model: "sacar"},
    // elegir: {stem_change_rule_id: "e:i"},
    elegir: {stem_change_rule_id: "e:i"},
    // emparejar: null,
    // empatar: null,
    // empatizar: null,
    empezar: {stem_change_rule_id: "e:ie"},
    // encantar: null,
    // encauzar: null,
    encender: {stem_change_rule_id: "e:ie"},
    encontrar: {stem_change_rule_id: "o:ue"},
    // endurecer: null,
    enfocar: {model: "sacar"},
    enfriar: {irregular_base: "vaciar"},
    // enfurecer: null,
    // enloquecer: null,
    // enojar: null,
    // ensañar: null,
    // enseñar: null,
    entender: {stem_change_rule_id: "e:ie"},
    enterrar: {stem_change_rule_id: "e:ie"},
    // entrar: null,
    entrecerrar: {stem_change_rule_id: "e:ie"},
    entreoír: {irregular_base: "oír"},
    entretener: {irregular_base: "tener"},
    // entristecer: null,
    // envejecer: null,
    enviar: {irregular_base: "vaciar"},
    equivocar: {model: "sacar"},
    erguir: {irregular_base: "erguir"}, // ChatGPT
    // FIX: errar: {},
    // escalar: null,
    // escoger: null,
    // escribir: null,
    // escuchar: null,
    esforzar: {model: "forzar", stem_change_rule_id: "o:ue"},
    // esperar: null,
    espiar: {irregular_base: "vaciar"},
    esquiar: {irregular_base: "vaciar"},
    // estabilizar: null,
    // establecer: null,
    estar: {irregular_base: "estar"},
    // estremecer: null,
    // estudiar: null,
    excluir: {irregular_base: "huir"},
    // existir: null,
    // expandir: null,
    explicar: {model: "sacar"},
    exponer: {irregular_base: "poner"},
    extender: {stem_change_rule_id: "e:ie"},
    extraer: {irregular_base: "traer"},
    fabricar: {model: "sacar"},
    // fallecer: null,
    // faltar: null,
    // fascinar: null,
    fluir: {irregular_base: "huir"},
    // formalizar: null,
    // formar: null,
    // fortalecer: null,
    forzar: {model: "forzar", stem_change_rule_id: "o:ue"},
    fotografiar: {irregular_base: "vaciar"},
    guiar: {irregular_base: "vaciar"},
    // funcionar: null,
    // ganar: null,
    // garantizar: null,
    // gastar: null,
    gobernar: {stem_change_rule_id: "e:ie"},
    // gozar: null,
    granizar: {stem_change_rule_id: "o:ue", conjugate_only: ["s3"]},
    // gustar: null,
    haber: {irregular_base: "haber"}, // ChatGPT
    // habitar: null,
    // hablar: null,
    hacer: {irregular_base: "hacer"},
    helar: {stem_change_rule_id: "e:ie"},
    // hipnotizar: null,
    huir: {irregular_base: "huir"},
    // hundir: null,
    identificar: {model: "sacar"},
    impedir: {stem_change_rule_id: "e:i"},
    implicar: {model: "sacar"},
    imponer: {irregular_base: "poner"},
    // importar: null,
    incluir: {irregular_base: "huir"},
    inculcar: {model: "sacar"},
    indicar: {model: "sacar"},
    influir: {irregular_base: "huir"},
    instruir: {irregular_base: "huir"},
    // intentar: null,
    // interceptar: null,   // news
    // interesar: null,
    interponer: {irregular_base: "poner"},
    ir: {irregular_base: "ir"},
    jugar: {irregular_base: "jugar", stem_change_rule_id: "u:ue"},   // Bing says "jugar" is the only verb with this stem change.
    // lanzar: null,
    // lavar: null,
    leer: {irregular_base: "leer"}, // ChatGPT
    // legalizar: null,
    // levantar: null,
    // llamar: null,
    // llegar: null, // ChatGPT
    // llevar: null,
    // llorar: null,
    llover: {stem_change_rule_id: "o:ue", conjugate_only: ["s3"]},
    // lograr: null,
    machucar: {model: "sacar"},
    maldecir: {irregular_base: "decir"},
    manifestar: {stem_change_rule_id: "e:ie"},
    mantener: {irregular_base: "tener"},
    // maquillar: null,
    marcar: {model: "sacar"},
    // matar: null,
    medir: {stem_change_rule_id: "e:i"},
    // merecer: null,
    merendar: {stem_change_rule_id: "e:ie"},
    // meter: null,
    // mirar: null,
    // molestar: null,
    morir: {stem_change_rule_id: "o:ue"},
    mostrar: {stem_change_rule_id: "o:ue"},
    mover: {stem_change_rule_id: "o:ue"},
    // movilizar: null,
    // nacer: null,
    // nadar: null,
    // necesitar: null,
    nevar: {stem_change_rule_id: "e:ie", conjugate_only: ["s3"]},
    // normalizar: null,
    // obedecer: null,
    obtener: {irregular_base: "tener"},
    // ocurrir: null,
    // ofrecer: null,
    oír: {irregular_base: "oír"}, // ChatGPT
    oponer: {irregular_base: "poner"},
    // orar: null,
    // organizar: null,
    // pagar: null,
    // paralizar: null,
    // parar: null,
    // parecer: null,
    // partir: null,
    // pasar: null,
    // pasear: null,
    // patinar: null,
    pedir: {stem_change_rule_id: "e:i"},
    // peinar: null,
    pensar: {stem_change_rule_id: "e:ie"},
    perder: {stem_change_rule_id: "e:ie"},
    // permanecer: null,
    perseguir: {irregular_base: "seguir", stem_change_rule_id: "e:i"},    // except for yo, similar to {stem_change_rule_id: "e:ie"},
    // pertenecer: null,
    pescar: {model: "sacar"},
    picar: {model: "sacar"},
    platicar: {model: "sacar"},
    poder: {irregular_base: "poder", stem_change_rule_id: "o:ue"},
    // politizar: null,
    poner: {irregular_base: "poner"}, // ChatGPT
    posponer: {irregular_base: "poner"},
    practicar: {model: "sacar"},
    preferir: {stem_change_rule_id: "e:ie"}, // ChatGPT
    // preguntar: null,
    // preocupar: null,
    // preparar: null,
    // presentar: null,
    probar: {stem_change_rule_id: "o:ue"},
    producir: {irregular_base: "conducir"},
    // profundizar: null,
    // programar: null,
    promover: {stem_change_rule_id: "o:ue"},
    proponer: {irregular_base: "poner"},
    proseguir: {irregular_base: "seguir", stem_change_rule_id: "e:i"},    // except for yo, similar to {stem_change_rule_id: "e:ie"},
    // protagonizar: null,
    // proteger: null,
    provocar: {model: "sacar"},
    publicar: {model: "sacar"},
    quebrar: {stem_change_rule_id: "e:ie"},
    // quedar: null,
    querer: {irregular_base: "querer", stem_change_rule_id: "e:ie"},
    // quitar: null,
    rascar: {model: "sacar"},
    // realizar: null,
    // rebautizar: null,
    recalcar: {model: "sacar"},
    recalentar: {stem_change_rule_id: "e:ie"},
    // rechazar: null,
    // recibir: null,
    // recoger: null,
    recomendar: {stem_change_rule_id: "e:ie"},
    recomenzar: {stem_change_rule_id: "e:ie"},
    // reconocer: null,
    recontar: {stem_change_rule_id: "o:ue"},
    recordar: {stem_change_rule_id: "o:ue"},
    reducir: {irregular_base: "conducir"},
    // reemplazar: null,
    reencontrar: {stem_change_rule_id: "o:ue"},
    // reflejar: null,
    reforzar: {model: "forzar", stem_change_rule_id: "o:ue"},
    // regatear: null,
    regir: {stem_change_rule_id: "e:i"},
    // regresar: null,
    // regularizar: null,
    remover: {stem_change_rule_id: "o:ue"},
    repetir: {stem_change_rule_id: "e:i"},
    replicar: {model: "sacar"},
    reponer: {irregular_base: "poner"},
    reprobar: {stem_change_rule_id: "o:ue"},
    reproducir: {irregular_base: "conducir"},
    // resignar: null,
    resolver: {stem_change_rule_id: "o:ue"},
    // responder: null,
    retener: {irregular_base: "tener"},
    reunir: {model: "reunir", stem_change_rule_id: "u:ú"},
    // revisar: null,
    revolver: {stem_change_rule_id: "o:ue"},
    // rezar: null,
    saber: {irregular_base: "saber"},
    sacar: {model: "sacar"}, // ChatGPT
    // sacer: null,
    sacrificar: {model: "sacar"},
    // sacudir: null,
    salir: {irregular_base: "salir"},
    satisfacer: {irregular_base: "hacer"},
    seguir: {irregular_base: "seguir", stem_change_rule_id: "e:i"},    // except for yo, similar to {stem_change_rule_id: "e:ie"},
    secar: {model: "sacar"},
    seducir: {irregular_base: "conducir"},
    // seleccionar: null,
    sentar: {stem_change_rule_id: "e:ie"},
    sentir: {stem_change_rule_id: "e:ie"},
    ser: {irregular_base: "ser"},
    servir: {stem_change_rule_id: "e:i"},
    significar: {model: "sacar"},
    // simbolizar: null,
    sobrecalentar: {stem_change_rule_id: "e:ie"},
    sobrevolar: {stem_change_rule_id: "o:ue"},
    soldar: {stem_change_rule_id: "o:ue"},
    // solidarizar: null,
    soltar: {stem_change_rule_id: "o:ue"},
    sonar: {stem_change_rule_id: "o:ue"},
    soñar: {stem_change_rule_id: "o:ue"},
    // sorprender: null,   // canciones, podcasts, news
    sostener: {irregular_base: "tener"},
    // subir: null,
    // sufrir: null,
    suponer: {irregular_base: "poner"},
    sustituir: {irregular_base: "huir"},
    temblar: {stem_change_rule_id: "e:ie"},
    // temer: null,
    tender: {stem_change_rule_id: "e:ie"},
    tener: {irregular_base: "tener", stem_change_rule_id: "e:ie"},  // ChatGPT
    // terminar: null,
    // tirar: null,
    tocar: {model: "sacar"},
    // tomar: null,
    // trabajar: null,
    traducir: {irregular_base: "conducir"},
    traer: {irregular_base: "traer"},
    traficar: {model: "sacar"},
    // tranquilizar: null,
    // tratar: null,
    triplicar: {model: "sacar"},
    trompezar: {stem_change_rule_id: "e:ie"},
    tropezar: {stem_change_rule_id: "e:ie"},
    ubicar: {model: "sacar"},
    // unir: null,
    unificar: {model: "sacar"},
    // usar: null,
    // utilizar: null,
    vaciar: {irregular_base: "vaciar"}, // ChatGPT
    variar: {irregular_base: "vaciar"},
    // vender: null,
    venir: {irregular_base: "venir", stem_change_rule_id: "e:ie"}, // ChatGPT
    ver: {irregular_base: "ver"},
    verificar: {model: "sacar"},
    vestir: {stem_change_rule_id: "e:ie"},
    // viajar: null,
    // visitar: null,
    // visualizar: null,
    // vivir: null,
    volar: {stem_change_rule_id: "o:ue"},
    volcar: {stem_change_rule_id: "o:ue"},
    volver: {stem_change_rule_id: "o:ue"},
}


export function getAnnotations(infinitive: string, model: ConjugationModel, tense_mood: TenseMood) : VerbConjugationAnnotation {
    const unconfirmed = !(infinitive in morphophonemic_verb_conjugation_rules) || undefined
    const annotations: VerbConjugationAnnotation = {model, tense_mood, unconfirmed}
    return annotations
}
