import {ConjugationRules, VerbConjugationAnnotation, VerbTenseMood} from "./index"


// Each verb has a description of the rules required to conjugate it properly.
// If there are no ConjugationRules (a value of "null"), then the verb is regular, and is conjugated normally.
// Otherwise, the ConjugationRules specify the minimal rules required for conjugating the verb.
export const verb_conjugation_rules: {[infinitive: string]: ConjugationRules | null} = {
    // abrazar: null,
    // abrir: null,
// FIX:
    abstener: {model: "retener", irregular: {base: "tener"}},
    // aburrir: null,
    // acabar: null,
    // aceptar: null,
    acercar: {model: "sacar"},
    acertar: {model: "acertar", stem_change_type: "e:ie", stem_change_inclusions: ["PresInd","PresSub","CmdPos","CmdNeg"]},
    acordar: {model: "contar", stem_change_type: "o:ue", stem_change_inclusions: ["PresInd","PresSub","CmdPos","CmdNeg"]},
    acostar: {stem_change_type: "o:ue", stem_change_inclusions: ["PresInd"]},
    // actualizar: null,
    // acudir: null,
    // adormecer: null,
    // afeitar: null,
    // agarrar: null,
    // agradecer: null,
    // agredir: null,
    // alcanzar: null,
    almorzar: {model: "forzar", stem_change_type: "o:ue", stem_change_inclusions: ["PresInd","PresSub","CmdPos","CmdNeg"]},
    // alzar: null,
    // amanecer: null,
    // amenazar: null,
    // aparecer: null,
    aplicar: {model: "sacar"},
    apostar: {stem_change_type: "o:ue", stem_change_inclusions: ["PresInd","PresSub","CmdPos","CmdNeg"]},
    aprobar: {stem_change_type: "o:ue", stem_change_inclusions: ["PresInd","PresSub","CmdPos","CmdNeg"]},
    // amar: null,
    ampliar: {irregular: {base: "vaciar"}},
    // analizar: null,
    // aprender: null,
    // argüir: {model: "unfinished"}, // ChatGPT
    // arrancar: null,
    // arrodillar: null,
    ascender: {stem_change_type: "e:ie", stem_change_inclusions: ["PresInd"]},
    // asegurar: null,
    // asistir: null,
    // asociar: null,
    atacar: {model: "sacar"},
    atender: {stem_change_type: "e:ie", stem_change_inclusions: ["PresInd"]},
    // aterrizar: null,
    atraer: {irregular: {base: "traer"}},
    // avanzar: null,
    // ayudar: null,
    // bailar: null,
    // bañar: null,
    // bautizar: null,
    // beber: null,
    bendecir: {irregular: {base: "decir"}},
    // bloquear: null,
    // brincar: null,
    // bucear: null,
    buscar: {model: "sacar"},
    caber: {irregular: {base: "caber"}}, // ChatGPT
    caer: {irregular: {base: "caer"}},
    calentar: {stem_change_type: "e:ie", stem_change_inclusions: ["PresInd"]},
    // cambiar: null,
    // caminar: null,
    // canalizar: null,
    // cantar: null,
    // cazar: null,
    // celebrar: null,
    // cenar: null,
    cerrar: {model: "acertar", stem_change_type: "e:ie", stem_change_inclusions: ["PresInd"]},
    // cepillar: null,
    checar: {model: "sacar"},
    // chequear: null,
    // chocar: null,
    // coger: null,
    // colocar: null,
    comenzar: {stem_change_type: "e:ie", stem_change_inclusions: ["PresInd","PresSub","CmdPos","CmdNeg"]},
    // comer: null,
    // compartir: null,
    competir: {stem_change_type: "e:i"},
    // completar: null,
    componer: {irregular: {base: "poner"}},
    // comprar: null,
    // comprender: null,
    comprobar: {stem_change_type: "o:ue", stem_change_inclusions: ["PresInd"]},
    // comprometer: null,
    // comunicar: null,
    // conceptualizar: null,
    concertar: {stem_change_type: "e:ie", stem_change_inclusions: ["PresInd"]},
    concordar: {stem_change_type: "o:ue", stem_change_inclusions: ["PresInd"]},
    conducir: {conjugation_family: "ducir", irregular: {base: "conducir"}}, 
    // conectar: null,
    confesar: {stem_change_type: "e:ie", stem_change_inclusions: ["PresInd"]},
    confiar: {irregular: {base: "vaciar"}},
    // confundir: null,
    conmover: {stem_change_type: "o:ue", stem_change_inclusions: ["PresInd"]},
    // conocer: null, // ChatGPT
    conseguir: {irregular: {base: "seguir"}, stem_change_type: "e:i", stem_change_inclusions: ["PresInd", "PastInd"]},    // except for yo, similar to {stem_change_type: "e:ie", stem_change_inclusions: ["PresInd"]},
    // considerar: null,
    construir: {irregular: {base: "huir"}},
    contar: {stem_change_type: "o:ue", stem_change_inclusions: ["PresInd"]},
    contener: {irregular: {base: "tener"}},
    // contestar: null,
    contraer: {irregular: {base: "traer"}},
    contribuir: {irregular: {base: "huir"}},
    // conversar: null,
    convertir: {stem_change_type: "e:ie", stem_change_inclusions: ["PresInd", "PastInd"]},
    convocar: {model: "sacar"},
    coproducir: {irregular: {base: "conducir"}},
    corregir: {stem_change_type: "e:i", stem_change_inclusions: ["PresInd","PastInd"]},
    // correr: null,
    costar: {stem_change_type: "o:ue", stem_change_inclusions: ["PresInd"]},
    // cotizar: null,
    // crear: null,
    // crecer: null,
    // creer: {individual_accents: {PastInd: {s2:"creíste",s3: "creyó",p1:"creímos",p2:"creísteis",p3:"creyeron",vos:"creíste"}}},  // ChatGPT
    // creer: {model: "leer"},
    criar: {irregular: {base: "vaciar"}},
    criticar: {model: "sacar"},
    // cruzar: null,
    dar: {irregular: {base: "dar"}},
    // deber: null,
    // decidir: null,
    decir: {conjugation_family: "decir", irregular: {base: "decir"}, stem_change_type: "e:i", stem_change_inclusions: ["PresInd"]},
    dedicar: {model: "sacar"},
    defender: {stem_change_type: "e:ie", stem_change_inclusions: ["PresInd"]},
    // dejar: null,
    delinquir: {model: "unfinished"}, // ChatGPT
    // democratizar: null,
    demostrar: {stem_change_type: "o:ue", stem_change_inclusions: ["PresInd"]},
    derrocar: {model: "sacar"},
    // desaparecer: null,
    desaprobar: {stem_change_type: "o:ue", stem_change_inclusions: ["PresInd"]},
    // desayunar: null,
    // descansar: null,
    descomponer: {irregular: {base: "poner"}},
    desconfiar: {irregular: {base: "vaciar"}},
    // desear: null,
    // describir: null,
    deshacer: {irregular: {base: "hacer"}},
    // despedir: null,
    despertar: {stem_change_type: "e:ie", stem_change_inclusions: ["PresInd"]},
    destruir: {irregular: {base: "huir"}},
    desviar: {irregular: {base: "vaciar"}},
    devolver: {stem_change_type: "o:ue", stem_change_inclusions: ["PresInd"]},
    // dibujar: null,
    // dictar: null,
    // difundir: null,    // podcasts, news
    // disparar: null,    // news
    disponer: {irregular: {base: "poner"}},
    // dividir: null,
    disminuir: {irregular: {base: "huir"}},
    disolver: {stem_change_type: "o:ue", stem_change_inclusions: ["PresInd"]},
    distraer: {irregular: {base: "traer"}},
    distribuir: {irregular: {base: "huir"}},
    doler: {stem_change_type: "o:ue", stem_change_inclusions: ["PresInd"]},
    dormir: {stem_change_type: "o:ue"},
    // desembocar: null,
    desoír: {irregular: {base: "oír"}},
    // desproteger: null,
    detener: {irregular: {base: "tener"}, individual_accents: {CmdPos: {s2: "detén"}}},
    // disfrazar: null,
    // duchar: null,
    duplicar: {model: "sacar"},
    elegir: {stem_change_type: "e:i", stem_change_inclusions: ["PresInd","PastInd"]},
    // emparejar: null,
    // empatar: null,
    // empatizar: null,
    empezar: {stem_change_type: "e:ie", stem_change_inclusions: ["PresInd"]},
    // encantar: null,
    // encauzar: null,
    encender: {stem_change_type: "e:ie", stem_change_inclusions: ["PresInd"]},
    encontrar: {stem_change_type: "o:ue", stem_change_inclusions: ["PresInd"]},
    // endurecer: null,
    enfocar: {model: "sacar"},
    enfriar: {irregular: {base: "vaciar"}},
    // enfurecer: null,
    // enloquecer: null,
    // enojar: null,
    ensañar: null,
    enseñar: null,
    entender: {stem_change_type: "e:ie", stem_change_inclusions: ["PresInd"]},
    enterrar: {stem_change_type: "e:ie", stem_change_inclusions: ["PresInd"]},
    // entrar: null,
    entrecerrar: {stem_change_type: "e:ie", stem_change_inclusions: ["PresInd"]},
    entreoír: {irregular: {base: "oír"}},
    entretener: {irregular: {base: "tener"}},
    // entristecer: null,
    // envejecer: null,
    enviar: {irregular: {base: "vaciar"}},
    equivocar: {model: "sacar"},
    erguir: {irregular: {base: "erguir"}}, // ChatGPT
    // escalar: null,
    // escoger: null,
    // escribir: null,
    // escuchar: null,
    esforzar: {model: "forzar", stem_change_type: "o:ue", stem_change_inclusions: ["PresInd"]},
    // esperar: null,
    espiar: {irregular: {base: "vaciar"}},
    esquiar: {irregular: {base: "vaciar"}},
    // estabilizar: null,
    // establecer: null,
    estar: {irregular: {base: "estar"}},
    // estremecer: null,
    // estudiar: null,
    excluir: {irregular: {base: "huir"}},
    // existir: null,
    // expandir: null,
    explicar: {model: "sacar"},
    exponer: {irregular: {base: "poner"}},
    extender: {stem_change_type: "e:ie", stem_change_inclusions: ["PresInd"]},
    extraer: {irregular: {base: "traer"}},
    fabricar: {model: "sacar"},
    // fallecer: null,
    // faltar: null,
    // fascinar: null,
    fluir: {irregular: {base: "huir"}},
    // formalizar: null,
    // formar: null,
    // fortalecer: null,
    // FIX: no need for this conjugate_only: [s3] rule, now that ze is converted to ce
    forzar: {model: "forzar", stem_change_type: "o:ue", stem_change_inclusions: ["PresInd"]},
    fotografiar: {irregular: {base: "vaciar"}},
    guiar: {irregular: {base: "vaciar"}, individual_accents: {PresInd: {p2: "guiais"}, PresSub: {p2: "guieis"}, PastInd: {s1: "guie", s3: "guio"}, CmdNeg: {p2: "guieis"}}},
    // funcionar: null,
    // ganar: null,
    // garantizar: null,
    // gastar: null,
    gobernar: {stem_change_type: "e:ie", stem_change_inclusions: ["PresInd"]},
    // gozar: null,
    granizar: {stem_change_type: "o:ue", stem_change_inclusions: ["PresInd"], conjugate_only: ["s3"]},
    // gustar: null,
    haber: {irregular: {base: "haber"}}, // ChatGPT
    // habitar: null,
    // hablar: null,
    hacer: {conjugation_family: "acer", irregular: {base: "hacer"}},
    helar: {stem_change_type: "e:ie", stem_change_inclusions: ["PresInd"]},
    // hipnotizar: null,
    huir: {conjugation_family: "uir", irregular: {base: "huir"}},
    // hundir: null,
    identificar: {model: "sacar"},
    impedir: {stem_change_type: "e:i"},
    implicar: {model: "sacar"},
    imponer: {irregular: {base: "poner"}},
    // importar: null,
    incluir: {irregular: {base: "huir"}},
    inculcar: {model: "sacar"},
    indicar: {model: "sacar"},
    influir: {irregular: {base: "huir"}},
    instruir: {irregular: {base: "huir"}},
    // intentar: null,
    // interceptar: null,   // news
    // interesar: null,
    interponer: {irregular: {base: "poner"}},
    ir: {irregular: {base: "ir"}},
    jugar: {irregular: {base: "jugar"}, stem_change_type: "u:ue", stem_change_inclusions: ["PresInd","PresSub","CmdPos","CmdNeg"]},
    // lanzar: null,
    // lavar: null,
    leer: {conjugation_family: "eer", irregular: {base: "leer"}}, // ChatGPT
    // legalizar: null,
    // levantar: null,
    // llamar: null,
    // llegar: null, // ChatGPT
    // llevar: null,
    // llorar: null,
    llover: {stem_change_type: "o:ue", stem_change_inclusions: ["PresInd"], conjugate_only: ["s3"]},
    // lograr: null,
    machucar: {model: "sacar"},
    maldecir: {irregular: {base: "decir"}},
    manifestar: {stem_change_type: "e:ie", stem_change_inclusions: ["PresInd"]},
    mantener: {irregular: {base: "tener"}},
    // maquillar: null,
    marcar: {model: "sacar"},
    // matar: null,
    medir: {stem_change_type: "e:i"},
    // merecer: null,
    merendar: {stem_change_type: "e:ie", stem_change_inclusions: ["PresInd"]},
    // meter: null,
    // mirar: null,
    // molestar: null,
    morir: {stem_change_type: "o:ue"},
    mostrar: {stem_change_type: "o:ue", stem_change_inclusions: ["PresInd"]},
    mover: {stem_change_type: "o:ue", stem_change_inclusions: ["PresInd"]},
    // movilizar: null,
    // nacer: null,
    // nadar: null,
    // necesitar: null,
    nevar: {stem_change_type: "e:ie", stem_change_inclusions: ["PresInd"], conjugate_only: ["s3"]},
    // normalizar: null,
    // obedecer: null,
    obtener: {irregular: {base: "tener"}},
    // ocurrir: null,
    // ofrecer: null,
    oír: {conjugation_family: "oír", irregular: {base: "oír"}}, // ChatGPT
    oponer: {irregular: {base: "poner"}},
    // orar: null,
    // organizar: null,
    // pagar: null,
    // paralizar: null,
    // parar: null,
    // parecer: null,
    // partir: null,
    // pasar: null,
    // pasear: null,
    // patinar: null,
    pedir: {stem_change_type: "e:i"},
    // peinar: null,
    pensar: {stem_change_type: "e:ie", stem_change_inclusions: ["PresInd"]},
    perder: {stem_change_type: "e:ie", stem_change_inclusions: ["PresInd"]},
    // permanecer: null,
    perseguir: {irregular: {base: "seguir"}, stem_change_type: "e:i", stem_change_inclusions: ["PresInd", "PastInd"]},    // except for yo, similar to {stem_change_type: "e:ie", stem_change_inclusions: ["PresInd"]},
    // pertenecer: null,
    pescar: {model: "sacar"},
    picar: {model: "sacar"},
    platicar: {model: "sacar"},
    poder: {irregular: {base: "poder"}, stem_change_type: "o:ue", stem_change_inclusions: ["PresInd"]},
    // politizar: null,
    poner: {conjugation_family: "poner", irregular: {base: "poner"}}, // ChatGPT
    posponer: {irregular: {base: "poner"}},
    practicar: {model: "sacar"},
    preferir: {stem_change_type: "e:ie"}, // ChatGPT
    // preguntar: null,
    // preocupar: null,
    // preparar: null,
    // presentar: null,
    probar: {stem_change_type: "o:ue", stem_change_inclusions: ["PresInd"]},
    producir: {irregular: {base: "conducir"}},
    // profundizar: null,
    // programar: null,
    promover: {stem_change_type: "o:ue", stem_change_inclusions: ["PresInd"]},
    proponer: {irregular: {base: "poner"}},
    proseguir: {irregular: {base: "seguir"}, stem_change_type: "e:i", stem_change_inclusions: ["PresInd", "PastInd"]},    // except for yo, similar to {stem_change_type: "e:ie", stem_change_inclusions: ["PresInd"]},
    // protagonizar: null,
    // proteger: null,
    provocar: {model: "sacar"},
    publicar: {model: "sacar"},
    quebrar: {stem_change_type: "e:ie", stem_change_inclusions: ["PresInd"]},
    // quedar: null,
    querer: {irregular: {base: "querer"}, stem_change_type: "e:ie", stem_change_inclusions: ["PresInd","PresSub","FutInd","CmdPos","CmdNeg"]},
    // quitar: null,
    rascar: {model: "sacar"},
    // realizar: null,
    // rebautizar: null,
    recalcar: {model: "sacar"},
    recalentar: {stem_change_type: "e:ie", stem_change_inclusions: ["PresInd"]},
    // rechazar: null,
    // recibir: null,
    // recoger: null,
    recomendar: {stem_change_type: "e:ie", stem_change_inclusions: ["PresInd"]},
    recomenzar: {stem_change_type: "e:ie", stem_change_inclusions: ["PresInd"]},
    // reconocer: null,
    recontar: {stem_change_type: "o:ue", stem_change_inclusions: ["PresInd"]},
    recordar: {stem_change_type: "o:ue", stem_change_inclusions: ["PresInd"]},
    reducir: {irregular: {base: "conducir"}},
    // reemplazar: null,
    reencontrar: {stem_change_type: "o:ue", stem_change_inclusions: ["PresInd"]},
    // reflejar: null,
    reforzar: {model: "forzar", stem_change_type: "o:ue", stem_change_inclusions: ["PresInd"]},
    // regatear: null,
    regir: {stem_change_type: "e:i", stem_change_inclusions: ["PresInd","PastInd"]},
    // regresar: null,
    // regularizar: null,
    remover: {stem_change_type: "o:ue", stem_change_inclusions: ["PresInd"]},
    repetir: {stem_change_type: "e:i"},
    replicar: {model: "sacar"},
    reponer: {irregular: {base: "poner"}},
    reprobar: {stem_change_type: "o:ue", stem_change_inclusions: ["PresInd"]},
    reproducir: {irregular: {base: "conducir"}},
    // resignar: null,
    resolver: {stem_change_type: "o:ue", stem_change_inclusions: ["PresInd"]},
    // responder: null,
    retener: {irregular: {base: "tener"}},
    reunir: {model: "reunir", stem_change_type: "u:ú", stem_change_inclusions: ["PresInd","PresSub","CmdPos","CmdNeg"]},
    // revisar: null,
    revolver: {stem_change_type: "o:ue", stem_change_inclusions: ["PresInd"]},
    // rezar: null,
    saber: {irregular: {base: "saber"}},
    sacar: {model: "sacar"}, // ChatGPT
    // sacer: null,
    sacrificar: {model: "sacar"},
    // sacudir: null,
    salir: {irregular: {base: "salir"}},
    satisfacer: {irregular: {base: "hacer"}},
    seguir: {conjugation_family: "seguir", irregular: {base: "seguir"}, stem_change_type: "e:i", stem_change_inclusions: ["PresInd", "PastInd"]},    // except for yo, similar to {stem_change_type: "e:ie", stem_change_inclusions: ["PresInd"]},
    secar: {model: "sacar"},
    seducir: {irregular: {base: "conducir"}},
    // seleccionar: null,
    sentar: {stem_change_type: "e:ie", stem_change_inclusions: ["PresInd"]},
    sentir: {stem_change_type: "e:ie"},
    ser: {irregular: {base: "ser"}},
    servir: {stem_change_type: "e:i"},
    significar: {model: "sacar"},
    // simbolizar: null,
    sobrecalentar: {stem_change_type: "e:ie", stem_change_inclusions: ["PresInd"]},
    sobrevolar: {stem_change_type: "o:ue", stem_change_inclusions: ["PresInd"]},
    soldar: {stem_change_type: "o:ue", stem_change_inclusions: ["PresInd"]},
    // solidarizar: null,
    soltar: {stem_change_type: "o:ue", stem_change_inclusions: ["PresInd"]},
    sonar: {stem_change_type: "o:ue", stem_change_inclusions: ["PresInd"]},
    soñar: {stem_change_type: "o:ue", stem_change_inclusions: ["PresInd"]},
    // sorprender: null,   // canciones, podcasts, news
    sostener: {irregular: {base: "tener"}},
    // subir: null,
    // sufrir: null,
    suponer: {irregular: {base: "poner"}},
    sustituir: {irregular: {base: "huir"}},
    temblar: {stem_change_type: "e:ie", stem_change_inclusions: ["PresInd"]},
    // temer: null,
    tender: {stem_change_type: "e:ie", stem_change_inclusions: ["PresInd"]},
    tener: {conjugation_family: "tener", irregular: {base: "tener"}, stem_change_type: "e:ie", stem_change_inclusions: ["PresInd"]},  // ChatGPT
    // terminar: null,
    // tirar: null,
    tocar: {model: "sacar"},
    // tomar: null,
    // trabajar: null,
    traducir: {irregular: {base: "conducir"}},
    traer: {conjugation_family: "traer", irregular: {base: "traer"}},
    traficar: {model: "sacar"},
    // tranquilizar: null,
    // tratar: null,
    triplicar: {model: "sacar"},
    trompezar: {stem_change_type: "e:ie", stem_change_inclusions: ["PresInd"]},
    tropezar: {stem_change_type: "e:ie", stem_change_inclusions: ["PresInd"]},
    ubicar: {model: "sacar"},
    // unir: null,
    unificar: {model: "sacar"},
    // usar: null,
    // utilizar: null,
    vaciar: {conjugation_family: "iar", irregular: {base: "vaciar"} }, // ChatGPT
    variar: {irregular: {base: "vaciar"}},
    // vender: null,
    venir: {irregular: {base: "venir"}, stem_change_type: "e:ie", stem_change_inclusions: ["PresInd", "PastInd"]}, // ChatGPT
    ver: {irregular: {base: "ver"}},
    verificar: {model: "sacar"},
    vestir: {stem_change_type: "e:ie", stem_change_inclusions: ["PresInd"]},
    // viajar: null,
    // visitar: null,
    // visualizar: null,
    // vivir: null,
    volar: {stem_change_type: "o:ue", stem_change_inclusions: ["PresInd"]},
    volcar: {stem_change_type: "o:ue", stem_change_inclusions: ["PresInd"]},
    volver: {stem_change_type: "o:ue", stem_change_inclusions: ["PresInd"]},
}


export function getAnnotations(infinitive: string, tense_mood: VerbTenseMood) : VerbConjugationAnnotation {
    const unconfirmed = (infinitive in verb_conjugation_rules) ? undefined : true
    const annotations: VerbConjugationAnnotation = {tense_mood, unconfirmed}
    return annotations
}
