import { assert_TenseMood, assert_typographicalChange } from "./test-support.js"



// -ar
assert_TenseMood("amar", "PresInd", {s1: "amo", s2: "amas", s3: "ama", p1: "amamos", p2: "amáis", p3: "aman"})
assert_TenseMood("amar", "PresSub", {s1: "ame", s2: "ames", s3: "ame", p1: "amemos", p2: "améis", p3: "amen"})
assert_TenseMood("amar", "PastInd", {s1: "amé", s2: "amaste", s3: "amó", p1: "amamos", p2: "amasteis", p3: "amaron"})
assert_TenseMood("amar", "PastImp", {s1: "amaba", s2: "amabas", s3: "amaba", p1: "amábamos", p2: "amabais", p3: "amaban"})
assert_TenseMood("amar", "FutInd", {s1: "amaré", s2: "amarás", s3: "amará", p1: "amaremos", p2: "amaréis", p3: "amarán"})
assert_TenseMood("amar", "FutCond", {s1: "amaría", s2: "amarías", s3: "amaría", p1: "amaríamos", p2: "amaríais", p3: "amarían"})
assert_TenseMood("amar", "CmdPos", {s1: null, s2: "ama", s3: "ame", p1: "amemos", p2: "amad", p3: "amen"})
assert_TenseMood("amar", "CmdNeg", {s1: null, s2: "ames", s3: "ame", p1: "amemos", p2: "améis", p3: "amen"})


// -er
assert_TenseMood("beber", "PresInd", {s1: "bebo", s2: "bebes", s3: "bebe", p1: "bebemos", p2: "bebéis", p3: "beben"})
assert_TenseMood("beber", "PresSub", {s1: "beba", s2: "bebas", s3: "beba", p1: "bebamos", p2: "bebáis", p3: "beban"})
assert_TenseMood("beber", "PastInd", {s1: "bebí", s2: "bebiste", s3: "bebió", p1: "bebimos", p2: "bebisteis", p3: "bebieron"})
assert_TenseMood("beber", "PastImp", {s1: "bebía", s2: "bebías", s3: "bebía",  p1: "bebíamos", p2: "bebíais", p3: "bebían"})
assert_TenseMood("beber", "FutInd", {s1: "beberé", s2: "beberás", s3: "beberá", p1: "beberemos", p2: "beberéis", p3: "beberán"})
assert_TenseMood("beber", "FutCond", {s1: "bebería", s2: "beberías", s3: "bebería", p1: "beberíamos", p2: "beberíais", p3: "beberían"})
assert_TenseMood("beber", "CmdPos", {s1: null, s2: "bebe", s3: "beba", p1: "bebamos", p2: "bebed", p3: "beban"})
assert_TenseMood("beber", "CmdNeg", {s1: null, s2: "bebas", s3: "beba", p1: "bebamos", p2: "bebáis", p3: "beban"})


// -ir
assert_TenseMood("partir", "PresInd", {s1: "parto", s2: "partes", s3: "parte", p1: "partimos", p2: "partís", p3: "parten"})
assert_TenseMood("partir", "PresSub", {s1: "parta", s2: "partas", s3: "parta", p1: "partamos", p2: "partáis", p3: "partan"})
assert_TenseMood("partir", "PastInd", {s1: "partí", s2: "partiste", s3: "partió", p1: "partimos", p2: "partisteis", p3: "partieron"})
assert_TenseMood("partir", "PastImp", {s1: "partía", s2: "partías", s3: "partía",  p1: "partíamos", p2: "partíais", p3: "partían"})
assert_TenseMood("partir", "FutInd", {s1: "partiré", s2: "partirás", s3: "partirá", p1: "partiremos", p2: "partiréis", p3: "partirán"})
assert_TenseMood("partir", "FutCond", {s1: "partiría", s2: "partirías", s3: "partiría", p1: "partiríamos", p2: "partiríais", p3: "partirían"})
assert_TenseMood("partir", "CmdPos", {s1: null, s2: "parte", s3: "parta", p1: "partamos", p2: "partid", p3: "partan"})
assert_TenseMood("partir", "CmdNeg", {s1: null, s2: "partas", s3: "parta", p1: "partamos", p2: "partáis", p3: "partan"})


assert_TenseMood("caber", "PresInd", {s1:"quepo",s2:"cabes",s3:"cabe",p1:"cabemos",p2:"cabéis",p3:"caben","vos":"cabés"})
assert_TenseMood("caber", "PresSub", {s1:"quepa",s2:"quepas",s3:"quepa",p1:"quepamos",p2:"quepáis",p3:"quepan","vos":"quepas"})
assert_TenseMood("caber", "PastInd", {s1:"cupe",s2:"cupiste",s3:"cupo",p1:"cupimos",p2:"cupisteis",p3:"cupieron","vos":"cupiste"})
assert_TenseMood("caber", "PastImp", {s1:"cabía",s2:"cabías",s3:"cabía",p1:"cabíamos",p2:"cabíais",p3:"cabían","vos":"cabías"})
assert_TenseMood("caber", "FutInd", {s1:"cabré",s2:"cabrás",s3:"cabrá",p1:"cabremos",p2:"cabréis",p3:"cabrán","vos":"cabrás"})
assert_TenseMood("caber", "FutCond", {s1:"cabría",s2:"cabrías",s3:"cabría",p1:"cabríamos",p2:"cabríais",p3:"cabrían","vos":"cabrías"})
assert_TenseMood("caber", "CmdPos", {s1:null,s2:"cabe",s3:"quepa",p1:"quepamos",p2:"cabed",p3:"quepan","vos":"cabé"})
assert_TenseMood("caber", "CmdNeg", {s1:null,s2:"quepas",s3:"quepa",p1:"quepamos",p2:"quepáis",p3:"quepan","vos":"quepas"})

assert_TenseMood("caer", "PresInd", {s1:"caigo",s2:"caes",s3:"cae",p1:"caemos",p2:"caéis",p3:"caen","vos":"caés"})
assert_TenseMood("caer", "PresSub", {s1:"caiga",s2:"caigas",s3:"caiga",p1:"caigamos",p2:"caigáis",p3:"caigan","vos":"caigas"})
assert_TenseMood("caer", "PastInd", {s1:"caí",s2:"caíste",s3:"cayó",p1:"caímos",p2:"caísteis",p3:"cayeron","vos":"caíste"})
assert_TenseMood("caer", "PastImp", {s1:"caía",s2:"caías",s3:"caía",p1:"caíamos",p2:"caíais",p3:"caían","vos":"caías"})
assert_TenseMood("caer", "FutInd", {s1:"caeré",s2:"caerás",s3:"caerá",p1:"caeremos",p2:"caeréis",p3:"caerán","vos":"caerás"})
assert_TenseMood("caer", "FutCond", {s1:"caería",s2:"caerías",s3:"caería",p1:"caeríamos",p2:"caeríais",p3:"caerían","vos":"caerías"})
assert_TenseMood("caer", "CmdPos", {s1:null,s2:"cae",s3:"caiga",p1:"caigamos",p2:"caed",p3:"caigan","vos":"caé"})
assert_TenseMood("caer", "CmdNeg", {s1:null,s2:"caigas",s3:"caiga",p1:"caigamos",p2:"caigáis",p3:"caigan","vos":["caigas","*caigás"]})

assert_TenseMood("conducir", "PresInd", {s1:"conduzco",s2:"conduces",s3:"conduce",p1:"conducimos",p2:"conducís",p3:"conducen","vos":"conducís"})
assert_TenseMood("conducir", "PresSub", {s1:"conduzca",s2:"conduzcas",s3:"conduzca",p1:"conduzcamos",p2:"conduzcáis",p3:"conduzcan","vos":"conduzcas"})
assert_TenseMood("conducir", "PastInd", {s1:"conduje",s2:"condujiste",s3:"condujo",p1:"condujimos",p2:"condujisteis",p3:"condujeron","vos":"condujiste"})
assert_TenseMood("conducir", "PastImp", {s1:"conducía",s2:"conducías",s3:"conducía",p1:"conducíamos",p2:"conducíais",p3:"conducían","vos":"conducías"})
assert_TenseMood("conducir", "FutInd", {s1:"conduciré",s2:"conducirás",s3:"conducirá",p1:"conduciremos",p2:"conduciréis",p3:"conducirán","vos":"conducirás"})
assert_TenseMood("conducir", "FutCond", {s1:"conduciría",s2:"conducirías",s3:"conduciría",p1:"conduciríamos",p2:"conduciríais",p3:"conducirían","vos":"conducirías"})
assert_TenseMood("conducir", "CmdPos", {s1:null,s2:"conduce",s3:"conduzca",p1:"conduzcamos",p2:"conducid",p3:"conduzcan","vos":"conducí"})
assert_TenseMood("conducir", "CmdNeg", {s1:null,s2:"conduzcas",s3:"conduzca",p1:"conduzcamos",p2:"conduzcáis",p3:"conduzcan","vos":"conduzcas"})

assert_TenseMood("dar", "PresInd", {s1: "doy", s2: "das", s3: "da", p1: "damos", p2: "dais", p3: "dan"})
assert_TenseMood("dar", "PresSub", {s1: "dé", s2: "des", s3: "dé", p1: "demos", p2: "deis", p3: "den"})
assert_TenseMood("dar", "PastInd", {s1: "di", s2: "diste", s3: "dio",  p1: "dimos", p2: "disteis", p3: "dieron"})
assert_TenseMood("dar", "PastImp", {s1: "daba", s2: "dabas", s3: "daba",  p1: "dábamos", p2: "dabais", p3: "daban"})
assert_TenseMood("dar", "FutInd", {s1: "daré", s2: "darás", s3: "dará", p1: "daremos", p2: "daréis", p3: "darán"})
assert_TenseMood("dar", "FutCond", {s1: "daría", s2: "darías", s3: "daría", p1: "daríamos", p2: "daríais", p3: "darían"})
assert_TenseMood("dar", "CmdPos", {s1: null, s2: "da", s3: "dé", p1: "demos", p2: "dad", p3: "den"})
assert_TenseMood("dar", "CmdNeg", {s1: null, s2: "des", s3: "dé", p1: "demos", p2: "deis", p3: "den"})

assert_TenseMood("decir", "PresInd", {s1: "digo", s2: "dices", s3: "dice",     p1: "decimos", p2: "decís", p3: "dicen"})
assert_TenseMood("decir", "PresSub", {s1: "diga", s2: "digas", s3: "diga",     p1: "digamos", p2: "digáis", p3: "digan"})
assert_TenseMood("decir", "PastInd", {s1: "dije", s2: "dijiste", s3: "dijo",   p1: "dijimos", p2: "dijisteis", p3: "dijeron"})
assert_TenseMood("decir", "PastImp", {s1: "decía", s2: "decías", s3: "decía",  p1: "decíamos", p2: "decíais", p3: "decían"})
assert_TenseMood("decir", "FutInd",  {s1: "diré", s2: "dirás", s3: "dirá",     p1: "diremos",  p2: "diréis", p3: "dirán" })
assert_TenseMood("decir", "FutCond", {s1: "diría", s2: "dirías", s3: "diría",  p1: "diríamos", p2: "diríais", p3: "dirían" })
assert_TenseMood("decir", "CmdPos",  {s1: null,   s2: "di", s3: "diga",        p1: "digamos",  p2: "decid", p3: "digan" })
assert_TenseMood("decir", "CmdNeg",  {s1: null,   s2: "digas", s3: "diga",     p1: "digamos",  p2: "digáis", p3: "digan" })

assert_TenseMood("detener", "PresInd", {s1:"detengo",s2:"detienes",s3:"detiene",p1:"detenemos",p2:"detenéis",p3:"detienen","vos":"detenés"})
assert_TenseMood("detener", "PresSub", {s1:"detenga",s2:"detengas",s3:"detenga",p1:"detengamos",p2:"detengáis",p3:"detengan","vos":"detengas"})
assert_TenseMood("detener", "PastInd", {s1:"detuve",s2:"detuviste",s3:"detuvo",p1:"detuvimos",p2:"detuvisteis",p3:"detuvieron","vos":"detuviste"})
assert_TenseMood("detener", "PastImp", {s1:"detenía",s2:"detenías",s3:"detenía",p1:"deteníamos",p2:"deteníais",p3:"detenían","vos":"detenías"})
assert_TenseMood("detener", "FutInd", {s1:"detendré",s2:"detendrás",s3:"detendrá",p1:"detendremos",p2:"detendréis",p3:"detendrán","vos":"detendrás"})
assert_TenseMood("detener", "FutCond", {s1:"detendría",s2:"detendrías",s3:"detendría",p1:"detendríamos",p2:"detendríais",p3:"detendrían","vos":"detendrías"})
assert_TenseMood("detener", "CmdPos", {s1:null,s2:"detén",s3:"detenga",p1:"detengamos",p2:"detened",p3:"detengan","vos":"detené"})
assert_TenseMood("detener", "CmdNeg", {s1:null,s2:"detengas",s3:"detenga",p1:"detengamos",p2:"detengáis",p3:"detengan","vos":"detengas"})

assert_TenseMood("erguir", "PresInd", {s1:["irgo","yergo"],s2:["irgues","yergues"],s3:["irgue","yergue"],p1:"erguimos",p2:"erguís",p3:["irguen","yerguen"],"vos":"erguís"})
assert_TenseMood("erguir", "PresSub", {s1:["irga","yerga"],s2:["irgas","yergas"],s3:["irga","yerga"],p1:["irgamos","yergamos"],p2:["irgáis","yergáis"],p3:["irgan","yergan"],"vos":"yergas"})
assert_TenseMood("erguir", "PastInd", {s1:"erguí",s2:"erguiste",s3:"irguió",p1:"erguimos",p2:"erguisteis",p3:"irguieron","vos":"erguiste"})
assert_TenseMood("erguir", "PastImp", {s1:"erguía",s2:"erguías",s3:"erguía",p1:"erguíamos",p2:"erguíais",p3:"erguían","vos":"erguías"})
assert_TenseMood("erguir", "FutInd", {s1:"erguiré",s2:"erguirás",s3:"erguirá",p1:"erguiremos",p2:"erguiréis",p3:"erguirán","vos":"erguirás"})
assert_TenseMood("erguir", "FutCond", {s1:"erguiría",s2:"erguirías",s3:"erguiría",p1:"erguiríamos",p2:"erguiríais",p3:"erguirían","vos":"erguirías"})
assert_TenseMood("erguir", "CmdPos", {s1:null,s2:["irgue","yergue"],s3:["irga","yerga"],p1:["irgamos","yergamos"],p2:"erguid",p3:["irgan","yergan"],"vos":"erguí"})
assert_TenseMood("erguir", "CmdNeg", {s1:null,s2:["irgas","yergas"],s3:["irga","yerga"],p1:["irgamos","yergamos"],p2:["irgáis","yergáis"],p3:["irgan","yergan"],"vos":"yergas"})

assert_TenseMood("estar", "PresInd", {s1: "estoy", s2: "estás", s3: "está",         p1: "estamos", p2: "estáis", p3: "están" })
assert_TenseMood("estar", "PresSub", { s1: "esté", s2: "estés", s3: "esté",         p1: "estemos", p2: "estéis", p3: "estén" })
assert_TenseMood("estar", "PastInd", {s1: "estuve", s2: "estuviste", s3: "estuvo",  p1: "estuvimos", p2: "estuvisteis", p3: "estuvieron"})
assert_TenseMood("estar", "PastImp", {s1: "estaba", s2: "estabas", s3: "estaba",    p1: "estábamos", p2: "estabais", p3: "estaban"})
assert_TenseMood("estar", "FutInd", {s1: "estaré", s2: "estarás", s3: "estará",     p1: "estaremos", p2: "estaréis", p3: "estarán"})
assert_TenseMood("estar", "FutCond", {s1: "estaría", s2: "estarías", s3: "estaría", p1: "estaríamos", p2: "estaríais", p3: "estarían"})
assert_TenseMood("estar", "CmdPos",  {s1: null,   s2: "está", s3: "esté",           p1: "estemos",  p2: "estad", p3: "estén" })
assert_TenseMood("estar", "CmdNeg",  {s1: null,   s2: "estés", s3: "esté",          p1: "estemos", p2: "estéis", p3: "estén" })

// based on "vaciar", but has changes to the accents
assert_TenseMood("guiar", "PresInd", {s1:"guío",s2:"guías",s3:"guía",p1:"guiamos",p2:"guiais",p3:"guían","vos":"guias"})
assert_TenseMood("guiar", "PresSub", {s1:"guíe",s2:"guíes",s3:"guíe",p1:"guiemos",p2:"guieis",p3:"guíen","vos":["guíes",""]})
assert_TenseMood("guiar", "PastInd", {s1:"guie",s2:"guiaste",s3:"guio",p1:"guiamos",p2:"guiasteis",p3:"guiaron","vos":"guiaste"})
assert_TenseMood("guiar", "PastImp", {s1:"guiaba",s2:"guiabas",s3:"guiaba",p1:"guiábamos",p2:"guiabais",p3:"guiaban","vos":"guiabas"})
assert_TenseMood("guiar", "FutInd", {s1:"guiaré",s2:"guiarás",s3:"guiará",p1:"guiaremos",p2:"guiaréis",p3:"guiarán","vos":"guiarás"})
assert_TenseMood("guiar", "FutCond", {s1:"guiaría",s2:"guiarías",s3:"guiaría",p1:"guiaríamos",p2:"guiaríais",p3:"guiarían","vos":"guiarías"})
assert_TenseMood("guiar", "CmdPos", {s1:null,s2:"guía",s3:"guíe",p1:"guiemos",p2:"guiad",p3:"guíen","vos":"guia"})
assert_TenseMood("guiar", "CmdNeg", {s1:null,s2:"guíes",s3:"guíe",p1:"guiemos",p2:"guieis",p3:"guíen","vos":["guíes","*guiés"]})

// NOTE: supports alternate form for s3 => impersonal: hay
assert_TenseMood("haber", "PresInd", {s1: "he", s2: "has", s3: ["hay", "ha"],     p1: "hemos", p2: "habéis", p3: "han"})
assert_TenseMood("haber", "PresSub", {s1: "haya", s2: "hayas", s3: "haya",        p1: "hayamos", p2: "hayáis", p3: "hayan" })
assert_TenseMood("haber", "PastInd", {s1: "hube", s2: "hubiste", s3: "hubo",      p1: "hubimos", p2: "hubisteis", p3: "hubieron"})
assert_TenseMood("haber", "PastImp", {s1: "había", s2: "habías", s3: "había",     p1: "habíamos", p2: "habíais", p3: "habían"})
assert_TenseMood("haber", "FutInd", {s1: "habré", s2: "habrás", s3: "habrá",      p1: "habremos", p2: "habréis", p3: "habrán"})
assert_TenseMood("haber", "FutCond", {s1: "habría", s2: "habrías", s3: "habría",  p1: "habríamos", p2: "habríais", p3: "habrían"})
assert_TenseMood("haber", "CmdPos",  {s1: null,   s2: ["habe", "he"], s3: "haya", p1: "hayamos",  p2: "habed", p3: "hayan" })
assert_TenseMood("haber", "CmdNeg",  {s1: null,   s2: "hayas", s3: "haya",        p1: "hayamos",  p2: "hayáis", p3: "hayan" })

assert_TenseMood("hacer", "PresInd", {s1: "hago", s2: "haces", s3: "hace",        p1: "hacemos", p2: "hacéis", p3: "hacen"})
assert_TenseMood("hacer", "PresSub", {s1: "haga", s2: "hagas", s3: "haga",        p1: "hagamos", p2: "hagáis", p3: "hagan" })
assert_TenseMood("hacer", "PastInd", {s1: "hice", s2: "hiciste", s3: "hizo",      p1: "hicimos", p2: "hicisteis", p3: "hicieron"})
assert_TenseMood("hacer", "PastImp", {s1: "hacía", s2: "hacías", s3: "hacía",     p1: "hacíamos", p2: "hacíais", p3: "hacían"})
assert_TenseMood("hacer", "FutInd",  {s1: "haré", s2: "harás", s3: "hará",         p1: "haremos", p2: "haréis", p3: "harán"})
assert_TenseMood("hacer", "FutCond", {s1: "haría", s2: "harías", s3: "haría",     p1: "haríamos", p2: "haríais", p3: "harían"})
assert_TenseMood("hacer", "CmdPos",  {s1: null,   s2: "haz", s3: "haga",          p1: "hagamos",  p2: "haced", p3: "hagan" })
assert_TenseMood("hacer", "CmdNeg",  {s1: null,   s2: "hagas", s3: "haga",        p1: "hagamos",  p2: "hagáis", p3: "hagan" })

assert_TenseMood("huir", "PresInd", {s1:"huyo",s2:"huyes",s3:"huye",p1:"huimos",p2:"huis",p3:"huyen","vos":"huis"})
assert_TenseMood("huir", "PresSub", {s1:"huya",s2:"huyas",s3:"huya",p1:"huyamos",p2:"huyáis",p3:"huyan","vos":"huyas"})
assert_TenseMood("huir", "PastInd", {s1:"hui",s2:"huiste",s3:"huyó",p1:"huimos",p2:"huisteis",p3:"huyeron","vos":"huiste"})
assert_TenseMood("huir", "PastImp", {s1:"huía",s2:"huías",s3:"huía",p1:"huíamos",p2:"huíais",p3:"huían","vos":"huías"})
assert_TenseMood("huir", "FutInd", {s1:"huiré",s2:"huirás",s3:"huirá",p1:"huiremos",p2:"huiréis",p3:"huirán","vos":"huirás"})
assert_TenseMood("huir", "FutCond", {s1:"huiría",s2:"huirías",s3:"huiría",p1:"huiríamos",p2:"huiríais",p3:"huirían","vos":"huirías"})
assert_TenseMood("huir", "CmdPos", {s1:null,s2:"huye",s3:"huya",p1:"huyamos",p2:"huid",p3:"huyan","vos":"hui"})
assert_TenseMood("huir", "CmdNeg", {s1:null,s2:"huyas",s3:"huya",p1:"huyamos",p2:"huyáis",p3:"huyan","vos":"huyas"})

assert_TenseMood("ir", "PresInd", {s1: "voy", s2: "vas", s3: "va",                p1: "vamos", p2: "vais", p3: "van"})
assert_TenseMood("ir", "PresSub", {s1: "vaya", s2: "vayas", s3: "vaya",           p1: "vayamos", p2: "vayáis", p3: "vayan" })
assert_TenseMood("ir", "PastInd", {s1: "fui", s2: "fuiste", s3: "fue",            p1: "fuimos", p2: "fuisteis", p3: "fueron"})
assert_TenseMood("ir", "PastImp", {s1: "iba", s2: "ibas", s3: "iba",              p1: "íbamos", p2: "ibais", p3: "iban"})
assert_TenseMood("ir", "FutInd",  {s1: "iré", s2: "irás", s3: "irá",              p1: "iremos", p2: "iréis", p3: "irán"})
assert_TenseMood("ir", "FutCond", {s1: "iría", s2: "irías", s3: "iría",           p1: "iríamos", p2: "iríais", p3: "irían"})
assert_TenseMood("ir", "CmdPos",  {s1: null, s2: "ve", s3: "vaya",                p1: ["vayamos", "vamos"], p2: "id", p3: "vayan"})
assert_TenseMood("ir", "CmdNeg",  {s1: null, s2: "vayas", s3: "vaya",             p1: "vayamos", p2: "vayáis", p3: "vayan"})

assert_TenseMood("jugar", "PresInd", {s1:"juego",s2:"juegas",s3:"juega",p1:"jugamos",p2:"jugáis",p3:"juegan","vos":"jugás"})
assert_TenseMood("jugar", "PresSub", {s1:"juegue",s2:"juegues",s3:"juegue",p1:"juguemos",p2:"juguéis",p3:"jueguen","vos":"juegues"})
assert_TenseMood("jugar", "PastInd", {s1:"jugué",s2:"jugaste",s3:"jugó",p1:"jugamos",p2:"jugasteis",p3:"jugaron","vos":"jugaste"})
assert_TenseMood("jugar", "PastImp", {s1:"jugaba",s2:"jugabas",s3:"jugaba",p1:"jugábamos",p2:"jugabais",p3:"jugaban","vos":"jugabas"})
assert_TenseMood("jugar", "FutInd", {s1:"jugaré",s2:"jugarás",s3:"jugará",p1:"jugaremos",p2:"jugaréis",p3:"jugarán","vos":"jugarás"})
assert_TenseMood("jugar", "FutCond", {s1:"jugaría",s2:"jugarías",s3:"jugaría",p1:"jugaríamos",p2:"jugaríais",p3:"jugarían","vos":"jugarías"})
assert_TenseMood("jugar", "CmdPos", {s1:null,s2:"juega",s3:"juegue",p1:"juguemos",p2:"jugad",p3:"jueguen","vos":"jugá"})
assert_TenseMood("jugar", "CmdNeg", {s1:null,s2:"juegues",s3:"juegue",p1:"juguemos",p2:"juguéis",p3:"jueguen","vos":["juegues","*jugués"]})

assert_TenseMood("leer", "PresInd", {s1: "leo", s2: "lees", s3: "lee",            p1: "leemos", p2: "leéis", p3: "leen"})
assert_TenseMood("leer", "PresSub", {s1: "lea", s2: "leas", s3: "lea",            p1: "leamos", p2: "leáis", p3: "lean"})
assert_TenseMood("leer", "PastInd", {s1: "leí", s2: "leíste", s3: "leyó",         p1: "leímos", p2: "leísteis", p3: "leyeron"})
assert_TenseMood("leer", "PastImp", {s1: "leía", s2: "leías", s3: "leía",         p1: "leíamos", p2: "leíais", p3: "leían"})
assert_TenseMood("leer", "FutInd", {s1: "leeré", s2: "leerás", s3: "leerá",       p1: "leeremos", p2: "leeréis", p3: "leerán"})
assert_TenseMood("leer", "FutCond", {s1: "leería", s2: "leerías", s3: "leería",   p1: "leeríamos", p2: "leeríais", p3: "leerían"})
assert_TenseMood("leer", "CmdPos", {s1: null, s2: "lee", s3: "lea",               p1: "leamos", p2: "leed", p3: "lean"})
assert_TenseMood("leer", "CmdNeg", {s1: null, s2: "leas", s3: "lea",              p1: "leamos", p2: "leáis", p3: "lean"})

assert_TenseMood("llegar", "PresInd", {s1: "llego", s2: "llegas", s3: "llega", p1: "llegamos", p2: "llegáis", p3: "llegan"})
assert_TenseMood("llegar", "PastInd", {s1: "llegué", s2: "llegaste", s3: "llegó",  p1: "llegamos", p2: "llegasteis", p3: "llegaron"})

assert_TenseMood("oír", "PresInd", {s1:"oigo",s2:"oyes",s3:"oye",p1:"oímos",p2:"oís",p3:"oyen","vos":"oís"})
assert_TenseMood("oír", "PresSub", {s1:"oiga",s2:"oigas",s3:"oiga",p1:"oigamos",p2:"oigáis",p3:"oigan","vos":"oigas"})
assert_TenseMood("oír", "PastInd", {s1:"oí",s2:"oíste",s3:"oyó",p1:"oímos",p2:"oísteis",p3:"oyeron","vos":"oíste"})
assert_TenseMood("oír", "PastImp", {s1:"oía",s2:"oías",s3:"oía",p1:"oíamos",p2:"oíais",p3:"oían","vos":"oías"})
assert_TenseMood("oír", "FutInd", {s1:"oiré",s2:"oirás",s3:"oirá",p1:"oiremos",p2:"oiréis",p3:"oirán","vos":"oirás"})
assert_TenseMood("oír", "FutCond", {s1:"oiría",s2:"oirías",s3:"oiría",p1:"oiríamos",p2:"oiríais",p3:"oirían","vos":"oirías"})
assert_TenseMood("oír", "CmdPos", {s1:null,s2:"oye",s3:"oiga",p1:"oigamos",p2:"oíd",p3:"oigan","vos":"oí"})
assert_TenseMood("oír", "CmdNeg", {s1:null,s2:"oigas",s3:"oiga",p1:"oigamos",p2:"oigáis",p3:"oigan","vos":["oigas","*oigás"]})

assert_TenseMood("poder", "PresInd", {s1:"puedo",s2:"puedes",s3:"puede",p1:"podemos",p2:"podéis",p3:"pueden","vos":"podés"})
assert_TenseMood("poder", "PresSub", {s1:"pueda",s2:"puedas",s3:"pueda",p1:"podamos",p2:"podáis",p3:"puedan","vos":"puedas"})
assert_TenseMood("poder", "PastInd", {s1:"pude",s2:"pudiste",s3:"pudo",p1:"pudimos",p2:"pudisteis",p3:"pudieron","vos":"pudiste"})
assert_TenseMood("poder", "PastImp", {s1:"podía",s2:"podías",s3:"podía",p1:"podíamos",p2:"podíais",p3:"podían","vos":"podías"})
assert_TenseMood("poder", "FutInd", {s1:"podré",s2:"podrás",s3:"podrá",p1:"podremos",p2:"podréis",p3:"podrán","vos":"podrás"})
assert_TenseMood("poder", "FutCond", {s1:"podría",s2:"podrías",s3:"podría",p1:"podríamos",p2:"podríais",p3:"podrían","vos":"podrías"})
assert_TenseMood("poder", "CmdPos", {s1:null,s2:"puede",s3:"pueda",p1:"podamos",p2:"poded",p3:"puedan","vos":"podé"})
assert_TenseMood("poder", "CmdNeg", {s1:null,s2:"puedas",s3:"pueda",p1:"podamos",p2:"podáis",p3:"puedan","vos":["puedas","*podás"]})

assert_TenseMood("poner", "PresInd", {s1:"pongo",s2:"pones",s3:"pone",p1:"ponemos",p2:"ponéis",p3:"ponen","vos":"ponés"})
assert_TenseMood("poner", "PresSub", {s1:"ponga",s2:"pongas",s3:"ponga",p1:"pongamos",p2:"pongáis",p3:"pongan","vos":"pongas"})
assert_TenseMood("poner", "PastInd", {s1:"puse",s2:"pusiste",s3:"puso",p1:"pusimos",p2:"pusisteis",p3:"pusieron","vos":"pusiste"})
assert_TenseMood("poner", "PastImp", {s1:"ponía",s2:"ponías",s3:"ponía",p1:"poníamos",p2:"poníais",p3:"ponían","vos":"ponías"})
assert_TenseMood("poner", "FutInd", {s1:"pondré",s2:"pondrás",s3:"pondrá",p1:"pondremos",p2:"pondréis",p3:"pondrán","vos":"pondrás"})
assert_TenseMood("poner", "FutCond", {s1:"pondría",s2:"pondrías",s3:"pondría",p1:"pondríamos",p2:"pondríais",p3:"pondrían","vos":"pondrías"})
assert_TenseMood("poner", "CmdPos", {s1:null,s2:"pon",s3:"ponga",p1:"pongamos",p2:"poned",p3:"pongan","vos":"poné"})
assert_TenseMood("poner", "CmdNeg", {s1:null,s2:"pongas",s3:"ponga",p1:"pongamos",p2:"pongáis",p3:"pongan","vos":["pongas","*pongás"]})

assert_TenseMood("querer", "PresInd", {s1:"quiero",s2:"quieres",s3:"quiere",p1:"queremos",p2:"queréis",p3:"quieren","vos":"querés"})
assert_TenseMood("querer", "PresSub", {s1:"quiera",s2:"quieras",s3:"quiera",p1:"queramos",p2:"queráis",p3:"quieran","vos":"quieras"})
assert_TenseMood("querer", "PastInd", {s1:"quise",s2:"quisiste",s3:"quiso",p1:"quisimos",p2:"quisisteis",p3:"quisieron","vos":"quisiste"})
assert_TenseMood("querer", "PastImp", {s1:"quería",s2:"querías",s3:"quería",p1:"queríamos",p2:"queríais",p3:"querían","vos":"querías"})
assert_TenseMood("querer", "FutInd",  {s1:"querré",s2:"querrás",s3:"querrá",p1:"querremos",p2:"querréis",p3:"querrán","vos":"querrás"})
assert_TenseMood("querer", "FutCond", {s1:"querría",s2:"querrías",s3:"querría",p1:"querríamos",p2:"querríais",p3:"querrían","vos":"querrías"})
assert_TenseMood("querer", "CmdPos",  {s1:null,s2:"quiere",s3:"quiera",p1:"queramos",p2:"quered",p3:"quieran","vos":"queré"})
assert_TenseMood("querer", "CmdNeg",  {s1:null,s2:"quieras",s3:"quiera",p1:"queramos",p2:"queráis",p3:"quieran","vos":"quieras"})

assert_TenseMood("saber", "PresInd", {s1:"sé",s2:"sabes",s3:"sabe",p1:"sabemos",p2:"sabéis",p3:"saben","vos":"sabés"})
assert_TenseMood("saber", "PresSub", {s1:"sepa",s2:"sepas",s3:"sepa",p1:"sepamos",p2:"sepáis",p3:"sepan","vos":"sepas"})
assert_TenseMood("saber", "PastInd", {s1:"supe",s2:"supiste",s3:"supo",p1:"supimos",p2:"supisteis",p3:"supieron","vos":"supiste"})
assert_TenseMood("saber", "PastImp", {s1:"sabía",s2:"sabías",s3:"sabía",p1:"sabíamos",p2:"sabíais",p3:"sabían","vos":"sabías"})
assert_TenseMood("saber", "FutInd", {s1:"sabré",s2:"sabrás",s3:"sabrá",p1:"sabremos",p2:"sabréis",p3:"sabrán","vos":"sabrás"})
assert_TenseMood("saber", "FutCond", {s1:"sabría",s2:"sabrías",s3:"sabría",p1:"sabríamos",p2:"sabríais",p3:"sabrían","vos":"sabrías"})
assert_TenseMood("saber", "CmdPos", {s1:null,s2:"sabe",s3:"sepa",p1:"sepamos",p2:"sabed",p3:"sepan","vos":"sabé"})
assert_TenseMood("saber", "CmdNeg", {s1:null,s2:"sepas",s3:"sepa",p1:"sepamos",p2:"sepáis",p3:"sepan","vos":["sepas","*sepás"]})

assert_TenseMood("salir", "PresInd", {s1:"salgo",s2:"sales",s3:"sale",p1:"salimos",p2:"salís",p3:"salen","vos":"salís"})
assert_TenseMood("salir", "PresSub", {s1:"salga",s2:"salgas",s3:"salga",p1:"salgamos",p2:"salgáis",p3:"salgan","vos":"salgas"})
assert_TenseMood("salir", "PastInd", {s1:"salí",s2:"saliste",s3:"salió",p1:"salimos",p2:"salisteis",p3:"salieron","vos":"saliste"})
assert_TenseMood("salir", "PastImp", {s1:"salía",s2:"salías",s3:"salía",p1:"salíamos",p2:"salíais",p3:"salían","vos":"salías"})
assert_TenseMood("salir", "FutInd", {s1:"saldré",s2:"saldrás",s3:"saldrá",p1:"saldremos",p2:"saldréis",p3:"saldrán","vos":"saldrás"})
assert_TenseMood("salir", "FutCond", {s1:"saldría",s2:"saldrías",s3:"saldría",p1:"saldríamos",p2:"saldríais",p3:"saldrían","vos":"saldrías"})
assert_TenseMood("salir", "CmdPos", {s1:null,s2:"sal",s3:"salga",p1:"salgamos",p2:"salid",p3:"salgan","vos":"salí"})
assert_TenseMood("salir", "CmdNeg", {s1:null,s2:"salgas",s3:"salga",p1:"salgamos",p2:"salgáis",p3:"salgan","vos":["salgas","*salgás"]})

assert_TenseMood("seguir", "PresInd", {s1:"sigo",s2:"sigues",s3:"sigue",p1:"seguimos",p2:"seguís",p3:"siguen","vos":"seguís"})
assert_TenseMood("seguir", "PresSub", {s1:"siga",s2:"sigas",s3:"siga",p1:"sigamos",p2:"sigáis",p3:"sigan","vos":"sigas"})
assert_TenseMood("seguir", "PastInd", {s1:"seguí",s2:"seguiste",s3:"siguió",p1:"seguimos",p2:"seguisteis",p3:"siguieron","vos":"seguiste"})
assert_TenseMood("seguir", "PastImp", {s1:"seguía",s2:"seguías",s3:"seguía",p1:"seguíamos",p2:"seguíais",p3:"seguían","vos":"seguías"})
assert_TenseMood("seguir", "FutInd", {s1:"seguiré",s2:"seguirás",s3:"seguirá",p1:"seguiremos",p2:"seguiréis",p3:"seguirán","vos":"seguirás"})
assert_TenseMood("seguir", "FutCond", {s1:"seguiría",s2:"seguirías",s3:"seguiría",p1:"seguiríamos",p2:"seguiríais",p3:"seguirían","vos":"seguirías"})
assert_TenseMood("seguir", "CmdPos", {s1:null,s2:"sigue",s3:"siga",p1:"sigamos",p2:"seguid",p3:"sigan","vos":"seguí"})
assert_TenseMood("seguir", "CmdNeg", {s1:null,s2:"sigas",s3:"siga",p1:"sigamos",p2:"sigáis",p3:"sigan","vos":["sigas","*sigás"]})

assert_TenseMood("ser", "PresInd", {s1:"soy",s2:"eres",s3:"es",p1:"somos",p2:"sois",p3:"son","vos":"sos"})
assert_TenseMood("ser", "PresSub", {s1:"sea",s2:"seas",s3:"sea",p1:"seamos",p2:"seáis",p3:"sean","vos":"seas"})
assert_TenseMood("ser", "PastInd", {s1:"fui",s2:"fuiste",s3:"fue",p1:"fuimos",p2:"fuisteis",p3:"fueron","vos":"fuiste"})
assert_TenseMood("ser", "PastImp", {s1:"era",s2:"eras",s3:"era",p1:"éramos",p2:"erais",p3:"eran","vos":"eras"})
assert_TenseMood("ser", "FutInd",  {s1:"seré",s2:"serás",s3:"será",p1:"seremos",p2:"seréis",p3:"serán","vos":"serás"})
assert_TenseMood("ser", "FutCond", {s1:"sería",s2:"serías",s3:"sería",p1:"seríamos",p2:"seríais",p3:"serían","vos":"serías"})
assert_TenseMood("ser", "CmdPos",  {s1:null,s2:"sé",s3:"sea",p1:"seamos",p2:"sed",p3:"sean","vos":"sé"})
assert_TenseMood("ser", "CmdNeg",  {s1:null,s2:"seas",s3:"sea",p1:"seamos",p2:"seáis",p3:"sean","vos":["seas","*seás"]})

assert_TenseMood("tener", "PresInd", {s1:"tengo",s2:"tienes",s3:"tiene",p1:"tenemos",p2:"tenéis",p3:"tienen","vos":"tenés"})
assert_TenseMood("tener", "PresSub", {s1:"tenga",s2:"tengas",s3:"tenga",p1:"tengamos",p2:"tengáis",p3:"tengan","vos":"tengas"})
assert_TenseMood("tener", "PastInd", {s1:"tuve",s2:"tuviste",s3:"tuvo",p1:"tuvimos",p2:"tuvisteis",p3:"tuvieron","vos":"tuviste"})
assert_TenseMood("tener", "PastImp", {s1:"tenía",s2:"tenías",s3:"tenía",p1:"teníamos",p2:"teníais",p3:"tenían","vos":"tenías"})
assert_TenseMood("tener", "FutInd",  {s1:"tendré",s2:"tendrás",s3:"tendrá",p1:"tendremos",p2:"tendréis",p3:"tendrán","vos":"tendrás"})
assert_TenseMood("tener", "FutCond", {s1:"tendría",s2:"tendrías",s3:"tendría",p1:"tendríamos",p2:"tendríais",p3:"tendrían","vos":"tendrías"})
assert_TenseMood("tener", "CmdPos",  {s1:null,s2:"ten",s3:"tenga",p1:"tengamos",p2:"tened",p3:"tengan","vos":"tené"})
assert_TenseMood("tener", "CmdNeg",  {s1:null,s2:"tengas",s3:"tenga",p1:"tengamos",p2:"tengáis",p3:"tengan","vos":"tengas"})

assert_TenseMood("traer", "PresInd", {s1:"traigo",s2:"traes",s3:"trae",p1:"traemos",p2:"traéis",p3:"traen","vos":"traés"})
assert_TenseMood("traer", "PresSub", {s1:"traiga",s2:"traigas",s3:"traiga",p1:"traigamos",p2:"traigáis",p3:"traigan","vos":"traigas"})
assert_TenseMood("traer", "PastInd", {s1:"traje",s2:"trajiste",s3:"trajo",p1:"trajimos",p2:"trajisteis",p3:"trajeron","vos":"trajiste"})
assert_TenseMood("traer", "PastImp", {s1:"traía",s2:"traías",s3:"traía",p1:"traíamos",p2:"traíais",p3:"traían","vos":"traías"})
assert_TenseMood("traer", "FutInd", {s1:"traeré",s2:"traerás",s3:"traerá",p1:"traeremos",p2:"traeréis",p3:"traerán","vos":"traerás"})
assert_TenseMood("traer", "FutCond", {s1:"traería",s2:"traerías",s3:"traería",p1:"traeríamos",p2:"traeríais",p3:"traerían","vos":"traerías"})
assert_TenseMood("traer", "CmdPos", {s1:null,s2:"trae",s3:"traiga",p1:"traigamos",p2:"traed",p3:"traigan","vos":"traé"})
assert_TenseMood("traer", "CmdNeg", {s1:null,s2:"traigas",s3:"traiga",p1:"traigamos",p2:"traigáis",p3:"traigan","vos":["traigas","*traigás"]})

assert_TenseMood("vaciar", "PresInd", {s1:"vacío",s2:"vacías",s3:"vacía",p1:"vaciamos",p2:"vaciáis",p3:"vacían","vos":"vaciás"})
assert_TenseMood("vaciar", "PresSub", {s1:"vacíe",s2:"vacíes",s3:"vacíe",p1:"vaciemos",p2:"vaciéis",p3:"vacíen","vos":["vacíes","*vaciés"]})
assert_TenseMood("vaciar", "PastInd", {s1:"vacié",s2:"vaciaste",s3:"vació",p1:"vaciamos",p2:"vaciasteis",p3:"vaciaron","vos":"vaciaste"})
assert_TenseMood("vaciar", "PastImp", {s1:"vaciaba",s2:"vaciabas",s3:"vaciaba",p1:"vaciábamos",p2:"vaciabais",p3:"vaciaban","vos":"vaciabas"})
assert_TenseMood("vaciar", "FutInd",  {s1:"vaciaré",s2:"vaciarás",s3:"vaciará",p1:"vaciaremos",p2:"vaciaréis",p3:"vaciarán","vos":"vaciarás"})
assert_TenseMood("vaciar", "FutCond", {s1:"vaciaría",s2:"vaciarías",s3:"vaciaría",p1:"vaciaríamos",p2:"vaciaríais",p3:"vaciarían","vos":"vaciarías"})
assert_TenseMood("vaciar", "CmdPos",  {s1:null,s2:"vacía",s3:"vacíe",p1:"vaciemos",p2:"vaciad",p3:"vacíen","vos":"vaciá"})
assert_TenseMood("vaciar", "CmdNeg",  {s1:null,s2:"vacíes",s3:"vacíe",p1:"vaciemos",p2:"vaciéis",p3:"vacíen","vos":["vacíes","*vaciés"]})

assert_TenseMood("venir", "PresInd", {s1:"vengo",s2:"vienes",s3:"viene",p1:"venimos",p2:"venís",p3:"vienen","vos":"venís"})
assert_TenseMood("venir", "PresSub", {s1:"venga",s2:"vengas",s3:"venga",p1:"vengamos",p2:"vengáis",p3:"vengan","vos":"vengas"})
assert_TenseMood("venir", "PastInd", {s1:"vine",s2:"viniste",s3:"vino",p1:"vinimos",p2:"vinisteis",p3:"vinieron","vos":"viniste"})
assert_TenseMood("venir", "PastImp", {s1:"venía",s2:"venías",s3:"venía",p1:"veníamos",p2:"veníais",p3:"venían","vos":"venías"})
assert_TenseMood("venir", "FutInd",  {s1:"vendré",s2:"vendrás",s3:"vendrá",p1:"vendremos",p2:"vendréis",p3:"vendrán","vos":"vendrás"})
assert_TenseMood("venir", "FutCond", {s1:"vendría",s2:"vendrías",s3:"vendría",p1:"vendríamos",p2:"vendríais",p3:"vendrían","vos":"vendrías"})
assert_TenseMood("venir", "CmdPos",  {s1:null,s2:"ven",s3:"venga",p1:"vengamos",p2:"venid",p3:"vengan","vos":"vení"})
assert_TenseMood("venir", "CmdNeg",  {s1:null,s2:"vengas",s3:"venga",p1:"vengamos",p2:"vengáis",p3:"vengan","vos":["vengas","*vengás"]})

assert_TenseMood("ver", "PresInd", {s1:"veo",s2:"ves",s3:"ve",p1:"vemos",p2:"veis",p3:"ven","vos":"ves"})
assert_TenseMood("ver", "PresSub", {s1:"vea",s2:"veas",s3:"vea",p1:"veamos",p2:"veáis",p3:"vean","vos":"veas"})
assert_TenseMood("ver", "PastInd", {s1:"vi",s2:"viste",s3:"vio",p1:"vimos",p2:"visteis",p3:"vieron","vos":"viste"})
assert_TenseMood("ver", "PastImp", {s1:"veía",s2:"veías",s3:"veía",p1:"veíamos",p2:"veíais",p3:"veían","vos":"veías"})
assert_TenseMood("ver", "FutInd", {s1:"veré",s2:"verás",s3:"verá",p1:"veremos",p2:"veréis",p3:"verán","vos":"verás"})
assert_TenseMood("ver", "FutCond", {s1:"vería",s2:"verías",s3:"vería",p1:"veríamos",p2:"veríais",p3:"verían","vos":"verías"})
assert_TenseMood("ver", "CmdPos", {s1:null,s2:"ve",s3:"vea",p1:"veamos",p2:"ved",p3:"vean","vos":"ve"})
assert_TenseMood("ver", "CmdNeg", {s1:null,s2:"veas",s3:"vea",p1:"veamos",p2:"veáis",p3:"vean","vos":"veas"})



assert_typographicalChange({conjugated_form: "empezé", infinitive: "empezar"}, "empecé")
assert_typographicalChange({conjugated_form: "conoco", infinitive: "conocer"}, "conozco")
assert_typographicalChange({conjugated_form: "sacé", infinitive: "sacar"}, "saqué")
assert_typographicalChange({conjugated_form: "eligo", infinitive: "elegir"}, "elijo")
assert_typographicalChange({conjugated_form: "llegé", infinitive: "llegar"}, "llegué")
