import { assert_TenseMood, assert_typographicalChange } from "./test-support.js"



// -ar
assert_TenseMood("amar", "PresInd", {"1s": "amo", "2s": "amas", "3s": "ama", "1p": "amamos", "2p": "amáis", "3p": "aman"})
assert_TenseMood("amar", "PresSub", {"1s": "ame", "2s": "ames", "3s": "ame", "1p": "amemos", "2p": "améis", "3p": "amen"})
assert_TenseMood("amar", "PastInd", {"1s": "amé", "2s": "amaste", "3s": "amó", "1p": "amamos", "2p": "amasteis", "3p": "amaron"})
assert_TenseMood("amar", "PastImp", {"1s": "amaba", "2s": "amabas", "3s": "amaba", "1p": "amábamos", "2p": "amabais", "3p": "amaban"})
assert_TenseMood("amar", "FutInd", {"1s": "amaré", "2s": "amarás", "3s": "amará", "1p": "amaremos", "2p": "amaréis", "3p": "amarán"})
assert_TenseMood("amar", "FutCond", {"1s": "amaría", "2s": "amarías", "3s": "amaría", "1p": "amaríamos", "2p": "amaríais", "3p": "amarían"})
assert_TenseMood("amar", "CmdPos", {"1s": null, "2s": "ama", "3s": "ame", "1p": "amemos", "2p": "amad", "3p": "amen"})
assert_TenseMood("amar", "CmdNeg", {"1s": null, "2s": "ames", "3s": "ame", "1p": "amemos", "2p": "améis", "3p": "amen"})


// -er
assert_TenseMood("beber", "PresInd", {"1s": "bebo", "2s": "bebes", "3s": "bebe", "1p": "bebemos", "2p": "bebéis", "3p": "beben"})
assert_TenseMood("beber", "PresSub", {"1s": "beba", "2s": "bebas", "3s": "beba", "1p": "bebamos", "2p": "bebáis", "3p": "beban"})
assert_TenseMood("beber", "PastInd", {"1s": "bebí", "2s": "bebiste", "3s": "bebió", "1p": "bebimos", "2p": "bebisteis", "3p": "bebieron"})
assert_TenseMood("beber", "PastImp", {"1s": "bebía", "2s": "bebías", "3s": "bebía",  "1p": "bebíamos", "2p": "bebíais", "3p": "bebían"})
assert_TenseMood("beber", "FutInd", {"1s": "beberé", "2s": "beberás", "3s": "beberá", "1p": "beberemos", "2p": "beberéis", "3p": "beberán"})
assert_TenseMood("beber", "FutCond", {"1s": "bebería", "2s": "beberías", "3s": "bebería", "1p": "beberíamos", "2p": "beberíais", "3p": "beberían"})
assert_TenseMood("beber", "CmdPos", {"1s": null, "2s": "bebe", "3s": "beba", "1p": "bebamos", "2p": "bebed", "3p": "beban"})
assert_TenseMood("beber", "CmdNeg", {"1s": null, "2s": "bebas", "3s": "beba", "1p": "bebamos", "2p": "bebáis", "3p": "beban"})


// -ir
assert_TenseMood("partir", "PresInd", {"1s": "parto", "2s": "partes", "3s": "parte", "1p": "partimos", "2p": "partís", "3p": "parten"})
assert_TenseMood("partir", "PresSub", {"1s": "parta", "2s": "partas", "3s": "parta", "1p": "partamos", "2p": "partáis", "3p": "partan"})
assert_TenseMood("partir", "PastInd", {"1s": "partí", "2s": "partiste", "3s": "partió", "1p": "partimos", "2p": "partisteis", "3p": "partieron"})
assert_TenseMood("partir", "PastImp", {"1s": "partía", "2s": "partías", "3s": "partía",  "1p": "partíamos", "2p": "partíais", "3p": "partían"})
assert_TenseMood("partir", "FutInd", {"1s": "partiré", "2s": "partirás", "3s": "partirá", "1p": "partiremos", "2p": "partiréis", "3p": "partirán"})
assert_TenseMood("partir", "FutCond", {"1s": "partiría", "2s": "partirías", "3s": "partiría", "1p": "partiríamos", "2p": "partiríais", "3p": "partirían"})
assert_TenseMood("partir", "CmdPos", {"1s": null, "2s": "parte", "3s": "parta", "1p": "partamos", "2p": "partid", "3p": "partan"})
assert_TenseMood("partir", "CmdNeg", {"1s": null, "2s": "partas", "3s": "parta", "1p": "partamos", "2p": "partáis", "3p": "partan"})


assert_TenseMood("caber", "PresInd", {"1s":"quepo","2s":"cabes","3s":"cabe","1p":"cabemos","2p":"cabéis","3p":"caben","vos":"cabés"})
assert_TenseMood("caber", "PresSub", {"1s":"quepa","2s":"quepas","3s":"quepa","1p":"quepamos","2p":"quepáis","3p":"quepan","vos":"quepas"})
assert_TenseMood("caber", "PastInd", {"1s":"cupe","2s":"cupiste","3s":"cupo","1p":"cupimos","2p":"cupisteis","3p":"cupieron","vos":"cupiste"})
assert_TenseMood("caber", "PastImp", {"1s":"cabía","2s":"cabías","3s":"cabía","1p":"cabíamos","2p":"cabíais","3p":"cabían","vos":"cabías"})
assert_TenseMood("caber", "FutInd", {"1s":"cabré","2s":"cabrás","3s":"cabrá","1p":"cabremos","2p":"cabréis","3p":"cabrán","vos":"cabrás"})
assert_TenseMood("caber", "FutCond", {"1s":"cabría","2s":"cabrías","3s":"cabría","1p":"cabríamos","2p":"cabríais","3p":"cabrían","vos":"cabrías"})
assert_TenseMood("caber", "CmdPos", {"1s":null,"2s":"cabe","3s":"quepa","1p":"quepamos","2p":"cabed","3p":"quepan","vos":"cabé"})
assert_TenseMood("caber", "CmdNeg", {"1s":null,"2s":"quepas","3s":"quepa","1p":"quepamos","2p":"quepáis","3p":"quepan","vos":"quepas"})

assert_TenseMood("caer", "PresInd", {"1s":"caigo","2s":"caes","3s":"cae","1p":"caemos","2p":"caéis","3p":"caen","vos":"caés"})
assert_TenseMood("caer", "PresSub", {"1s":"caiga","2s":"caigas","3s":"caiga","1p":"caigamos","2p":"caigáis","3p":"caigan","vos":"caigas"})
assert_TenseMood("caer", "PastInd", {"1s":"caí","2s":"caíste","3s":"cayó","1p":"caímos","2p":"caísteis","3p":"cayeron","vos":"caíste"})
assert_TenseMood("caer", "PastImp", {"1s":"caía","2s":"caías","3s":"caía","1p":"caíamos","2p":"caíais","3p":"caían","vos":"caías"})
assert_TenseMood("caer", "FutInd", {"1s":"caeré","2s":"caerás","3s":"caerá","1p":"caeremos","2p":"caeréis","3p":"caerán","vos":"caerás"})
assert_TenseMood("caer", "FutCond", {"1s":"caería","2s":"caerías","3s":"caería","1p":"caeríamos","2p":"caeríais","3p":"caerían","vos":"caerías"})
assert_TenseMood("caer", "CmdPos", {"1s":null,"2s":"cae","3s":"caiga","1p":"caigamos","2p":"caed","3p":"caigan","vos":"caé"})
assert_TenseMood("caer", "CmdNeg", {"1s":null,"2s":"caigas","3s":"caiga","1p":"caigamos","2p":"caigáis","3p":"caigan","vos":["caigas","*caigás"]})

assert_TenseMood("conducir", "PresInd", {"1s":"conduzco","2s":"conduces","3s":"conduce","1p":"conducimos","2p":"conducís","3p":"conducen","vos":"conducís"})
assert_TenseMood("conducir", "PresSub", {"1s":"conduzca","2s":"conduzcas","3s":"conduzca","1p":"conduzcamos","2p":"conduzcáis","3p":"conduzcan","vos":"conduzcas"})
assert_TenseMood("conducir", "PastInd", {"1s":"conduje","2s":"condujiste","3s":"condujo","1p":"condujimos","2p":"condujisteis","3p":"condujeron","vos":"condujiste"})
assert_TenseMood("conducir", "PastImp", {"1s":"conducía","2s":"conducías","3s":"conducía","1p":"conducíamos","2p":"conducíais","3p":"conducían","vos":"conducías"})
assert_TenseMood("conducir", "FutInd", {"1s":"conduciré","2s":"conducirás","3s":"conducirá","1p":"conduciremos","2p":"conduciréis","3p":"conducirán","vos":"conducirás"})
assert_TenseMood("conducir", "FutCond", {"1s":"conduciría","2s":"conducirías","3s":"conduciría","1p":"conduciríamos","2p":"conduciríais","3p":"conducirían","vos":"conducirías"})
assert_TenseMood("conducir", "CmdPos", {"1s":null,"2s":"conduce","3s":"conduzca","1p":"conduzcamos","2p":"conducid","3p":"conduzcan","vos":"conducí"})
assert_TenseMood("conducir", "CmdNeg", {"1s":null,"2s":"conduzcas","3s":"conduzca","1p":"conduzcamos","2p":"conduzcáis","3p":"conduzcan","vos":"conduzcas"})

assert_TenseMood("dar", "PresInd", {"1s": "doy", "2s": "das", "3s": "da", "1p": "damos", "2p": "dais", "3p": "dan"})
assert_TenseMood("dar", "PresSub", {"1s": "dé", "2s": "des", "3s": "dé", "1p": "demos", "2p": "deis", "3p": "den"})
assert_TenseMood("dar", "PastInd", {"1s": "di", "2s": "diste", "3s": "dio",  "1p": "dimos", "2p": "disteis", "3p": "dieron"})
assert_TenseMood("dar", "PastImp", {"1s": "daba", "2s": "dabas", "3s": "daba",  "1p": "dábamos", "2p": "dabais", "3p": "daban"})
assert_TenseMood("dar", "FutInd", {"1s": "daré", "2s": "darás", "3s": "dará", "1p": "daremos", "2p": "daréis", "3p": "darán"})
assert_TenseMood("dar", "FutCond", {"1s": "daría", "2s": "darías", "3s": "daría", "1p": "daríamos", "2p": "daríais", "3p": "darían"})
assert_TenseMood("dar", "CmdPos", {"1s": null, "2s": "da", "3s": "dé", "1p": "demos", "2p": "dad", "3p": "den"})
assert_TenseMood("dar", "CmdNeg", {"1s": null, "2s": "des", "3s": "dé", "1p": "demos", "2p": "deis", "3p": "den"})

assert_TenseMood("decir", "PresInd", {"1s": "digo", "2s": "dices", "3s": "dice",     "1p": "decimos", "2p": "decís", "3p": "dicen"})
assert_TenseMood("decir", "PresSub", {"1s": "diga", "2s": "digas", "3s": "diga",     "1p": "digamos", "2p": "digáis", "3p": "digan"})
assert_TenseMood("decir", "PastInd", {"1s": "dije", "2s": "dijiste", "3s": "dijo",   "1p": "dijimos", "2p": "dijisteis", "3p": "dijeron"})
assert_TenseMood("decir", "PastImp", {"1s": "decía", "2s": "decías", "3s": "decía",  "1p": "decíamos", "2p": "decíais", "3p": "decían"})
assert_TenseMood("decir", "FutInd",  {"1s": "diré", "2s": "dirás", "3s": "dirá",     "1p": "diremos",  "2p": "diréis", "3p": "dirán" })
assert_TenseMood("decir", "FutCond", {"1s": "diría", "2s": "dirías", "3s": "diría",  "1p": "diríamos", "2p": "diríais", "3p": "dirían" })
assert_TenseMood("decir", "CmdPos",  {"1s": null,   "2s": "di", "3s": "diga",        "1p": "digamos",  "2p": "decid", "3p": "digan" })
assert_TenseMood("decir", "CmdNeg",  {"1s": null,   "2s": "digas", "3s": "diga",     "1p": "digamos",  "2p": "digáis", "3p": "digan" })

assert_TenseMood("detener", "PresInd", {"1s":"detengo","2s":"detienes","3s":"detiene","1p":"detenemos","2p":"detenéis","3p":"detienen","vos":"detenés"})
assert_TenseMood("detener", "PresSub", {"1s":"detenga","2s":"detengas","3s":"detenga","1p":"detengamos","2p":"detengáis","3p":"detengan","vos":"detengas"})
assert_TenseMood("detener", "PastInd", {"1s":"detuve","2s":"detuviste","3s":"detuvo","1p":"detuvimos","2p":"detuvisteis","3p":"detuvieron","vos":"detuviste"})
assert_TenseMood("detener", "PastImp", {"1s":"detenía","2s":"detenías","3s":"detenía","1p":"deteníamos","2p":"deteníais","3p":"detenían","vos":"detenías"})
assert_TenseMood("detener", "FutInd", {"1s":"detendré","2s":"detendrás","3s":"detendrá","1p":"detendremos","2p":"detendréis","3p":"detendrán","vos":"detendrás"})
assert_TenseMood("detener", "FutCond", {"1s":"detendría","2s":"detendrías","3s":"detendría","1p":"detendríamos","2p":"detendríais","3p":"detendrían","vos":"detendrías"})
assert_TenseMood("detener", "CmdPos", {"1s":null,"2s":"detén","3s":"detenga","1p":"detengamos","2p":"detened","3p":"detengan","vos":"detené"})
assert_TenseMood("detener", "CmdNeg", {"1s":null,"2s":"detengas","3s":"detenga","1p":"detengamos","2p":"detengáis","3p":"detengan","vos":"detengas"})

assert_TenseMood("erguir", "PresInd", {"1s":["irgo","yergo"],"2s":["irgues","yergues"],"3s":["irgue","yergue"],"1p":"erguimos","2p":"erguís","3p":["irguen","yerguen"],"vos":"erguís"})
assert_TenseMood("erguir", "PresSub", {"1s":["irga","yerga"],"2s":["irgas","yergas"],"3s":["irga","yerga"],"1p":["irgamos","yergamos"],"2p":["irgáis","yergáis"],"3p":["irgan","yergan"],"vos":"yergas"})
assert_TenseMood("erguir", "PastInd", {"1s":"erguí","2s":"erguiste","3s":"irguió","1p":"erguimos","2p":"erguisteis","3p":"irguieron","vos":"erguiste"})
assert_TenseMood("erguir", "PastImp", {"1s":"erguía","2s":"erguías","3s":"erguía","1p":"erguíamos","2p":"erguíais","3p":"erguían","vos":"erguías"})
assert_TenseMood("erguir", "FutInd", {"1s":"erguiré","2s":"erguirás","3s":"erguirá","1p":"erguiremos","2p":"erguiréis","3p":"erguirán","vos":"erguirás"})
assert_TenseMood("erguir", "FutCond", {"1s":"erguiría","2s":"erguirías","3s":"erguiría","1p":"erguiríamos","2p":"erguiríais","3p":"erguirían","vos":"erguirías"})
assert_TenseMood("erguir", "CmdPos", {"1s":null,"2s":["irgue","yergue"],"3s":["irga","yerga"],"1p":["irgamos","yergamos"],"2p":"erguid","3p":["irgan","yergan"],"vos":"erguí"})
assert_TenseMood("erguir", "CmdNeg", {"1s":null,"2s":["irgas","yergas"],"3s":["irga","yerga"],"1p":["irgamos","yergamos"],"2p":["irgáis","yergáis"],"3p":["irgan","yergan"],"vos":"yergas"})

assert_TenseMood("estar", "PresInd", {"1s": "estoy", "2s": "estás", "3s": "está",         "1p": "estamos", "2p": "estáis", "3p": "están" })
assert_TenseMood("estar", "PresSub", { "1s": "esté", "2s": "estés", "3s": "esté",         "1p": "estemos", "2p": "estéis", "3p": "estén" })
assert_TenseMood("estar", "PastInd", {"1s": "estuve", "2s": "estuviste", "3s": "estuvo",  "1p": "estuvimos", "2p": "estuvisteis", "3p": "estuvieron"})
assert_TenseMood("estar", "PastImp", {"1s": "estaba", "2s": "estabas", "3s": "estaba",    "1p": "estábamos", "2p": "estabais", "3p": "estaban"})
assert_TenseMood("estar", "FutInd", {"1s": "estaré", "2s": "estarás", "3s": "estará",     "1p": "estaremos", "2p": "estaréis", "3p": "estarán"})
assert_TenseMood("estar", "FutCond", {"1s": "estaría", "2s": "estarías", "3s": "estaría", "1p": "estaríamos", "2p": "estaríais", "3p": "estarían"})
assert_TenseMood("estar", "CmdPos",  {"1s": null,   "2s": "está", "3s": "esté",           "1p": "estemos",  "2p": "estad", "3p": "estén" })
assert_TenseMood("estar", "CmdNeg",  {"1s": null,   "2s": "estés", "3s": "esté",          "1p": "estemos", "2p": "estéis", "3p": "estén" })

// based on "vaciar", but has changes to the accents
assert_TenseMood("guiar", "PresInd", {"1s":"guío","2s":"guías","3s":"guía","1p":"guiamos","2p":"guiais","3p":"guían","vos":"guias"})
assert_TenseMood("guiar", "PresSub", {"1s":"guíe","2s":"guíes","3s":"guíe","1p":"guiemos","2p":"guieis","3p":"guíen","vos":["guíes",""]})
assert_TenseMood("guiar", "PastInd", {"1s":"guie","2s":"guiaste","3s":"guio","1p":"guiamos","2p":"guiasteis","3p":"guiaron","vos":"guiaste"})
assert_TenseMood("guiar", "PastImp", {"1s":"guiaba","2s":"guiabas","3s":"guiaba","1p":"guiábamos","2p":"guiabais","3p":"guiaban","vos":"guiabas"})
assert_TenseMood("guiar", "FutInd", {"1s":"guiaré","2s":"guiarás","3s":"guiará","1p":"guiaremos","2p":"guiaréis","3p":"guiarán","vos":"guiarás"})
assert_TenseMood("guiar", "FutCond", {"1s":"guiaría","2s":"guiarías","3s":"guiaría","1p":"guiaríamos","2p":"guiaríais","3p":"guiarían","vos":"guiarías"})
assert_TenseMood("guiar", "CmdPos", {"1s":null,"2s":"guía","3s":"guíe","1p":"guiemos","2p":"guiad","3p":"guíen","vos":"guia"})
assert_TenseMood("guiar", "CmdNeg", {"1s":null,"2s":"guíes","3s":"guíe","1p":"guiemos","2p":"guieis","3p":"guíen","vos":["guíes","*guiés"]})

// NOTE: supports alternate form for 3s => impersonal: hay
assert_TenseMood("haber", "PresInd", {"1s": "he", "2s": "has", "3s": ["hay", "ha"],     "1p": "hemos", "2p": "habéis", "3p": "han"})
assert_TenseMood("haber", "PresSub", {"1s": "haya", "2s": "hayas", "3s": "haya",        "1p": "hayamos", "2p": "hayáis", "3p": "hayan" })
assert_TenseMood("haber", "PastInd", {"1s": "hube", "2s": "hubiste", "3s": "hubo",      "1p": "hubimos", "2p": "hubisteis", "3p": "hubieron"})
assert_TenseMood("haber", "PastImp", {"1s": "había", "2s": "habías", "3s": "había",     "1p": "habíamos", "2p": "habíais", "3p": "habían"})
assert_TenseMood("haber", "FutInd", {"1s": "habré", "2s": "habrás", "3s": "habrá",      "1p": "habremos", "2p": "habréis", "3p": "habrán"})
assert_TenseMood("haber", "FutCond", {"1s": "habría", "2s": "habrías", "3s": "habría",  "1p": "habríamos", "2p": "habríais", "3p": "habrían"})
assert_TenseMood("haber", "CmdPos",  {"1s": null,   "2s": ["habe", "he"], "3s": "haya", "1p": "hayamos",  "2p": "habed", "3p": "hayan" })
assert_TenseMood("haber", "CmdNeg",  {"1s": null,   "2s": "hayas", "3s": "haya",        "1p": "hayamos",  "2p": "hayáis", "3p": "hayan" })

assert_TenseMood("hacer", "PresInd", {"1s": "hago", "2s": "haces", "3s": "hace",        "1p": "hacemos", "2p": "hacéis", "3p": "hacen"})
assert_TenseMood("hacer", "PresSub", {"1s": "haga", "2s": "hagas", "3s": "haga",        "1p": "hagamos", "2p": "hagáis", "3p": "hagan" })
assert_TenseMood("hacer", "PastInd", {"1s": "hice", "2s": "hiciste", "3s": "hizo",      "1p": "hicimos", "2p": "hicisteis", "3p": "hicieron"})
assert_TenseMood("hacer", "PastImp", {"1s": "hacía", "2s": "hacías", "3s": "hacía",     "1p": "hacíamos", "2p": "hacíais", "3p": "hacían"})
assert_TenseMood("hacer", "FutInd",  {"1s": "haré", "2s": "harás", "3s": "hará",         "1p": "haremos", "2p": "haréis", "3p": "harán"})
assert_TenseMood("hacer", "FutCond", {"1s": "haría", "2s": "harías", "3s": "haría",     "1p": "haríamos", "2p": "haríais", "3p": "harían"})
assert_TenseMood("hacer", "CmdPos",  {"1s": null,   "2s": "haz", "3s": "haga",          "1p": "hagamos",  "2p": "haced", "3p": "hagan" })
assert_TenseMood("hacer", "CmdNeg",  {"1s": null,   "2s": "hagas", "3s": "haga",        "1p": "hagamos",  "2p": "hagáis", "3p": "hagan" })

assert_TenseMood("huir", "PresInd", {"1s":"huyo","2s":"huyes","3s":"huye","1p":"huimos","2p":"huis","3p":"huyen","vos":"huis"})
assert_TenseMood("huir", "PresSub", {"1s":"huya","2s":"huyas","3s":"huya","1p":"huyamos","2p":"huyáis","3p":"huyan","vos":"huyas"})
assert_TenseMood("huir", "PastInd", {"1s":"hui","2s":"huiste","3s":"huyó","1p":"huimos","2p":"huisteis","3p":"huyeron","vos":"huiste"})
assert_TenseMood("huir", "PastImp", {"1s":"huía","2s":"huías","3s":"huía","1p":"huíamos","2p":"huíais","3p":"huían","vos":"huías"})
assert_TenseMood("huir", "FutInd", {"1s":"huiré","2s":"huirás","3s":"huirá","1p":"huiremos","2p":"huiréis","3p":"huirán","vos":"huirás"})
assert_TenseMood("huir", "FutCond", {"1s":"huiría","2s":"huirías","3s":"huiría","1p":"huiríamos","2p":"huiríais","3p":"huirían","vos":"huirías"})
assert_TenseMood("huir", "CmdPos", {"1s":null,"2s":"huye","3s":"huya","1p":"huyamos","2p":"huid","3p":"huyan","vos":"hui"})
assert_TenseMood("huir", "CmdNeg", {"1s":null,"2s":"huyas","3s":"huya","1p":"huyamos","2p":"huyáis","3p":"huyan","vos":"huyas"})

assert_TenseMood("ir", "PresInd", {"1s": "voy", "2s": "vas", "3s": "va",                "1p": "vamos", "2p": "vais", "3p": "van"})
assert_TenseMood("ir", "PresSub", {"1s": "vaya", "2s": "vayas", "3s": "vaya",           "1p": "vayamos", "2p": "vayáis", "3p": "vayan" })
assert_TenseMood("ir", "PastInd", {"1s": "fui", "2s": "fuiste", "3s": "fue",            "1p": "fuimos", "2p": "fuisteis", "3p": "fueron"})
assert_TenseMood("ir", "PastImp", {"1s": "iba", "2s": "ibas", "3s": "iba",              "1p": "íbamos", "2p": "ibais", "3p": "iban"})
assert_TenseMood("ir", "FutInd",  {"1s": "iré", "2s": "irás", "3s": "irá",              "1p": "iremos", "2p": "iréis", "3p": "irán"})
assert_TenseMood("ir", "FutCond", {"1s": "iría", "2s": "irías", "3s": "iría",           "1p": "iríamos", "2p": "iríais", "3p": "irían"})
assert_TenseMood("ir", "CmdPos",  {"1s": null, "2s": "ve", "3s": "vaya",                "1p": ["vayamos", "vamos"], "2p": "id", "3p": "vayan"})
assert_TenseMood("ir", "CmdNeg",  {"1s": null, "2s": "vayas", "3s": "vaya",             "1p": "vayamos", "2p": "vayáis", "3p": "vayan"})

assert_TenseMood("jugar", "PresInd", {"1s":"juego","2s":"juegas","3s":"juega","1p":"jugamos","2p":"jugáis","3p":"juegan","vos":"jugás"})
assert_TenseMood("jugar", "PresSub", {"1s":"juegue","2s":"juegues","3s":"juegue","1p":"juguemos","2p":"juguéis","3p":"jueguen","vos":"juegues"})
assert_TenseMood("jugar", "PastInd", {"1s":"jugué","2s":"jugaste","3s":"jugó","1p":"jugamos","2p":"jugasteis","3p":"jugaron","vos":"jugaste"})
assert_TenseMood("jugar", "PastImp", {"1s":"jugaba","2s":"jugabas","3s":"jugaba","1p":"jugábamos","2p":"jugabais","3p":"jugaban","vos":"jugabas"})
assert_TenseMood("jugar", "FutInd", {"1s":"jugaré","2s":"jugarás","3s":"jugará","1p":"jugaremos","2p":"jugaréis","3p":"jugarán","vos":"jugarás"})
assert_TenseMood("jugar", "FutCond", {"1s":"jugaría","2s":"jugarías","3s":"jugaría","1p":"jugaríamos","2p":"jugaríais","3p":"jugarían","vos":"jugarías"})
assert_TenseMood("jugar", "CmdPos", {"1s":null,"2s":"juega","3s":"juegue","1p":"juguemos","2p":"jugad","3p":"jueguen","vos":"jugá"})
assert_TenseMood("jugar", "CmdNeg", {"1s":null,"2s":"juegues","3s":"juegue","1p":"juguemos","2p":"juguéis","3p":"jueguen","vos":["juegues","*jugués"]})

assert_TenseMood("leer", "PresInd", {"1s": "leo", "2s": "lees", "3s": "lee",            "1p": "leemos", "2p": "leéis", "3p": "leen"})
assert_TenseMood("leer", "PresSub", {"1s": "lea", "2s": "leas", "3s": "lea",            "1p": "leamos", "2p": "leáis", "3p": "lean"})
assert_TenseMood("leer", "PastInd", {"1s": "leí", "2s": "leíste", "3s": "leyó",         "1p": "leímos", "2p": "leísteis", "3p": "leyeron"})
assert_TenseMood("leer", "PastImp", {"1s": "leía", "2s": "leías", "3s": "leía",         "1p": "leíamos", "2p": "leíais", "3p": "leían"})
assert_TenseMood("leer", "FutInd", {"1s": "leeré", "2s": "leerás", "3s": "leerá",       "1p": "leeremos", "2p": "leeréis", "3p": "leerán"})
assert_TenseMood("leer", "FutCond", {"1s": "leería", "2s": "leerías", "3s": "leería",   "1p": "leeríamos", "2p": "leeríais", "3p": "leerían"})
assert_TenseMood("leer", "CmdPos", {"1s": null, "2s": "lee", "3s": "lea",               "1p": "leamos", "2p": "leed", "3p": "lean"})
assert_TenseMood("leer", "CmdNeg", {"1s": null, "2s": "leas", "3s": "lea",              "1p": "leamos", "2p": "leáis", "3p": "lean"})

assert_TenseMood("llegar", "PresInd", {"1s": "llego", "2s": "llegas", "3s": "llega", "1p": "llegamos", "2p": "llegáis", "3p": "llegan"})
assert_TenseMood("llegar", "PastInd", {"1s": "llegué", "2s": "llegaste", "3s": "llegó",  "1p": "llegamos", "2p": "llegasteis", "3p": "llegaron"})

assert_TenseMood("oír", "PresInd", {"1s":"oigo","2s":"oyes","3s":"oye","1p":"oímos","2p":"oís","3p":"oyen","vos":"oís"})
assert_TenseMood("oír", "PresSub", {"1s":"oiga","2s":"oigas","3s":"oiga","1p":"oigamos","2p":"oigáis","3p":"oigan","vos":"oigas"})
assert_TenseMood("oír", "PastInd", {"1s":"oí","2s":"oíste","3s":"oyó","1p":"oímos","2p":"oísteis","3p":"oyeron","vos":"oíste"})
assert_TenseMood("oír", "PastImp", {"1s":"oía","2s":"oías","3s":"oía","1p":"oíamos","2p":"oíais","3p":"oían","vos":"oías"})
assert_TenseMood("oír", "FutInd", {"1s":"oiré","2s":"oirás","3s":"oirá","1p":"oiremos","2p":"oiréis","3p":"oirán","vos":"oirás"})
assert_TenseMood("oír", "FutCond", {"1s":"oiría","2s":"oirías","3s":"oiría","1p":"oiríamos","2p":"oiríais","3p":"oirían","vos":"oirías"})
assert_TenseMood("oír", "CmdPos", {"1s":null,"2s":"oye","3s":"oiga","1p":"oigamos","2p":"oíd","3p":"oigan","vos":"oí"})
assert_TenseMood("oír", "CmdNeg", {"1s":null,"2s":"oigas","3s":"oiga","1p":"oigamos","2p":"oigáis","3p":"oigan","vos":["oigas","*oigás"]})

assert_TenseMood("poder", "PresInd", {"1s":"puedo","2s":"puedes","3s":"puede","1p":"podemos","2p":"podéis","3p":"pueden","vos":"podés"})
assert_TenseMood("poder", "PresSub", {"1s":"pueda","2s":"puedas","3s":"pueda","1p":"podamos","2p":"podáis","3p":"puedan","vos":"puedas"})
assert_TenseMood("poder", "PastInd", {"1s":"pude","2s":"pudiste","3s":"pudo","1p":"pudimos","2p":"pudisteis","3p":"pudieron","vos":"pudiste"})
assert_TenseMood("poder", "PastImp", {"1s":"podía","2s":"podías","3s":"podía","1p":"podíamos","2p":"podíais","3p":"podían","vos":"podías"})
assert_TenseMood("poder", "FutInd", {"1s":"podré","2s":"podrás","3s":"podrá","1p":"podremos","2p":"podréis","3p":"podrán","vos":"podrás"})
assert_TenseMood("poder", "FutCond", {"1s":"podría","2s":"podrías","3s":"podría","1p":"podríamos","2p":"podríais","3p":"podrían","vos":"podrías"})
assert_TenseMood("poder", "CmdPos", {"1s":null,"2s":"puede","3s":"pueda","1p":"podamos","2p":"poded","3p":"puedan","vos":"podé"})
assert_TenseMood("poder", "CmdNeg", {"1s":null,"2s":"puedas","3s":"pueda","1p":"podamos","2p":"podáis","3p":"puedan","vos":["puedas","*podás"]})

assert_TenseMood("poner", "PresInd", {"1s":"pongo","2s":"pones","3s":"pone","1p":"ponemos","2p":"ponéis","3p":"ponen","vos":"ponés"})
assert_TenseMood("poner", "PresSub", {"1s":"ponga","2s":"pongas","3s":"ponga","1p":"pongamos","2p":"pongáis","3p":"pongan","vos":"pongas"})
assert_TenseMood("poner", "PastInd", {"1s":"puse","2s":"pusiste","3s":"puso","1p":"pusimos","2p":"pusisteis","3p":"pusieron","vos":"pusiste"})
assert_TenseMood("poner", "PastImp", {"1s":"ponía","2s":"ponías","3s":"ponía","1p":"poníamos","2p":"poníais","3p":"ponían","vos":"ponías"})
assert_TenseMood("poner", "FutInd", {"1s":"pondré","2s":"pondrás","3s":"pondrá","1p":"pondremos","2p":"pondréis","3p":"pondrán","vos":"pondrás"})
assert_TenseMood("poner", "FutCond", {"1s":"pondría","2s":"pondrías","3s":"pondría","1p":"pondríamos","2p":"pondríais","3p":"pondrían","vos":"pondrías"})
assert_TenseMood("poner", "CmdPos", {"1s":null,"2s":"pon","3s":"ponga","1p":"pongamos","2p":"poned","3p":"pongan","vos":"poné"})
assert_TenseMood("poner", "CmdNeg", {"1s":null,"2s":"pongas","3s":"ponga","1p":"pongamos","2p":"pongáis","3p":"pongan","vos":["pongas","*pongás"]})

assert_TenseMood("querer", "PresInd", {"1s":"quiero","2s":"quieres","3s":"quiere","1p":"queremos","2p":"queréis","3p":"quieren","vos":"querés"})
assert_TenseMood("querer", "PresSub", {"1s":"quiera","2s":"quieras","3s":"quiera","1p":"queramos","2p":"queráis","3p":"quieran","vos":"quieras"})
assert_TenseMood("querer", "PastInd", {"1s":"quise","2s":"quisiste","3s":"quiso","1p":"quisimos","2p":"quisisteis","3p":"quisieron","vos":"quisiste"})
assert_TenseMood("querer", "PastImp", {"1s":"quería","2s":"querías","3s":"quería","1p":"queríamos","2p":"queríais","3p":"querían","vos":"querías"})
assert_TenseMood("querer", "FutInd",  {"1s":"querré","2s":"querrás","3s":"querrá","1p":"querremos","2p":"querréis","3p":"querrán","vos":"querrás"})
assert_TenseMood("querer", "FutCond", {"1s":"querría","2s":"querrías","3s":"querría","1p":"querríamos","2p":"querríais","3p":"querrían","vos":"querrías"})
assert_TenseMood("querer", "CmdPos",  {"1s":null,"2s":"quiere","3s":"quiera","1p":"queramos","2p":"quered","3p":"quieran","vos":"queré"})
assert_TenseMood("querer", "CmdNeg",  {"1s":null,"2s":"quieras","3s":"quiera","1p":"queramos","2p":"queráis","3p":"quieran","vos":"quieras"})

assert_TenseMood("saber", "PresInd", {"1s":"sé","2s":"sabes","3s":"sabe","1p":"sabemos","2p":"sabéis","3p":"saben","vos":"sabés"})
assert_TenseMood("saber", "PresSub", {"1s":"sepa","2s":"sepas","3s":"sepa","1p":"sepamos","2p":"sepáis","3p":"sepan","vos":"sepas"})
assert_TenseMood("saber", "PastInd", {"1s":"supe","2s":"supiste","3s":"supo","1p":"supimos","2p":"supisteis","3p":"supieron","vos":"supiste"})
assert_TenseMood("saber", "PastImp", {"1s":"sabía","2s":"sabías","3s":"sabía","1p":"sabíamos","2p":"sabíais","3p":"sabían","vos":"sabías"})
assert_TenseMood("saber", "FutInd", {"1s":"sabré","2s":"sabrás","3s":"sabrá","1p":"sabremos","2p":"sabréis","3p":"sabrán","vos":"sabrás"})
assert_TenseMood("saber", "FutCond", {"1s":"sabría","2s":"sabrías","3s":"sabría","1p":"sabríamos","2p":"sabríais","3p":"sabrían","vos":"sabrías"})
assert_TenseMood("saber", "CmdPos", {"1s":null,"2s":"sabe","3s":"sepa","1p":"sepamos","2p":"sabed","3p":"sepan","vos":"sabé"})
assert_TenseMood("saber", "CmdNeg", {"1s":null,"2s":"sepas","3s":"sepa","1p":"sepamos","2p":"sepáis","3p":"sepan","vos":["sepas","*sepás"]})

assert_TenseMood("salir", "PresInd", {"1s":"salgo","2s":"sales","3s":"sale","1p":"salimos","2p":"salís","3p":"salen","vos":"salís"})
assert_TenseMood("salir", "PresSub", {"1s":"salga","2s":"salgas","3s":"salga","1p":"salgamos","2p":"salgáis","3p":"salgan","vos":"salgas"})
assert_TenseMood("salir", "PastInd", {"1s":"salí","2s":"saliste","3s":"salió","1p":"salimos","2p":"salisteis","3p":"salieron","vos":"saliste"})
assert_TenseMood("salir", "PastImp", {"1s":"salía","2s":"salías","3s":"salía","1p":"salíamos","2p":"salíais","3p":"salían","vos":"salías"})
assert_TenseMood("salir", "FutInd", {"1s":"saldré","2s":"saldrás","3s":"saldrá","1p":"saldremos","2p":"saldréis","3p":"saldrán","vos":"saldrás"})
assert_TenseMood("salir", "FutCond", {"1s":"saldría","2s":"saldrías","3s":"saldría","1p":"saldríamos","2p":"saldríais","3p":"saldrían","vos":"saldrías"})
assert_TenseMood("salir", "CmdPos", {"1s":null,"2s":"sal","3s":"salga","1p":"salgamos","2p":"salid","3p":"salgan","vos":"salí"})
assert_TenseMood("salir", "CmdNeg", {"1s":null,"2s":"salgas","3s":"salga","1p":"salgamos","2p":"salgáis","3p":"salgan","vos":["salgas","*salgás"]})

assert_TenseMood("seguir", "PresInd", {"1s":"sigo","2s":"sigues","3s":"sigue","1p":"seguimos","2p":"seguís","3p":"siguen","vos":"seguís"})
assert_TenseMood("seguir", "PresSub", {"1s":"siga","2s":"sigas","3s":"siga","1p":"sigamos","2p":"sigáis","3p":"sigan","vos":"sigas"})
assert_TenseMood("seguir", "PastInd", {"1s":"seguí","2s":"seguiste","3s":"siguió","1p":"seguimos","2p":"seguisteis","3p":"siguieron","vos":"seguiste"})
assert_TenseMood("seguir", "PastImp", {"1s":"seguía","2s":"seguías","3s":"seguía","1p":"seguíamos","2p":"seguíais","3p":"seguían","vos":"seguías"})
assert_TenseMood("seguir", "FutInd", {"1s":"seguiré","2s":"seguirás","3s":"seguirá","1p":"seguiremos","2p":"seguiréis","3p":"seguirán","vos":"seguirás"})
assert_TenseMood("seguir", "FutCond", {"1s":"seguiría","2s":"seguirías","3s":"seguiría","1p":"seguiríamos","2p":"seguiríais","3p":"seguirían","vos":"seguirías"})
assert_TenseMood("seguir", "CmdPos", {"1s":null,"2s":"sigue","3s":"siga","1p":"sigamos","2p":"seguid","3p":"sigan","vos":"seguí"})
assert_TenseMood("seguir", "CmdNeg", {"1s":null,"2s":"sigas","3s":"siga","1p":"sigamos","2p":"sigáis","3p":"sigan","vos":["sigas","*sigás"]})

assert_TenseMood("ser", "PresInd", {"1s":"soy","2s":"eres","3s":"es","1p":"somos","2p":"sois","3p":"son","vos":"sos"})
assert_TenseMood("ser", "PresSub", {"1s":"sea","2s":"seas","3s":"sea","1p":"seamos","2p":"seáis","3p":"sean","vos":"seas"})
assert_TenseMood("ser", "PastInd", {"1s":"fui","2s":"fuiste","3s":"fue","1p":"fuimos","2p":"fuisteis","3p":"fueron","vos":"fuiste"})
assert_TenseMood("ser", "PastImp", {"1s":"era","2s":"eras","3s":"era","1p":"éramos","2p":"erais","3p":"eran","vos":"eras"})
assert_TenseMood("ser", "FutInd",  {"1s":"seré","2s":"serás","3s":"será","1p":"seremos","2p":"seréis","3p":"serán","vos":"serás"})
assert_TenseMood("ser", "FutCond", {"1s":"sería","2s":"serías","3s":"sería","1p":"seríamos","2p":"seríais","3p":"serían","vos":"serías"})
assert_TenseMood("ser", "CmdPos",  {"1s":null,"2s":"sé","3s":"sea","1p":"seamos","2p":"sed","3p":"sean","vos":"sé"})
assert_TenseMood("ser", "CmdNeg",  {"1s":null,"2s":"seas","3s":"sea","1p":"seamos","2p":"seáis","3p":"sean","vos":["seas","*seás"]})

assert_TenseMood("tener", "PresInd", {"1s":"tengo","2s":"tienes","3s":"tiene","1p":"tenemos","2p":"tenéis","3p":"tienen","vos":"tenés"})
assert_TenseMood("tener", "PresSub", {"1s":"tenga","2s":"tengas","3s":"tenga","1p":"tengamos","2p":"tengáis","3p":"tengan","vos":"tengas"})
assert_TenseMood("tener", "PastInd", {"1s":"tuve","2s":"tuviste","3s":"tuvo","1p":"tuvimos","2p":"tuvisteis","3p":"tuvieron","vos":"tuviste"})
assert_TenseMood("tener", "PastImp", {"1s":"tenía","2s":"tenías","3s":"tenía","1p":"teníamos","2p":"teníais","3p":"tenían","vos":"tenías"})
assert_TenseMood("tener", "FutInd",  {"1s":"tendré","2s":"tendrás","3s":"tendrá","1p":"tendremos","2p":"tendréis","3p":"tendrán","vos":"tendrás"})
assert_TenseMood("tener", "FutCond", {"1s":"tendría","2s":"tendrías","3s":"tendría","1p":"tendríamos","2p":"tendríais","3p":"tendrían","vos":"tendrías"})
assert_TenseMood("tener", "CmdPos",  {"1s":null,"2s":"ten","3s":"tenga","1p":"tengamos","2p":"tened","3p":"tengan","vos":"tené"})
assert_TenseMood("tener", "CmdNeg",  {"1s":null,"2s":"tengas","3s":"tenga","1p":"tengamos","2p":"tengáis","3p":"tengan","vos":"tengas"})

assert_TenseMood("traer", "PresInd", {"1s":"traigo","2s":"traes","3s":"trae","1p":"traemos","2p":"traéis","3p":"traen","vos":"traés"})
assert_TenseMood("traer", "PresSub", {"1s":"traiga","2s":"traigas","3s":"traiga","1p":"traigamos","2p":"traigáis","3p":"traigan","vos":"traigas"})
assert_TenseMood("traer", "PastInd", {"1s":"traje","2s":"trajiste","3s":"trajo","1p":"trajimos","2p":"trajisteis","3p":"trajeron","vos":"trajiste"})
assert_TenseMood("traer", "PastImp", {"1s":"traía","2s":"traías","3s":"traía","1p":"traíamos","2p":"traíais","3p":"traían","vos":"traías"})
assert_TenseMood("traer", "FutInd", {"1s":"traeré","2s":"traerás","3s":"traerá","1p":"traeremos","2p":"traeréis","3p":"traerán","vos":"traerás"})
assert_TenseMood("traer", "FutCond", {"1s":"traería","2s":"traerías","3s":"traería","1p":"traeríamos","2p":"traeríais","3p":"traerían","vos":"traerías"})
assert_TenseMood("traer", "CmdPos", {"1s":null,"2s":"trae","3s":"traiga","1p":"traigamos","2p":"traed","3p":"traigan","vos":"traé"})
assert_TenseMood("traer", "CmdNeg", {"1s":null,"2s":"traigas","3s":"traiga","1p":"traigamos","2p":"traigáis","3p":"traigan","vos":["traigas","*traigás"]})

assert_TenseMood("vaciar", "PresInd", {"1s":"vacío","2s":"vacías","3s":"vacía","1p":"vaciamos","2p":"vaciáis","3p":"vacían","vos":"vaciás"})
assert_TenseMood("vaciar", "PresSub", {"1s":"vacíe","2s":"vacíes","3s":"vacíe","1p":"vaciemos","2p":"vaciéis","3p":"vacíen","vos":["vacíes","*vaciés"]})
assert_TenseMood("vaciar", "PastInd", {"1s":"vacié","2s":"vaciaste","3s":"vació","1p":"vaciamos","2p":"vaciasteis","3p":"vaciaron","vos":"vaciaste"})
assert_TenseMood("vaciar", "PastImp", {"1s":"vaciaba","2s":"vaciabas","3s":"vaciaba","1p":"vaciábamos","2p":"vaciabais","3p":"vaciaban","vos":"vaciabas"})
assert_TenseMood("vaciar", "FutInd",  {"1s":"vaciaré","2s":"vaciarás","3s":"vaciará","1p":"vaciaremos","2p":"vaciaréis","3p":"vaciarán","vos":"vaciarás"})
assert_TenseMood("vaciar", "FutCond", {"1s":"vaciaría","2s":"vaciarías","3s":"vaciaría","1p":"vaciaríamos","2p":"vaciaríais","3p":"vaciarían","vos":"vaciarías"})
assert_TenseMood("vaciar", "CmdPos",  {"1s":null,"2s":"vacía","3s":"vacíe","1p":"vaciemos","2p":"vaciad","3p":"vacíen","vos":"vaciá"})
assert_TenseMood("vaciar", "CmdNeg",  {"1s":null,"2s":"vacíes","3s":"vacíe","1p":"vaciemos","2p":"vaciéis","3p":"vacíen","vos":["vacíes","*vaciés"]})

assert_TenseMood("venir", "PresInd", {"1s":"vengo","2s":"vienes","3s":"viene","1p":"venimos","2p":"venís","3p":"vienen","vos":"venís"})
assert_TenseMood("venir", "PresSub", {"1s":"venga","2s":"vengas","3s":"venga","1p":"vengamos","2p":"vengáis","3p":"vengan","vos":"vengas"})
assert_TenseMood("venir", "PastInd", {"1s":"vine","2s":"viniste","3s":"vino","1p":"vinimos","2p":"vinisteis","3p":"vinieron","vos":"viniste"})
assert_TenseMood("venir", "PastImp", {"1s":"venía","2s":"venías","3s":"venía","1p":"veníamos","2p":"veníais","3p":"venían","vos":"venías"})
assert_TenseMood("venir", "FutInd",  {"1s":"vendré","2s":"vendrás","3s":"vendrá","1p":"vendremos","2p":"vendréis","3p":"vendrán","vos":"vendrás"})
assert_TenseMood("venir", "FutCond", {"1s":"vendría","2s":"vendrías","3s":"vendría","1p":"vendríamos","2p":"vendríais","3p":"vendrían","vos":"vendrías"})
assert_TenseMood("venir", "CmdPos",  {"1s":null,"2s":"ven","3s":"venga","1p":"vengamos","2p":"venid","3p":"vengan","vos":"vení"})
assert_TenseMood("venir", "CmdNeg",  {"1s":null,"2s":"vengas","3s":"venga","1p":"vengamos","2p":"vengáis","3p":"vengan","vos":["vengas","*vengás"]})

assert_TenseMood("ver", "PresInd", {"1s":"veo","2s":"ves","3s":"ve","1p":"vemos","2p":"veis","3p":"ven","vos":"ves"})
assert_TenseMood("ver", "PresSub", {"1s":"vea","2s":"veas","3s":"vea","1p":"veamos","2p":"veáis","3p":"vean","vos":"veas"})
assert_TenseMood("ver", "PastInd", {"1s":"vi","2s":"viste","3s":"vio","1p":"vimos","2p":"visteis","3p":"vieron","vos":"viste"})
assert_TenseMood("ver", "PastImp", {"1s":"veía","2s":"veías","3s":"veía","1p":"veíamos","2p":"veíais","3p":"veían","vos":"veías"})
assert_TenseMood("ver", "FutInd", {"1s":"veré","2s":"verás","3s":"verá","1p":"veremos","2p":"veréis","3p":"verán","vos":"verás"})
assert_TenseMood("ver", "FutCond", {"1s":"vería","2s":"verías","3s":"vería","1p":"veríamos","2p":"veríais","3p":"verían","vos":"verías"})
assert_TenseMood("ver", "CmdPos", {"1s":null,"2s":"ve","3s":"vea","1p":"veamos","2p":"ved","3p":"vean","vos":"ve"})
assert_TenseMood("ver", "CmdNeg", {"1s":null,"2s":"veas","3s":"vea","1p":"veamos","2p":"veáis","3p":"vean","vos":"veas"})



assert_typographicalChange({conjugated_form: "empezé", infinitive: "empezar"}, "empecé")
assert_typographicalChange({conjugated_form: "conoco", infinitive: "conocer"}, "conozco")
assert_typographicalChange({conjugated_form: "sacé", infinitive: "sacar"}, "saqué")
assert_typographicalChange({conjugated_form: "eligo", infinitive: "elegir"}, "elijo")
assert_typographicalChange({conjugated_form: "llegé", infinitive: "llegar"}, "llegué")
