import { assert_Participles, assert_TenseMood, assert_typographicalChange } from "./test-support.js"


// -ar
assert_Participles("amar", {pres: "amando", past: "amado"})
assert_TenseMood("amar", "IndPres", {s1: "amo", s2: "amas", s3: "ama", p1: "amamos", p2: "amáis", p3: "aman", vos: "amás"})
assert_TenseMood("amar", "IndImp", {s1: "amaba", s2: "amabas", s3: "amaba", p1: "amábamos", p2: "amabais", p3: "amaban"})
assert_TenseMood("amar", "IndPret", {s1: "amé", s2: "amaste", s3: "amó", p1: "amamos", p2: "amasteis", p3: "amaron"})
assert_TenseMood("amar", "IndFut", {s1: "amaré", s2: "amarás", s3: "amará", p1: "amaremos", p2: "amaréis", p3: "amarán"})
assert_TenseMood("amar", "IndCond", {s1: "amaría", s2: "amarías", s3: "amaría", p1: "amaríamos", p2: "amaríais", p3: "amarían"})
// TODO: SubPres,vos has 2nd form, C.Am regional: amés
assert_TenseMood("amar", "SubPres", {s1: "ame", s2: "ames", s3: "ame", p1: "amemos", p2: "améis", p3: "amen"})
assert_TenseMood("amar", "SubImp", {s1: ["amara","amase"], s2: ["amaras","amases"], s3: ["amara","amase"], p1: ["amáramos", "amásemos"], p2: ["amarais", "amaseis"], p3: ["amaran", "amasen"]})
assert_TenseMood("amar", "SubFut", {s1:"amare",s2:"amares",s3:"amare",p1:"amáremos",p2:"amareis",p3:"amaren"})
assert_TenseMood("amar", "CmdPos", {s1: null, s2: "ama", s3: "ame", p1: "amemos", p2: "amad", p3: "amen", vos: "amá"})
assert_TenseMood("amar", "CmdNeg", {s1: null, s2: "ames", s3: "ame", p1: "amemos", p2: "améis", p3: "amen"})


// -er
assert_Participles("beber", { pres: "bebiendo", past: "bebido" })
assert_TenseMood("beber", "IndPres", {s1: "bebo", s2: "bebes", s3: "bebe", p1: "bebemos", p2: "bebéis", p3: "beben", vos: "bebés"})
assert_TenseMood("beber", "IndImp", {s1: "bebía", s2: "bebías", s3: "bebía",  p1: "bebíamos", p2: "bebíais", p3: "bebían"})
assert_TenseMood("beber", "IndPret", {s1: "bebí", s2: "bebiste", s3: "bebió", p1: "bebimos", p2: "bebisteis", p3: "bebieron"})
assert_TenseMood("beber", "IndFut", {s1: "beberé", s2: "beberás", s3: "beberá", p1: "beberemos", p2: "beberéis", p3: "beberán"})
assert_TenseMood("beber", "IndCond", {s1: "bebería", s2: "beberías", s3: "bebería", p1: "beberíamos", p2: "beberíais", p3: "beberían"})
assert_TenseMood("beber", "SubPres", {s1: "beba", s2: "bebas", s3: "beba", p1: "bebamos", p2: "bebáis", p3: "beban"})
assert_TenseMood("beber", "SubImp", {s1: ["bebiera","bebiese"], s2: ["bebieras","bebieses"], s3: ["bebiera","bebiese"], p1: ["bebiéramos", "bebiésemos"], p2: ["bebierais", "bebieseis"], p3: ["bebieran", "bebiesen"]})
assert_TenseMood("beber", "SubFut", {s1:"bebiere",s2:"bebieres",s3:"bebiere",p1:"bebiéremos",p2:"bebiereis",p3:"bebieren"})
assert_TenseMood("beber", "CmdPos", {s1: null, s2: "bebe", s3: "beba", p1: "bebamos", p2: "bebed", p3: "beban", vos: "bebé"})
assert_TenseMood("beber", "CmdNeg", {s1: null, s2: "bebas", s3: "beba", p1: "bebamos", p2: "bebáis", p3: "beban"})


// -ir
assert_Participles("partir", { pres: "partiendo", past: "partido" })
assert_TenseMood("partir", "IndPres", {s1: "parto", s2: "partes", s3: "parte", p1: "partimos", p2: "partís", p3: "parten", vos: "partís"})
assert_TenseMood("partir", "IndImp", {s1: "partía", s2: "partías", s3: "partía",  p1: "partíamos", p2: "partíais", p3: "partían"})
assert_TenseMood("partir", "IndPret", {s1: "partí", s2: "partiste", s3: "partió", p1: "partimos", p2: "partisteis", p3: "partieron"})
assert_TenseMood("partir", "IndFut", {s1: "partiré", s2: "partirás", s3: "partirá", p1: "partiremos", p2: "partiréis", p3: "partirán"})
assert_TenseMood("partir", "IndCond", {s1: "partiría", s2: "partirías", s3: "partiría", p1: "partiríamos", p2: "partiríais", p3: "partirían"})
assert_TenseMood("partir", "SubPres", {s1: "parta", s2: "partas", s3: "parta", p1: "partamos", p2: "partáis", p3: "partan"})
assert_TenseMood("partir", "SubImp", {s1: ["partiera","partiese"], s2: ["partieras","partieses"], s3: ["partiera","partiese"], p1: ["partiéramos", "partiésemos"], p2: ["partierais", "partieseis"], p3: ["partieran", "partiesen"]})
assert_TenseMood("partir","SubFut",{s1:"partiere",s2:"partieres",s3:"partiere",p1:"partiéremos",p2:"partiereis",p3:"partieren"})
assert_TenseMood("partir", "CmdPos", {s1: null, s2: "parte", s3: "parta", p1: "partamos", p2: "partid", p3: "partan", vos: "partí"})
assert_TenseMood("partir", "CmdNeg", {s1: null, s2: "partas", s3: "parta", p1: "partamos", p2: "partáis", p3: "partan"})

// all other verbs

assert_Participles("acertar", { pres: "acertando", past: "acertado" })
assert_TenseMood("acertar", "IndPres", {s1: "acierto", s2: "aciertas", s3: "acierta", p1: "acertamos", p2: "acertáis", p3: "aciertan", vos: "acertás"})
assert_TenseMood("acertar", "IndImp", {s1: "acertaba", s2: "acertabas", s3: "acertaba", p1: "acertábamos", p2: "acertabais", p3: "acertaban"})
assert_TenseMood("acertar", "IndPret", {s1: "acerté", s2: "acertaste", s3: "acertó", p1: "acertamos", p2: "acertasteis", p3: "acertaron"})
assert_TenseMood("acertar", "IndFut", {s1: "acertaré", s2: "acertarás", s3: "acertará", p1: "acertaremos", p2: "acertaréis", p3: "acertarán"})
assert_TenseMood("acertar", "IndCond", {s1: "acertaría", s2: "acertarías", s3: "acertaría", p1: "acertaríamos", p2: "acertaríais", p3: "acertarían"})
assert_TenseMood("acertar", "SubPres", {s1: "acierte", s2: "aciertes", s3: "acierte", p1: "acertemos", p2: "acertéis", p3: "acierten"})
assert_TenseMood("acertar", "SubImp", {s1: ["acertara","acertase"], s2: ["acertaras","acertases"], s3: ["acertara","acertase"], p1: ["acertáramos", "acertásemos"], p2: ["acertarais", "acertaseis"], p3: ["acertaran", "acertasen"]})
assert_TenseMood("acertar","SubFut",{s1:"acertare",s2:"acertares",s3:"acertare",p1:"acertáremos",p2:"acertareis",p3:"acertaren"})
assert_TenseMood("acertar", "CmdPos", {s1:null, s2: "acierta", s3: "acierte", p1: "acertemos", p2: "acertad", p3: "acierten", vos: "acertá"})
assert_TenseMood("acertar", "CmdNeg", {s1:null, s2: "aciertes", s3: "acierte", p1: "acertemos", p2: "acertéis", p3: "acierten"})

assert_Participles("acordar", { pres: "acordando", past: "acordado" })
assert_TenseMood("acordar", "IndPres", {s1: "acuerdo", s2: "acuerdas", s3: "acuerda", p1: "acordamos", p2: "acordáis", p3: "acuerdan", vos: "acordás"})
assert_TenseMood("acordar", "IndPret", {s1: "acordé", s2: "acordaste", s3: "acordó", p1: "acordamos", p2: "acordasteis", p3: "acordaron"})
assert_TenseMood("acordar", "IndImp", {s1: "acordaba", s2: "acordabas", s3: "acordaba", p1: "acordábamos", p2: "acordabais", p3: "acordaban"})
assert_TenseMood("acordar", "IndFut",  {s1: "acordaré", s2: "acordarás", s3: "acordará", p1: "acordaremos", p2: "acordaréis", p3: "acordarán"})
assert_TenseMood("acordar", "IndCond", {s1: "acordaría", s2: "acordarías", s3: "acordaría", p1: "acordaríamos", p2: "acordaríais", p3: "acordarían"})
assert_TenseMood("acordar", "SubPres", {s1: "acuerde", s2: "acuerdes", s3: "acuerde", p1: "acordemos", p2: "acordéis", p3: "acuerden"})
assert_TenseMood("acordar", "SubImp", {s1:["acordara","acordase"],s2:["acordaras","acordases"],s3:["acordara","acordase"],p1:["acordáramos","acordásemos"],p2:["acordarais","acordaseis"],p3:["acordaran","acordasen"]})
assert_TenseMood("acordar","SubFut",{s1:"acordare",s2:"acordares",s3:"acordare",p1:"acordáremos",p2:"acordareis",p3:"acordaren"})
assert_TenseMood("acordar", "CmdPos",  {s1:null, s2: "acuerda", s3: "acuerde", p1: "acordemos", p2: "acordad", p3: "acuerden", vos: "acordá"})
assert_TenseMood("acordar", "CmdNeg",  {s1:null, s2: "acuerdes", s3: "acuerde", p1: "acordemos", p2: "acordéis", p3: "acuerden"})

assert_Participles("almorzar", { pres: "almorzando", past: "almorzado" })
assert_TenseMood("almorzar", "IndPres", {s1: "almuerzo", s2: "almuerzas", s3: "almuerza", p1: "almorzamos", p2: "almorzáis", p3: "almuerzan", vos: "almorzás"})
assert_TenseMood("almorzar", "IndImp", {s1: "almorzaba", s2: "almorzabas", s3: "almorzaba", p1: "almorzábamos", p2: "almorzabais", p3: "almorzaban"})
assert_TenseMood("almorzar", "IndPret", {s1: "almorcé", s2: "almorzaste", s3: "almorzó", p1: "almorzamos", p2: "almorzasteis", p3: "almorzaron"})
assert_TenseMood("almorzar", "IndFut", {s1: "almorzaré", s2: "almorzarás", s3: "almorzará", p1: "almorzaremos", p2: "almorzaréis", p3: "almorzarán"})
assert_TenseMood("almorzar", "IndCond", {s1: "almorzaría", s2: "almorzarías", s3: "almorzaría", p1: "almorzaríamos", p2: "almorzaríais", p3: "almorzarían"})
assert_TenseMood("almorzar", "SubPres", {s1: "almuerce", s2: "almuerces", s3: "almuerce", p1: "almorcemos", p2: "almorcéis", p3: "almuercen"})
assert_TenseMood("almorzar", "SubImp", {s1:["almorzara","almorzase"],s2:["almorzaras","almorzases"],s3:["almorzara","almorzase"],p1:["almorzáramos","almorzásemos"],p2:["almorzarais","almorzaseis"],p3:["almorzaran","almorzasen"]})
assert_TenseMood("almorzar","SubFut",{s1:"almorzare",s2:"almorzares",s3:"almorzare",p1:"almorzáremos",p2:"almorzareis",p3:"almorzaren"})
assert_TenseMood("almorzar", "CmdPos", {s1:null, s2: "almuerza", s3: "almuerce", p1: "almorcemos", p2: "almorzad", p3: "almuercen", vos: "almorzá"})
assert_TenseMood("almorzar", "CmdNeg", {s1:null, s2: "almuerces", s3: "almuerce", p1: "almorcemos", p2: "almorcéis", p3: "almuercen"})

assert_Participles("andar", { pres: "andando", past: "andado" })
assert_TenseMood("andar", "IndPres", {s1: "ando", s2: "andas", s3: "anda", p1: "andamos", p2: "andáis", p3: "andan", vos: "andás"})
assert_TenseMood("andar", "IndImp", {s1: "andaba", s2: "andabas", s3: "andaba", p1: "andábamos", p2: "andabais", p3: "andaban"})
assert_TenseMood("andar", "IndPret", {s1: "anduve", s2: "anduviste", s3: "anduvo", p1: "anduvimos", p2: "anduvisteis", p3: "anduvieron"})
assert_TenseMood("andar", "IndFut", {s1: "andaré", s2: "andarás", s3: "andará", p1: "andaremos", p2: "andaréis", p3: "andarán"})
assert_TenseMood("andar", "IndCond", {s1: "andaría", s2: "andarías", s3: "andaría", p1: "andaríamos", p2: "andaríais", p3: "andarían"})
assert_TenseMood("andar", "SubPres", {s1: "ande", s2: "andes", s3: "ande", p1: "andemos", p2: "andéis", p3: "anden"})
assert_TenseMood("andar", "SubImp", {s1: ["anduviera","anduviese"], s2: ["anduvieras","anduvieses"], s3: ["anduviera","anduviese"], p1: ["anduviéramos","anduviésemos"], p2: ["anduvierais","anduvieseis"], p3: ["anduvieran","anduviesen"]})
assert_TenseMood("andar","SubFut",{s1:"anduviere",s2:"anduvieres",s3:"anduviere",p1:"anduviéremos",p2:"anduviereis",p3:"anduvieren"})
assert_TenseMood("andar", "CmdPos", {s1: null, s2: "anda", s3: "ande", p1: "andemos", p2: "andad", p3: "anden", vos: "andá"})
assert_TenseMood("andar", "CmdNeg", {s1: null, s2: "andes", s3: "ande", p1: "andemos", p2: "andéis", p3: "anden"})

// "-üir" family of typographic changes
assert_Participles("argüir", { pres: "arguyendo", past: "argüido" })
assert_TenseMood("argüir","IndPres",{s1: "arguyo",s2: "arguyes",s3: "arguye",p1: "argüimos",p2: "argüís",p3: "arguyen",vos: "argüís"})
assert_TenseMood("argüir","IndImp",{s1: "argüía",s2: "argüías",s3: "argüía",p1: "argüíamos",p2: "argüíais",p3: "argüían"})
assert_TenseMood("argüir","IndPret",{s1: "argüí",s2: "argüiste",s3: "arguyó",p1: "argüimos",p2: "argüisteis",p3: "arguyeron"})
assert_TenseMood("argüir","IndFut",{s1: "argüiré",s2: "argüirás",s3: "argüirá",p1: "argüiremos",p2: "argüiréis",p3: "argüirán"})
assert_TenseMood("argüir","IndCond",{s1: "argüiría",s2: "argüirías",s3: "argüiría",p1: "argüiríamos",p2: "argüiríais",p3: "argüirían"})
assert_TenseMood("argüir","SubPres",{s1: "arguya",s2: "arguyas",s3: "arguya",p1: "arguyamos",p2: "arguyáis",p3: "arguyan"})
assert_TenseMood("argüir","SubImp",{s1:["arguyera","arguyese"],s2:["arguyeras","arguyeses"],s3:["arguyera","arguyese"],p1:["arguyéramos","arguyésemos"],p2:["arguyerais","arguyeseis"],p3:["arguyeran","arguyesen"]})
assert_TenseMood("argüir","SubFut",{s1:"arguyere",s2:"arguyeres",s3:"arguyere",p1:"arguyéremos",p2:"arguyereis",p3:"arguyeren"})
assert_TenseMood("argüir","CmdPos",{s1:null,s2: "arguye",s3: "arguya",p1: "arguyamos",p2: "argüid",p3: "arguyan",vos: "argüí"})
assert_TenseMood("argüir","CmdNeg",{s1:null,s2: "arguyas",s3: "arguya",p1: "arguyamos",p2: "arguyáis",p3: "arguyan"})

assert_Participles("caber", { pres: "cabiendo", past: "cabido" })
assert_TenseMood("caber", "IndPres", {s1: "quepo",s2: "cabes",s3: "cabe",p1: "cabemos",p2: "cabéis",p3: "caben",vos: "cabés"})
assert_TenseMood("caber", "IndImp", {s1: "cabía",s2: "cabías",s3: "cabía",p1: "cabíamos",p2: "cabíais",p3: "cabían"})
assert_TenseMood("caber", "IndPret", {s1: "cupe",s2: "cupiste",s3: "cupo",p1: "cupimos",p2: "cupisteis",p3: "cupieron"})
assert_TenseMood("caber", "IndFut", {s1: "cabré",s2: "cabrás",s3: "cabrá",p1: "cabremos",p2: "cabréis",p3: "cabrán"})
assert_TenseMood("caber", "IndCond", {s1: "cabría",s2: "cabrías",s3: "cabría",p1: "cabríamos",p2: "cabríais",p3: "cabrían"})
assert_TenseMood("caber", "SubPres", {s1: "quepa",s2: "quepas",s3: "quepa",p1: "quepamos",p2: "quepáis",p3: "quepan"})
assert_TenseMood("caber","SubImp",{s1:["cupiera","cupiese"],s2:["cupieras","cupieses"],s3:["cupiera","cupiese"],p1:["cupiéramos","cupiésemos"],p2:["cupierais","cupieseis"],p3:["cupieran","cupiesen"]})
assert_TenseMood("caber","SubFut",{s1:"cupiere",s2:"cupieres",s3:"cupiere",p1:"cupiéremos",p2:"cupiereis",p3:"cupieren"})
assert_TenseMood("caber", "CmdPos", {s1:null,s2: "cabe",s3: "quepa",p1: "quepamos",p2: "cabed",p3: "quepan",vos: "cabé"})
assert_TenseMood("caber", "CmdNeg", {s1:null,s2: "quepas",s3: "quepa",p1: "quepamos",p2: "quepáis",p3: "quepan"})

assert_Participles("caer", { pres: "cayendo", past: "caído" })
assert_TenseMood("caer", "IndPres", {s1: "caigo",s2: "caes",s3: "cae",p1: "caemos",p2: "caéis",p3: "caen",vos: "caés"})
assert_TenseMood("caer", "IndImp", {s1: "caía",s2: "caías",s3: "caía",p1: "caíamos",p2: "caíais",p3: "caían"})
assert_TenseMood("caer", "IndPret", {s1: "caí",s2: "caíste",s3: "cayó",p1: "caímos",p2: "caísteis",p3: "cayeron"})
assert_TenseMood("caer", "IndFut", {s1: "caeré",s2: "caerás",s3: "caerá",p1: "caeremos",p2: "caeréis",p3: "caerán"})
assert_TenseMood("caer", "IndCond", {s1: "caería",s2: "caerías",s3: "caería",p1: "caeríamos",p2: "caeríais",p3: "caerían"})
assert_TenseMood("caer", "SubPres", {s1: "caiga",s2: "caigas",s3: "caiga",p1: "caigamos",p2: "caigáis",p3: "caigan"})
assert_TenseMood("caer","SubImp",{s1:["cayera","cayese"],s2:["cayeras","cayeses"],s3:["cayera","cayese"],p1:["cayéramos","cayésemos"],p2:["cayerais","cayeseis"],p3:["cayeran","cayesen"]})
assert_TenseMood("caer","SubFut",{s1:"cayere",s2:"cayeres",s3:"cayere",p1:"cayéremos",p2:"cayereis",p3:"cayeren"})
assert_TenseMood("caer", "CmdPos", {s1:null,s2: "cae",s3: "caiga",p1: "caigamos",p2: "caed",p3: "caigan",vos: "caé"})
assert_TenseMood("caer", "CmdNeg", {s1:null,s2: "caigas",s3: "caiga",p1: "caigamos",p2: "caigáis",p3: "caigan"})

assert_Participles("conducir", { pres: "conduciendo", past: "conducido" })
assert_TenseMood("conducir", "IndPres", {s1: "conduzco",s2: "conduces",s3: "conduce",p1: "conducimos",p2: "conducís",p3: "conducen",vos: "conducís"})
assert_TenseMood("conducir", "IndImp", {s1: "conducía",s2: "conducías",s3: "conducía",p1: "conducíamos",p2: "conducíais",p3: "conducían"})
assert_TenseMood("conducir", "IndPret", {s1: "conduje",s2: "condujiste",s3: "condujo",p1: "condujimos",p2: "condujisteis",p3: "condujeron"})
assert_TenseMood("conducir", "IndFut", {s1: "conduciré",s2: "conducirás",s3: "conducirá",p1: "conduciremos",p2: "conduciréis",p3: "conducirán"})
assert_TenseMood("conducir", "IndCond", {s1: "conduciría",s2: "conducirías",s3: "conduciría",p1: "conduciríamos",p2: "conduciríais",p3: "conducirían"})
assert_TenseMood("conducir", "SubPres", {s1: "conduzca",s2: "conduzcas",s3: "conduzca",p1: "conduzcamos",p2: "conduzcáis",p3: "conduzcan"})
assert_TenseMood("conducir","SubImp",{s1:["condujera","condujese"],s2:["condujeras","condujeses"],s3:["condujera","condujese"],p1:["condujéramos","condujésemos"],p2:["condujerais","condujeseis"],p3:["condujeran","condujesen"]})
assert_TenseMood("conducir","SubFut",{s1:"condujere",s2:"condujeres",s3:"condujere",p1:"condujéremos",p2:"condujereis",p3:"condujeren"})
assert_TenseMood("conducir", "CmdPos", {s1:null,s2: "conduce",s3: "conduzca",p1: "conduzcamos",p2: "conducid",p3: "conduzcan",vos: "conducí"})
assert_TenseMood("conducir", "CmdNeg", {s1:null,s2: "conduzcas",s3: "conduzca",p1: "conduzcamos",p2: "conduzcáis",p3: "conduzcan"})


// test prefix + irregular base: 'co-' + 'ser'
assert_Participles("coser", { pres: "cosiendo", past: "cosido" })
assert_TenseMood("coser", "IndPres", {s1: "coso", s2: "coses", s3: "cose",     p1: "cosemos",  p2: "coséis",    p3: "cosen", vos: "cosés"})
assert_TenseMood("coser", "IndImp", {s1: "cosía", s2: "cosías", s3: "cosía",  p1: "cosíamos", p2: "cosíais",  p3: "cosían"})
assert_TenseMood("coser", "IndPret", {s1: "cosí", s2: "cosiste", s3: "cosió",   p1: "cosimos",  p2: "cosisteis", p3: "cosieron"})
assert_TenseMood("coser", "IndFut",  {s1: "coseré", s2: "coserás", s3: "coserá", p1: "coseremos", p2: "coseréis", p3: "coserán"})
assert_TenseMood("coser", "IndCond", {s1: "cosería", s2: "coserías", s3: "cosería", p1: "coseríamos", p2: "coseríais", p3: "coserían"})
assert_TenseMood("coser", "SubPres", {s1: "cosa", s2: "cosas", s3: "cosa",     p1: "cosamos",  p2: "cosáis",    p3: "cosan"})
assert_TenseMood("coser","SubImp",{s1:["cosiera","cosiese"],s2:["cosieras","cosieses"],s3:["cosiera","cosiese"],p1:["cosiéramos","cosiésemos"],p2:["cosierais","cosieseis"],p3:["cosieran","cosiesen"]})
assert_TenseMood("coser","SubFut",{s1:"cosiere",s2:"cosieres",s3:"cosiere",p1:"cosiéremos",p2:"cosiereis",p3:"cosieren"})
assert_TenseMood("coser", "CmdPos",  {s1:null, s2: "cose", s3: "cosa",        p1: "cosamos",  p2: "cosed",    p3: "cosan", vos: "cosé"})
assert_TenseMood("coser", "CmdNeg",  {s1:null, s2: "cosas", s3: "cosa",       p1: "cosamos",  p2: "cosáis",   p3: "cosan"})

assert_Participles("creer", { pres: "creyendo", past: "creído" })
assert_TenseMood("creer", "IndPres", {s1: "creo",s2: "crees",s3: "cree",p1: "creemos",p2: "creéis",p3: "creen",vos: "creés"})
assert_TenseMood("creer", "IndImp", {s1: "creía",s2: "creías",s3: "creía",p1: "creíamos",p2: "creíais",p3: "creían"})
assert_TenseMood("creer", "IndPret", {s1: "creí",s2: "creíste",s3: "creyó",p1: "creímos",p2: "creísteis",p3: "creyeron"})
assert_TenseMood("creer", "IndFut",  {s1: "creeré",s2: "creerás",s3: "creerá",p1: "creeremos",p2: "creeréis",p3: "creerán"})
assert_TenseMood("creer", "IndCond", {s1: "creería",s2: "creerías",s3: "creería",p1: "creeríamos",p2: "creeríais",p3: "creerían"})
assert_TenseMood("creer", "SubPres", {s1: "crea",s2: "creas",s3: "crea",p1: "creamos",p2: "creáis",p3: "crean"})
assert_TenseMood("creer","SubImp",{s1:["creyera","creyese"],s2:["creyeras","creyeses"],s3:["creyera","creyese"],p1:["creyéramos","creyésemos"],p2:["creyerais","creyeseis"],p3:["creyeran","creyesen"]})
assert_TenseMood("creer","SubFut",{s1:"creyere",s2:"creyeres",s3:"creyere",p1:"creyéremos",p2:"creyereis",p3:"creyeren"})
assert_TenseMood("creer", "CmdPos",  {s1:null,s2: "cree",s3: "crea",p1: "creamos",p2: "creed",p3: "crean",vos: "creé"})
assert_TenseMood("creer", "CmdNeg",  {s1:null,s2: "creas",s3: "crea",p1: "creamos",p2: "creáis",p3: "crean"})

assert_Participles("dar", { pres: "dando", past: "dado" })
assert_TenseMood("dar", "IndPres", {s1: "doy", s2: "das", s3: "da", p1: "damos", p2: "dais", p3: "dan"})
assert_TenseMood("dar", "IndImp", {s1: "daba", s2: "dabas", s3: "daba",  p1: "dábamos", p2: "dabais", p3: "daban"})
assert_TenseMood("dar", "IndPret", {s1: "di", s2: "diste", s3: "dio",  p1: "dimos", p2: "disteis", p3: "dieron"})
assert_TenseMood("dar", "IndFut", {s1: "daré", s2: "darás", s3: "dará", p1: "daremos", p2: "daréis", p3: "darán"})
assert_TenseMood("dar", "IndCond", {s1: "daría", s2: "darías", s3: "daría", p1: "daríamos", p2: "daríais", p3: "darían"})
assert_TenseMood("dar", "SubPres", {s1: "dé", s2: "des", s3: "dé", p1: "demos", p2: "deis", p3: "den"})
assert_TenseMood("dar", "SubImp",{s1:["diera","diese"],s2:["dieras","dieses"],s3:["diera","diese"],p1:["diéramos","diésemos"],p2:["dierais","dieseis"],p3:["dieran","diesen"]})
assert_TenseMood("dar","SubFut",{s1:"diere",s2:"dieres",s3:"diere",p1:"diéremos",p2:"diereis",p3:"dieren"})
assert_TenseMood("dar", "CmdPos", {s1: null, s2: "da", s3: "dé", p1: "demos", p2: "dad", p3: "den"})
assert_TenseMood("dar", "CmdNeg", {s1: null, s2: "des", s3: "dé", p1: "demos", p2: "deis", p3: "den"})

assert_Participles("decir", { pres: "diciendo", past: "dicho" })
assert_TenseMood("decir", "IndPres", {s1: "digo", s2: "dices", s3: "dice",     p1: "decimos", p2: "decís", p3: "dicen",    vos: "decís"})
assert_TenseMood("decir", "IndImp",  {s1: "decía", s2: "decías", s3: "decía",  p1: "decíamos", p2: "decíais", p3: "decían"})
assert_TenseMood("decir", "IndPret", {s1: "dije", s2: "dijiste", s3: "dijo",   p1: "dijimos", p2: "dijisteis", p3: "dijeron"})
assert_TenseMood("decir", "IndFut",  {s1: "diré", s2: "dirás", s3: "dirá",     p1: "diremos",  p2: "diréis", p3: "dirán" })
assert_TenseMood("decir", "IndCond", {s1: "diría", s2: "dirías", s3: "diría",  p1: "diríamos", p2: "diríais", p3: "dirían" })
assert_TenseMood("decir", "SubPres", {s1: "diga", s2: "digas", s3: "diga",     p1: "digamos", p2: "digáis", p3: "digan"})
assert_TenseMood("decir","SubImp",{s1:["dijera","dijese"],s2:["dijeras","dijeses"],s3:["dijera","dijese"],p1:["dijéramos","dijésemos"],p2:["dijerais","dijeseis"],p3:["dijeran","dijesen"]})
assert_TenseMood("decir","SubFut",{s1:"dijere",s2:"dijeres",s3:"dijere",p1:"dijéremos",p2:"dijereis",p3:"dijeren"})
assert_TenseMood("decir", "CmdPos",  {s1: null,   s2: "di", s3: "diga",        p1: "digamos",  p2: "decid", p3: "digan",  vos: "decí" })
assert_TenseMood("decir", "CmdNeg",  {s1: null,   s2: "digas", s3: "diga",     p1: "digamos",  p2: "digáis", p3: "digan" })

// regular but with a unique "-quir" ending that requires spelling changes
assert_Participles("delinquir", { pres: "delinquiendo", past: "delinquido" })
assert_TenseMood("delinquir", "IndPres", {s1: "delinco",s2: "delinques",s3: "delinque",p1: "delinquimos",p2: "delinquís",p3: "delinquen",vos: "delinquís"})
assert_TenseMood("delinquir", "IndImp", {s1: "delinquía",s2: "delinquías",s3: "delinquía",p1: "delinquíamos",p2: "delinquíais",p3: "delinquían"})
assert_TenseMood("delinquir", "IndPret", {s1: "delinquí",s2: "delinquiste",s3: "delinquió",p1: "delinquimos",p2: "delinquisteis",p3: "delinquieron"})
assert_TenseMood("delinquir", "IndFut",  {s1: "delinquiré",s2: "delinquirás",s3: "delinquirá",p1: "delinquiremos",p2: "delinquiréis",p3: "delinquirán"})
assert_TenseMood("delinquir", "IndCond", {s1: "delinquiría",s2: "delinquirías",s3: "delinquiría",p1: "delinquiríamos",p2: "delinquiríais",p3: "delinquirían"})
assert_TenseMood("delinquir", "SubPres", {s1: "delinqua",s2: "delinquas",s3: "delinqua",p1: "delinquamos",p2: "delinquáis",p3: "delinquan"})
assert_TenseMood("delinquir", "SubImp",{s1:["delinquiera","delinquiese"],s2:["delinquieras","delinquieses"],s3:["delinquiera","delinquiese"],p1:["delinquiéramos","delinquiésemos"],p2:["delinquierais","delinquieseis"],p3:["delinquieran","delinquiesen"]})
assert_TenseMood("delinquir","SubFut",{s1:"delinquiere",s2:"delinquieres",s3:"delinquiere",p1:"delinquiéremos",p2:"delinquiereis",p3:"delinquieren"})
assert_TenseMood("delinquir", "CmdPos",  {s1:null,s2: "delinque",s3: "delinqua",p1: "delinquamos",p2: "delinquid",p3: "delinquan",vos: "delinquí"})
assert_TenseMood("delinquir", "CmdNeg",  {s1:null,s2: "delinquas",s3: "delinqua",p1: "delinquamos",p2: "delinquáis",p3: "delinquan"})

// descreer: prefix 'des' + conjugation_family_prefix 'cr' + '-eer'
assert_Participles("descreer", { pres: "descreyendo", past: "descreído" })
assert_TenseMood("descreer", "IndPres", {s1: "descreo",s2: "descrees",s3: "descree",p1: "descreemos",p2: "descreéis",p3: "descreen",vos: "descreés"})
assert_TenseMood("descreer", "IndImp", {s1: "descreía",s2: "descreías",s3: "descreía",p1: "descreíamos",p2: "descreíais",p3: "descreían"})
assert_TenseMood("descreer", "IndPret", {s1: "descreí",s2: "descreíste",s3: "descreyó",p1: "descreímos",p2: "descreísteis",p3: "descreyeron"})
assert_TenseMood("descreer", "IndFut", {s1: "descreeré",s2: "descreerás",s3: "descreerá",p1: "descreeremos",p2: "descreeréis",p3: "descreerán"})
assert_TenseMood("descreer", "IndCond", {s1: "descreería",s2: "descreerías",s3: "descreería",p1: "descreeríamos",p2: "descreeríais",p3: "descreerían"})
assert_TenseMood("descreer", "SubPres", {s1: "descrea",s2: "descreas",s3: "descrea",p1: "descreamos",p2: "descreáis",p3: "descrean"})
assert_TenseMood("descreer", "SubImp", {s1:["descreyera","descreyese"],s2:["descreyeras","descreyeses"],s3:["descreyera","descreyese"],p1:["descreyéramos","descreyésemos"],p2:["descreyerais","descreyeseis"],p3:["descreyeran","descreyesen"]})
assert_TenseMood("descreer", "SubFut", {s1:"descreyere",s2:"descreyeres",s3:"descreyere",p1:"descreyéremos",p2:"descreyereis",p3:"descreyeren"})
assert_TenseMood("descreer", "CmdPos", {s1:null,s2: "descree",s3: "descrea",p1: "descreamos",p2: "descreed",p3: "descrean",vos: "descreé"})
assert_TenseMood("descreer", "CmdNeg", {s1:null,s2: "descreas",s3: "descrea",p1: "descreamos",p2: "descreáis",p3: "descrean"})

// tests prefix 'de' + 'tener'
assert_Participles("detener", { pres: "deteniendo", past: "detenido" })
assert_TenseMood("detener", "IndPres", {s1: "detengo",s2: "detienes",s3: "detiene",p1: "detenemos",p2: "detenéis",p3: "detienen",vos: "detenés"})
assert_TenseMood("detener", "IndImp", {s1: "detenía",s2: "detenías",s3: "detenía",p1: "deteníamos",p2: "deteníais",p3: "detenían"})
assert_TenseMood("detener", "IndPret", {s1: "detuve",s2: "detuviste",s3: "detuvo",p1: "detuvimos",p2: "detuvisteis",p3: "detuvieron"})
assert_TenseMood("detener", "IndFut", {s1: "detendré",s2: "detendrás",s3: "detendrá",p1: "detendremos",p2: "detendréis",p3: "detendrán"})
assert_TenseMood("detener", "IndCond", {s1: "detendría",s2: "detendrías",s3: "detendría",p1: "detendríamos",p2: "detendríais",p3: "detendrían"})
assert_TenseMood("detener", "SubPres", {s1: "detenga",s2: "detengas",s3: "detenga",p1: "detengamos",p2: "detengáis",p3: "detengan"})
assert_TenseMood("detener", "SubImp",{s1:["detuviera","detuviese"],s2:["detuvieras","detuvieses"],s3:["detuviera","detuviese"],p1:["detuviéramos","detuviésemos"],p2:["detuvierais","detuvieseis"],p3:["detuvieran","detuviesen"]})
assert_TenseMood("detener","SubFut",{s1:"detuviere",s2:"detuvieres",s3:"detuviere",p1:"detuviéremos",p2:"detuviereis",p3:"detuvieren"})
assert_TenseMood("detener", "CmdPos", {s1:null,s2: "detén",s3: "detenga",p1: "detengamos",p2: "detened",p3: "detengan",vos: "detené"})
assert_TenseMood("detener", "CmdNeg", {s1:null,s2: "detengas",s3: "detenga",p1: "detengamos",p2: "detengáis",p3: "detengan"})

// o:ue
assert_Participles("dormir", { pres: "durmiendo", past: "dormido" })
assert_TenseMood("dormir", "IndPres", { s1: "duermo", s2: "duermes", s3: "duerme", p1: "dormimos", p2: "dormís", p3: "duermen", vos: "dormís" })
assert_TenseMood("dormir", "IndImp", { s1: "dormía", s2: "dormías", s3: "dormía", p1: "dormíamos", p2: "dormíais", p3: "dormían" })
assert_TenseMood("dormir", "IndPret", { s1: "dormí", s2: "dormiste", s3: "durmió", p1: "dormimos", p2: "dormisteis", p3: "durmieron" })
assert_TenseMood("dormir", "IndFut", { s1: "dormiré", s2: "dormirás", s3: "dormirá", p1: "dormiremos", p2: "dormiréis", p3: "dormirán" })
assert_TenseMood("dormir", "IndCond", { s1: "dormiría", s2: "dormirías", s3: "dormiría", p1: "dormiríamos", p2: "dormiríais", p3: "dormirían" })
assert_TenseMood("dormir", "SubPres", { s1: "duerma", s2: "duermas", s3: "duerma", p1: "durmamos", p2: "durmáis", p3: "duerman" })
assert_TenseMood("dormir", "SubImp", { s1: ["durmiera","durmiese"], s2: ["durmieras","durmieses"], s3: ["durmiera","durmiese"], p1: ["durmiéramos","durmiésemos"], p2: ["durmierais","durmieseis"], p3: ["durmieran","durmiesen"] })
assert_TenseMood("dormir","SubFut",{ s1:"durmiere", s2:"durmieres", s3:"durmiere", p1:"durmiéremos", p2:"durmiereis", p3:"durmieren" })
assert_TenseMood("dormir", "CmdPos", { s1: null, s2: "duerme", s3: "duerma", p1: "durmamos", p2: "dormid", p3: "duerman", vos: "dormí" })
assert_TenseMood("dormir", "CmdNeg", { s1: null, s2: "duermas", s3: "duerma", p1: "durmamos", p2: "durmáis", p3: "duerman" })

assert_Participles("elegir", { pres: "eligiendo", past: "elegido" })
assert_TenseMood("elegir","IndPres",{s1:"elijo",s2:"eliges",s3:"elige",p1:"elegimos",p2:"elegís",p3:"eligen",vos:"elegís"})
assert_TenseMood("elegir","IndImp",{s1:"elegía",s2:"elegías",s3:"elegía",p1:"elegíamos",p2:"elegíais",p3:"elegían"})
assert_TenseMood("elegir","IndPret",{s1:"elegí",s2:"elegiste",s3:"eligió",p1:"elegimos",p2:"elegisteis",p3:"eligieron"})
assert_TenseMood("elegir","IndFut",{s1:"elegiré",s2:"elegirás",s3:"elegirá",p1:"elegiremos",p2:"elegiréis",p3:"elegirán"})
assert_TenseMood("elegir","IndCond",{s1:"elegiría",s2:"elegirías",s3:"elegiría",p1:"elegiríamos",p2:"elegiríais",p3:"elegirían"})
assert_TenseMood("elegir","SubPres",{s1:"elija",s2:"elijas",s3:"elija",p1:"elijamos",p2:"elijáis",p3:"elijan"})
assert_TenseMood("elegir","SubImp",{s1:["eligiera","eligiese"],s2:["eligieras","eligieses"],s3:["eligiera","eligiese"],p1:["eligiéramos","eligiésemos"],p2:["eligierais","eligieseis"],p3:["eligieran","eligiesen"]})
assert_TenseMood("elegir","SubFut",{s1:"eligiere",s2:"eligieres",s3:"eligiere",p1:"eligiéremos",p2:"eligiereis",p3:"eligieren"})
assert_TenseMood("elegir","CmdPos",{s1:null,s2:"elige",s3:"elija",p1:"elijamos",p2:"elegid",p3:"elijan",vos:"elegí"})
assert_TenseMood("elegir","CmdNeg",{s1:null,s2:"elijas",s3:"elija",p1:"elijamos",p2:"elijáis",p3:"elijan"})

assert_Participles("erguir", { pres: "irguiendo", past: "erguido" })
assert_TenseMood("erguir", "IndPres", {s1:["irgo","yergo"],s2:["irgues","yergues"],s3:["irgue","yergue"],p1: "erguimos",p2: "erguís",p3:["irguen","yerguen"],vos: "erguís"})
assert_TenseMood("erguir", "IndImp", {s1: "erguía",s2: "erguías",s3: "erguía",p1: "erguíamos",p2: "erguíais",p3: "erguían"})
assert_TenseMood("erguir", "IndPret", {s1: "erguí",s2: "erguiste",s3: "irguió",p1: "erguimos",p2: "erguisteis",p3: "irguieron"})
assert_TenseMood("erguir", "IndFut", {s1: "erguiré",s2: "erguirás",s3: "erguirá",p1: "erguiremos",p2: "erguiréis",p3: "erguirán"})
assert_TenseMood("erguir", "IndCond", {s1: "erguiría",s2: "erguirías",s3: "erguiría",p1: "erguiríamos",p2: "erguiríais",p3: "erguirían"})
assert_TenseMood("erguir", "SubPres", {s1:["irga","yerga"],s2:["irgas","yergas"],s3:["irga","yerga"],p1:["irgamos","yergamos"],p2:["irgáis","yergáis"],p3:["irgan","yergan"],vos: "yergas"})
assert_TenseMood("erguir", "SubImp",{s1:["irguiera","irguiese"],s2:["irguieras","irguieses"],s3:["irguiera","irguiese"],p1:["irguiéramos","irguiésemos"],p2:["irguierais","irguieseis"],p3:["irguieran","irguiesen"]})
assert_TenseMood("erguir", "SubFut",{s1:"irguiere",s2:"irguieres",s3:"irguiere",p1:"irguiéremos",p2:"irguiereis",p3:"irguieren"})
assert_TenseMood("erguir", "CmdPos", {s1:null,s2:["irgue","yergue"],s3:["irga","yerga"],p1:["irgamos","yergamos"],p2: "erguid",p3:["irgan","yergan"],vos: "erguí"})
assert_TenseMood("erguir", "CmdNeg", {s1:null,s2:["irgas","yergas"],s3:["irga","yerga"],p1:["irgamos","yergamos"],p2:["irgáis","yergáis"],p3:["irgan","yergan"],vos: "yergas"})

assert_Participles("estar", { pres: "estando", past: "estado" })
assert_TenseMood("estar", "IndPres", {s1: "estoy", s2: "estás", s3: "está",         p1: "estamos", p2: "estáis", p3: "están" })
assert_TenseMood("estar", "IndImp",  {s1: "estaba", s2: "estabas", s3: "estaba",    p1: "estábamos", p2: "estabais", p3: "estaban"})
assert_TenseMood("estar", "IndPret", {s1: "estuve", s2: "estuviste", s3: "estuvo",  p1: "estuvimos", p2: "estuvisteis", p3: "estuvieron"})
assert_TenseMood("estar", "IndFut",  {s1: "estaré", s2: "estarás", s3: "estará",    p1: "estaremos", p2: "estaréis", p3: "estarán"})
assert_TenseMood("estar", "IndCond", {s1: "estaría", s2: "estarías", s3: "estaría", p1: "estaríamos", p2: "estaríais", p3: "estarían"})
assert_TenseMood("estar", "SubPres", {s1: "esté", s2: "estés", s3: "esté",          p1: "estemos", p2: "estéis", p3: "estén" })
assert_TenseMood("estar", "SubImp",{s1:["estuviera","estuviese"],s2:["estuvieras","estuvieses"],s3:["estuviera","estuviese"],p1:["estuviéramos","estuviésemos"],p2:["estuvierais","estuvieseis"],p3:["estuvieran","estuviesen"]})
assert_TenseMood("estar","SubFut",{s1:"estuviere",s2:"estuvieres",s3:"estuviere",p1:"estuviéremos",p2:"estuviereis",p3:"estuvieren"})
assert_TenseMood("estar", "CmdPos",  {s1: null,   s2: "está", s3: "esté",           p1: "estemos",  p2: "estad", p3: "estén" })
assert_TenseMood("estar", "CmdNeg",  {s1: null,   s2: "estés", s3: "esté",          p1: "estemos", p2: "estéis", p3: "estén" })

// conjugation_families["uir"]
assert_Participles("fluir", { pres: "fluyendo", past: "fluido" })
assert_TenseMood("fluir", "IndPres", {s1: "fluyo",s2: "fluyes",s3: "fluye",p1: "fluimos",p2: "fluis",p3: "fluyen",vos: "fluis"})
assert_TenseMood("fluir", "IndImp", {s1: "fluía",s2: "fluías",s3: "fluía",p1: "fluíamos",p2: "fluíais",p3: "fluían"})
assert_TenseMood("fluir", "IndPret", {s1: "flui",s2: "fluiste",s3: "fluyó",p1: "fluimos",p2: "fluisteis",p3: "fluyeron"})
assert_TenseMood("fluir", "IndFut", {s1: "fluiré",s2: "fluirás",s3: "fluirá",p1: "fluiremos",p2: "fluiréis",p3: "fluirán"})
assert_TenseMood("fluir", "IndCond", {s1: "fluiría",s2: "fluirías",s3: "fluiría",p1: "fluiríamos",p2: "fluiríais",p3: "fluirían"})
assert_TenseMood("fluir", "SubPres", {s1: "fluya",s2: "fluyas",s3: "fluya",p1: "fluyamos",p2: "fluyáis",p3: "fluyan"})
assert_TenseMood("fluir", "SubImp", {s1:["fluyera","fluyese"],s2:["fluyeras","fluyeses"],s3:["fluyera","fluyese"],p1:["fluyéramos","fluyésemos"],p2:["fluyerais","fluyeseis"],p3:["fluyeran","fluyesen"]})
assert_TenseMood("fluir","SubFut",{s1:"fluyere",s2:"fluyeres",s3:"fluyere",p1:"fluyéremos",p2:"fluyereis",p3:"fluyeren"})
assert_TenseMood("fluir", "CmdPos", {s1:null,s2: "fluye",s3: "fluya",p1: "fluyamos",p2: "fluid",p3: "fluyan",vos: "flui"})
assert_TenseMood("fluir", "CmdNeg", {s1:null,s2: "fluyas",s3: "fluya",p1: "fluyamos",p2: "fluyáis",p3: "fluyan"})

// based on "vaciar", but has changes to the accents
assert_Participles("guiar", { pres: "guiando", past: "guiado" })
assert_TenseMood("guiar", "IndPres", {s1: "guío",s2: "guías",s3: "guía",p1: "guiamos",p2: "guiais",p3: "guían",vos: "guias"})
assert_TenseMood("guiar", "IndImp", {s1: "guiaba",s2: "guiabas",s3: "guiaba",p1: "guiábamos",p2: "guiabais",p3: "guiaban"})
assert_TenseMood("guiar", "IndPret", {s1: "guie",s2: "guiaste",s3: "guio",p1: "guiamos",p2: "guiasteis",p3: "guiaron"})
assert_TenseMood("guiar", "IndFut", {s1: "guiaré",s2: "guiarás",s3: "guiará",p1: "guiaremos",p2: "guiaréis",p3: "guiarán"})
assert_TenseMood("guiar", "IndCond", {s1: "guiaría",s2: "guiarías",s3: "guiaría",p1: "guiaríamos",p2: "guiaríais",p3: "guiarían"})
assert_TenseMood("guiar", "SubPres", {s1: "guíe",s2: "guíes",s3: "guíe",p1: "guiemos",p2: "guieis",p3: "guíen"})
assert_TenseMood("guiar", "SubImp", {s1:["guiara","guiase"],s2:["guiaras","guiases"],s3:["guiara","guiase"],p1:["guiáramos","guiásemos"],p2:["guiarais","guiaseis"],p3:["guiaran","guiasen"]})
assert_TenseMood("guiar","SubFut",{s1:"guiare",s2:"guiares",s3:"guiare",p1:"guiáremos",p2:"guiareis",p3:"guiaren"})
assert_TenseMood("guiar", "CmdPos", {s1:null,s2: "guía",s3: "guíe",p1: "guiemos",p2: "guiad",p3: "guíen",vos: "guia"})
assert_TenseMood("guiar", "CmdNeg", {s1:null,s2: "guíes",s3: "guíe",p1: "guiemos",p2: "guieis",p3: "guíen"})

// NOTE: supports alternate form for s3 => impersonal: hay
assert_Participles("haber", { pres: "habiendo", past: "habido" })
assert_TenseMood("haber", "IndPres", {s1: "he", s2: "has", s3: ["hay", "ha"],     p1: "hemos", p2: "habéis", p3: "han"})
assert_TenseMood("haber", "IndImp",  {s1: "había", s2: "habías", s3: "había",     p1: "habíamos", p2: "habíais", p3: "habían"})
assert_TenseMood("haber", "IndPret", {s1: "hube", s2: "hubiste", s3: "hubo",      p1: "hubimos", p2: "hubisteis", p3: "hubieron"})
assert_TenseMood("haber", "IndFut",  {s1: "habré", s2: "habrás", s3: "habrá",     p1: "habremos", p2: "habréis", p3: "habrán"})
assert_TenseMood("haber", "IndCond", {s1: "habría", s2: "habrías", s3: "habría",  p1: "habríamos", p2: "habríais", p3: "habrían"})
assert_TenseMood("haber", "SubPres", {s1: "haya", s2: "hayas", s3: "haya",        p1: "hayamos", p2: "hayáis", p3: "hayan" })
assert_TenseMood("haber", "SubImp",{s1:["hubiera","hubiese"],s2:["hubieras","hubieses"],s3:["hubiera","hubiese"],p1:["hubiéramos","hubiésemos"],p2:["hubierais","hubieseis"],p3:["hubieran","hubiesen"]})
assert_TenseMood("haber","SubFut",{s1:"hubiere",s2:"hubieres",s3:"hubiere",p1:"hubiéremos",p2:"hubiereis",p3:"hubieren"})
assert_TenseMood("haber", "CmdPos",  {s1: null,   s2: ["habe", "he"], s3: "haya", p1: "hayamos",  p2: "habed", p3: "hayan" })
assert_TenseMood("haber", "CmdNeg",  {s1: null,   s2: "hayas", s3: "haya",        p1: "hayamos",  p2: "hayáis", p3: "hayan" })

assert_Participles("hacer", { pres: "haciendo", past: "hecho" })
assert_TenseMood("hacer", "IndPres", {s1: "hago", s2: "haces", s3: "hace",        p1: "hacemos", p2: "hacéis", p3: "hacen", vos: "hacés"})
assert_TenseMood("hacer", "IndImp",  {s1: "hacía", s2: "hacías", s3: "hacía",     p1: "hacíamos", p2: "hacíais", p3: "hacían"})
assert_TenseMood("hacer", "IndPret", {s1: "hice", s2: "hiciste", s3: "hizo",      p1: "hicimos", p2: "hicisteis", p3: "hicieron"})
assert_TenseMood("hacer", "IndFut",  {s1: "haré", s2: "harás", s3: "hará",        p1: "haremos", p2: "haréis", p3: "harán"})
assert_TenseMood("hacer", "IndCond", {s1: "haría", s2: "harías", s3: "haría",     p1: "haríamos", p2: "haríais", p3: "harían"})
assert_TenseMood("hacer", "SubPres", {s1: "haga", s2: "hagas", s3: "haga",        p1: "hagamos", p2: "hagáis", p3: "hagan" })
assert_TenseMood("hacer", "SubImp",{s1:["hiciera","hiciese"],s2:["hicieras","hicieses"],s3:["hiciera","hiciese"],p1:["hiciéramos","hiciésemos"],p2:["hicierais","hicieseis"],p3:["hicieran","hiciesen"]})
assert_TenseMood("hacer","SubFut",{s1:"hiciere",s2:"hicieres",s3:"hiciere",p1:"hiciéremos",p2:"hiciereis",p3:"hicieren"})
assert_TenseMood("hacer", "CmdPos",  {s1: null,   s2: "haz", s3: "haga",          p1: "hagamos",  p2: "haced", p3: "hagan", vos: "hacé" })
assert_TenseMood("hacer", "CmdNeg",  {s1: null,   s2: "hagas", s3: "haga",        p1: "hagamos",  p2: "hagáis", p3: "hagan" })

assert_Participles("huir", { pres: "huyendo", past: "huido" })
assert_TenseMood("huir", "IndPres", {s1: "huyo",s2: "huyes",s3: "huye",       p1: "huimos",p2: "huis",p3: "huyen",vos: "huis"})
assert_TenseMood("huir", "IndImp",  {s1: "huía",s2: "huías",s3: "huía",       p1: "huíamos",p2: "huíais",p3: "huían"})
assert_TenseMood("huir", "IndPret", {s1: "hui",s2: "huiste",s3: "huyó",       p1: "huimos",p2: "huisteis",p3: "huyeron"})
assert_TenseMood("huir", "IndFut",  {s1: "huiré",s2: "huirás",s3: "huirá",    p1: "huiremos",p2: "huiréis",p3: "huirán"})
assert_TenseMood("huir", "IndCond", {s1: "huiría",s2: "huirías",s3: "huiría", p1: "huiríamos",p2: "huiríais",p3: "huirían"})
assert_TenseMood("huir", "SubPres", {s1: "huya",s2: "huyas",s3: "huya",       p1: "huyamos",p2: "huyáis",p3: "huyan"})
assert_TenseMood("huir","SubImp",{s1:["huyera","huyese"],s2:["huyeras","huyeses"],s3:["huyera","huyese"],p1:["huyéramos","huyésemos"],p2:["huyerais","huyeseis"],p3:["huyeran","huyesen"]})
assert_TenseMood("huir","SubFut",{s1:"huyere",s2:"huyeres",s3:"huyere",p1:"huyéremos",p2:"huyereis",p3:"huyeren"})
assert_TenseMood("huir", "CmdPos",  {s1:null,s2: "huye",s3: "huya",          p1: "huyamos",p2: "huid",p3: "huyan",vos: "hui"})
assert_TenseMood("huir", "CmdNeg",  {s1:null,s2: "huyas",s3: "huya",         p1: "huyamos",p2: "huyáis",p3: "huyan"})

assert_Participles("ir", { pres: "yendo", past: "ido" })
assert_TenseMood("ir", "IndPres", {s1: "voy", s2: "vas", s3: "va",                p1: "vamos", p2: "vais", p3: "van"})
assert_TenseMood("ir", "IndImp",  {s1: "iba", s2: "ibas", s3: "iba",              p1: "íbamos", p2: "ibais", p3: "iban"})
assert_TenseMood("ir", "IndPret", {s1: "fui", s2: "fuiste", s3: "fue",            p1: "fuimos", p2: "fuisteis", p3: "fueron"})
assert_TenseMood("ir", "IndFut",  {s1: "iré", s2: "irás", s3: "irá",              p1: "iremos", p2: "iréis", p3: "irán"})
assert_TenseMood("ir", "IndCond", {s1: "iría", s2: "irías", s3: "iría",           p1: "iríamos", p2: "iríais", p3: "irían"})
assert_TenseMood("ir", "SubPres", {s1: "vaya", s2: "vayas", s3: "vaya",           p1: "vayamos", p2: "vayáis", p3: "vayan" })
assert_TenseMood("ir", "SubImp",{s1:["fuera","fuese"],s2:["fueras","fueses"],s3:["fuera","fuese"],p1:["fuéramos","fuésemos"],p2:["fuerais","fueseis"],p3:["fueran","fuesen"]})
assert_TenseMood("ir","SubFut",{s1:"fuere",s2:"fueres",s3:"fuere",p1:"fuéremos",p2:"fuereis",p3:"fueren"})
assert_TenseMood("ir", "CmdPos",  {s1: null, s2: "ve", s3: "vaya",                p1: ["vayamos", "vamos"], p2: "id", p3: "vayan", vos: "andá"})
assert_TenseMood("ir", "CmdNeg",  {s1: null, s2: "vayas", s3: "vaya",             p1: "vayamos", p2: "vayáis", p3: "vayan"})

assert_Participles("jugar", { pres: "jugando", past: "jugado" })
assert_TenseMood("jugar", "IndPres", {s1: "juego",s2: "juegas",s3: "juega",p1: "jugamos",p2: "jugáis",p3: "juegan",vos: "jugás"})
assert_TenseMood("jugar", "IndImp", {s1: "jugaba",s2: "jugabas",s3: "jugaba",p1: "jugábamos",p2: "jugabais",p3: "jugaban"})
assert_TenseMood("jugar", "IndPret", {s1: "jugué",s2: "jugaste",s3: "jugó",p1: "jugamos",p2: "jugasteis",p3: "jugaron"})
assert_TenseMood("jugar", "IndFut", {s1: "jugaré",s2: "jugarás",s3: "jugará",p1: "jugaremos",p2: "jugaréis",p3: "jugarán"})
assert_TenseMood("jugar", "IndCond", {s1: "jugaría",s2: "jugarías",s3: "jugaría",p1: "jugaríamos",p2: "jugaríais",p3: "jugarían"})
assert_TenseMood("jugar", "SubPres", {s1: "juegue",s2: "juegues",s3: "juegue",p1: "juguemos",p2: "juguéis",p3: "jueguen"})
assert_TenseMood("jugar", "SubImp",{s1:["jugara","jugase"],s2:["jugaras","jugases"],s3:["jugara","jugase"],p1:["jugáramos","jugásemos"],p2:["jugarais","jugaseis"],p3:["jugaran","jugasen"]})
assert_TenseMood("jugar","SubFut",{s1:"jugare",s2:"jugares",s3:"jugare",p1:"jugáremos",p2:"jugareis",p3:"jugaren"})
assert_TenseMood("jugar", "CmdPos", {s1:null,s2: "juega",s3: "juegue",p1: "juguemos",p2: "jugad",p3: "jueguen",vos: "jugá"})
assert_TenseMood("jugar", "CmdNeg", {s1:null,s2: "juegues",s3: "juegue",p1: "juguemos",p2: "juguéis",p3: "jueguen"})

assert_Participles("leer", { pres: "leyendo", past: "leído" })
assert_TenseMood("leer", "IndPres", {s1: "leo", s2: "lees", s3: "lee",            p1: "leemos", p2: "leéis", p3: "leen", vos: "leés"})
assert_TenseMood("leer", "IndImp", {s1: "leía", s2: "leías", s3: "leía",          p1: "leíamos", p2: "leíais", p3: "leían"})
assert_TenseMood("leer", "IndPret", {s1: "leí", s2: "leíste", s3: "leyó",         p1: "leímos", p2: "leísteis", p3: "leyeron"})
assert_TenseMood("leer", "IndFut", {s1: "leeré", s2: "leerás", s3: "leerá",       p1: "leeremos", p2: "leeréis", p3: "leerán"})
assert_TenseMood("leer", "IndCond", {s1: "leería", s2: "leerías", s3: "leería",   p1: "leeríamos", p2: "leeríais", p3: "leerían"})
assert_TenseMood("leer", "SubPres", {s1: "lea", s2: "leas", s3: "lea",            p1: "leamos", p2: "leáis", p3: "lean"})
assert_TenseMood("leer", "SubImp",{s1:["leyera","leyese"],s2:["leyeras","leyeses"],s3:["leyera","leyese"],p1:["leyéramos","leyésemos"],p2:["leyerais","leyeseis"],p3:["leyeran","leyesen"]})
assert_TenseMood("leer", "SubFut",{s1:"leyere",s2:"leyeres",s3:"leyere",p1:"leyéremos",p2:"leyereis",p3:"leyeren"})
assert_TenseMood("leer", "CmdPos", {s1: null, s2: "lee", s3: "lea",               p1: "leamos", p2: "leed", p3: "lean", vos: "leé"})
assert_TenseMood("leer", "CmdNeg", {s1: null, s2: "leas", s3: "lea",              p1: "leamos", p2: "leáis", p3: "lean"})

assert_Participles("llegar", { pres: "llegando", past: "llegado" })
assert_TenseMood("llegar", "IndPres", {s1: "llego", s2: "llegas", s3: "llega", p1: "llegamos", p2: "llegáis", p3: "llegan", vos: "llegás"})
assert_TenseMood("llegar", "IndImp", {s1:"llegaba",s2:"llegabas",s3:"llegaba",p1:"llegábamos",p2:"llegabais",p3:"llegaban"})
assert_TenseMood("llegar", "IndPret", {s1: "llegué", s2: "llegaste", s3: "llegó",  p1: "llegamos", p2: "llegasteis", p3: "llegaron"})
assert_TenseMood("llegar", "IndFut", {s1:"llegaré",s2:"llegarás",s3:"llegará",p1:"llegaremos",p2:"llegaréis",p3:"llegarán"})
assert_TenseMood("llegar", "IndCond", {s1:"llegaría",s2:"llegarías",s3:"llegaría",p1:"llegaríamos",p2:"llegaríais",p3:"llegarían"})
assert_TenseMood("llegar", "SubPres", {s1:"llegue",s2:"llegues",s3:"llegue",p1:"lleguemos",p2:"lleguéis",p3:"lleguen"})
assert_TenseMood("llegar","SubImp",{s1:["llegara","llegase"],s2:["llegaras","llegases"],s3:["llegara","llegase"],p1:["llegáramos","llegásemos"],p2:["llegarais","llegaseis"],p3:["llegaran","llegasen"]})
assert_TenseMood("llegar","SubFut",{s1:"llegare",s2:"llegares",s3:"llegare",p1:"llegáremos",p2:"llegareis",p3:"llegaren"})
assert_TenseMood("llegar", "CmdPos", {s1:null,s2:"llega",s3:"llegue",p1:"lleguemos",p2:"llegad",p3:"lleguen",vos:"llegá"})
assert_TenseMood("llegar", "CmdNeg", {s1:null,s2:"llegues",s3:"llegue",p1:"lleguemos",p2:"lleguéis",p3:"lleguen"})

assert_Participles("oír", { pres: "oyendo", past: "oído" })
assert_TenseMood("oír", "IndPres", {s1: "oigo",s2: "oyes",s3: "oye",p1: "oímos",p2: "oís",p3: "oyen",vos: "oís"})
assert_TenseMood("oír", "IndImp", {s1: "oía",s2: "oías",s3: "oía",p1: "oíamos",p2: "oíais",p3: "oían"})
assert_TenseMood("oír", "IndPret", {s1: "oí",s2: "oíste",s3: "oyó",p1: "oímos",p2: "oísteis",p3: "oyeron"})
assert_TenseMood("oír", "IndFut", {s1: "oiré",s2: "oirás",s3: "oirá",p1: "oiremos",p2: "oiréis",p3: "oirán"})
assert_TenseMood("oír", "IndCond", {s1: "oiría",s2: "oirías",s3: "oiría",p1: "oiríamos",p2: "oiríais",p3: "oirían"})
assert_TenseMood("oír", "SubPres", {s1: "oiga",s2: "oigas",s3: "oiga",p1: "oigamos",p2: "oigáis",p3: "oigan"})
assert_TenseMood("oír","SubImp",{s1:["oyera","oyese"],s2:["oyeras","oyeses"],s3:["oyera","oyese"],p1:["oyéramos","oyésemos"],p2:["oyerais","oyeseis"],p3:["oyeran","oyesen"]})
assert_TenseMood("oír","SubFut",{s1:"oyere",s2:"oyeres",s3:"oyere",p1:"oyéremos",p2:"oyereis",p3:"oyeren"})
assert_TenseMood("oír", "CmdPos", {s1:null,s2: "oye",s3: "oiga",p1: "oigamos",p2: "oíd",p3: "oigan",vos: "oí"})
assert_TenseMood("oír", "CmdNeg", {s1:null,s2: "oigas",s3: "oiga",p1: "oigamos",p2: "oigáis",p3: "oigan"})

assert_Participles("oponer", { pres: "oponiendo", past: "opuesto" })
assert_TenseMood("oponer", "IndPres", {s1: "opongo", s2: "opones", s3: "opone", p1: "oponemos", p2: "oponéis", p3: "oponen", vos: "oponés"})
assert_TenseMood("oponer", "IndImp", {s1: "oponía", s2: "oponías", s3: "oponía", p1: "oponíamos", p2: "oponíais", p3: "oponían"})
assert_TenseMood("oponer", "IndPret", {s1: "opuse", s2: "opusiste", s3: "opuso", p1: "opusimos", p2: "opusisteis", p3: "opusieron"})
assert_TenseMood("oponer", "IndFut", {s1: "opondré", s2: "opondrás", s3: "opondrá", p1: "opondremos", p2: "opondréis", p3: "opondrán"})
assert_TenseMood("oponer", "IndCond", {s1: "opondría", s2: "opondrías", s3: "opondría", p1: "opondríamos", p2: "opondríais", p3: "opondrían"})
assert_TenseMood("oponer", "SubPres", {s1: "oponga", s2: "opongas", s3: "oponga", p1: "opongamos", p2: "opongáis", p3: "opongan"})
assert_TenseMood("oponer","SubImp",{s1:["opusiera","opusiese"],s2:["opusieras","opusieses"],s3:["opusiera","opusiese"],p1:["opusiéramos","opusiésemos"],p2:["opusierais","opusieseis"],p3:["opusieran","opusiesen"]})
assert_TenseMood("oponer","SubFut",{s1:"opusiere",s2:"opusieres",s3:"opusiere",p1:"opusiéremos",p2:"opusiereis",p3:"opusieren"})
assert_TenseMood("oponer", "CmdPos", {s1: null, s2: "opón", s3: "oponga", p1: "opongamos", p2: "oponed", p3: "opongan", vos: "oponé"})
assert_TenseMood("oponer", "CmdNeg", {s1: null, s2: "opongas", s3: "oponga", p1: "opongamos", p2: "opongáis", p3: "opongan"})

assert_Participles("poder", { pres: "pudiendo", past: "podido" })
assert_TenseMood("poder", "IndPres", {s1: "puedo",s2: "puedes",s3: "puede",p1: "podemos",p2: "podéis",p3: "pueden",vos: "podés"})
assert_TenseMood("poder", "IndImp", {s1: "podía",s2: "podías",s3: "podía",p1: "podíamos",p2: "podíais",p3: "podían"})
assert_TenseMood("poder", "IndPret", {s1: "pude",s2: "pudiste",s3: "pudo",p1: "pudimos",p2: "pudisteis",p3: "pudieron"})
assert_TenseMood("poder", "IndFut", {s1: "podré",s2: "podrás",s3: "podrá",p1: "podremos",p2: "podréis",p3: "podrán"})
assert_TenseMood("poder", "IndCond", {s1: "podría",s2: "podrías",s3: "podría",p1: "podríamos",p2: "podríais",p3: "podrían"})
assert_TenseMood("poder", "SubPres", {s1: "pueda",s2: "puedas",s3: "pueda",p1: "podamos",p2: "podáis",p3: "puedan"})
assert_TenseMood("poder","SubImp",{s1:["pudiera","pudiese"],s2:["pudieras","pudieses"],s3:["pudiera","pudiese"],p1:["pudiéramos","pudiésemos"],p2:["pudierais","pudieseis"],p3:["pudieran","pudiesen"]})
assert_TenseMood("poder","SubFut",{s1:"pudiere",s2:"pudieres",s3:"pudiere",p1:"pudiéremos",p2:"pudiereis",p3:"pudieren"})
assert_TenseMood("poder", "CmdPos", {s1:null,s2: "puede",s3: "pueda",p1: "podamos",p2: "poded",p3: "puedan",vos: "podé"})
assert_TenseMood("poder", "CmdNeg", {s1:null,s2: "puedas",s3: "pueda",p1: "podamos",p2: "podáis",p3: "puedan"})

assert_Participles("poner", { pres: "poniendo", past: "puesto" })
assert_TenseMood("poner", "IndPres", {s1: "pongo",s2: "pones",s3: "pone",p1: "ponemos",p2: "ponéis",p3: "ponen",vos: "ponés"})
assert_TenseMood("poner", "IndImp", {s1: "ponía",s2: "ponías",s3: "ponía",p1: "poníamos",p2: "poníais",p3: "ponían"})
assert_TenseMood("poner", "IndPret", {s1: "puse",s2: "pusiste",s3: "puso",p1: "pusimos",p2: "pusisteis",p3: "pusieron"})
assert_TenseMood("poner", "IndFut", {s1: "pondré",s2: "pondrás",s3: "pondrá",p1: "pondremos",p2: "pondréis",p3: "pondrán"})
assert_TenseMood("poner", "IndCond", {s1: "pondría",s2: "pondrías",s3: "pondría",p1: "pondríamos",p2: "pondríais",p3: "pondrían"})
assert_TenseMood("poner", "SubPres", {s1: "ponga",s2: "pongas",s3: "ponga",p1: "pongamos",p2: "pongáis",p3: "pongan"})
assert_TenseMood("poner","SubImp",{s1:["pusiera","pusiese"],s2:["pusieras","pusieses"],s3:["pusiera","pusiese"],p1:["pusiéramos","pusiésemos"],p2:["pusierais","pusieseis"],p3:["pusieran","pusiesen"]})
assert_TenseMood("poner","SubFut",{s1:"pusiere",s2:"pusieres",s3:"pusiere",p1:"pusiéremos",p2:"pusiereis",p3:"pusieren"})
assert_TenseMood("poner", "CmdPos", {s1:null,s2: "pon",s3: "ponga",p1: "pongamos",p2: "poned",p3: "pongan",vos: "poné"})
// add regionalism such as: Central American spelling of vos: pongás
assert_TenseMood("poner", "CmdNeg", {s1:null,s2: "pongas",s3: "ponga",p1: "pongamos",p2: "pongáis",p3: "pongan"})

// "prever", a prefix "pre" + a 3-char base infinitive "ver"
assert_Participles("prever", { pres: "previendo", past: "previsto" })
assert_TenseMood("prever", "IndPres", {s1: "preveo",s2: "prevés",s3: "prevé",p1: "prevemos",p2: "prevéis",p3: "prevén"})
assert_TenseMood("prever", "IndImp", {s1: "preveía",s2: "preveías",s3: "preveía",p1: "preveíamos",p2: "preveíais",p3: "preveían"})
assert_TenseMood("prever", "IndPret", {s1: "preví",s2: "previste",s3: "previó",p1: "previmos",p2: "previsteis",p3: "previeron"})
assert_TenseMood("prever", "IndFut", {s1: "preveré",s2: "preverás",s3: "preverá",p1: "preveremos",p2: "preveréis",p3: "preverán"})
assert_TenseMood("prever", "IndCond", {s1: "prevería",s2: "preverías",s3: "prevería",p1: "preveríamos",p2: "preveríais",p3: "preverían"})
assert_TenseMood("prever", "SubPres", {s1: "prevea",s2: "preveas",s3: "prevea",p1: "preveamos",p2: "preveáis",p3: "prevean"})
assert_TenseMood("prever", "SubImp", {s1:["previera","previese"],s2:["previeras","previeses"],s3:["previera","previese"],p1:["previéramos","previésemos"],p2:["previerais","previeseis"],p3:["previeran","previesen"]})
assert_TenseMood("prever","SubFut",{s1:"previere",s2:"previeres",s3:"previere",p1:"previéremos",p2:"previereis",p3:"previeren"})
assert_TenseMood("prever", "CmdPos", {s1:null,s2: "prevé",s3: "prevea",p1: "preveamos",p2: "preved",p3: "prevean"})
assert_TenseMood("prever", "CmdNeg", {s1:null,s2: "preveas",s3: "prevea",p1: "preveamos",p2: "preveáis",p3: "prevean"})

assert_Participles("querer", { pres: "queriendo", past: "querido" })
assert_TenseMood("querer", "IndPres", {s1: "quiero",s2: "quieres",s3: "quiere",p1: "queremos",p2: "queréis",p3: "quieren",vos: "querés"})
assert_TenseMood("querer", "IndImp",  {s1: "quería",s2: "querías",s3: "quería",p1: "queríamos",p2: "queríais",p3: "querían"})
assert_TenseMood("querer", "IndPret", {s1: "quise",s2: "quisiste",s3: "quiso",p1: "quisimos",p2: "quisisteis",p3: "quisieron"})
assert_TenseMood("querer", "IndFut",  {s1: "querré",s2: "querrás",s3: "querrá",p1: "querremos",p2: "querréis",p3: "querrán"})
assert_TenseMood("querer", "IndCond", {s1: "querría",s2: "querrías",s3: "querría",p1: "querríamos",p2: "querríais",p3: "querrían"})
assert_TenseMood("querer", "SubPres", {s1: "quiera",s2: "quieras",s3: "quiera",p1: "queramos",p2: "queráis",p3: "quieran"})
assert_TenseMood("querer","SubImp",{s1:["quisiera","quisiese"],s2:["quisieras","quisieses"],s3:["quisiera","quisiese"],p1:["quisiéramos","quisiésemos"],p2:["quisierais","quisieseis"],p3:["quisieran","quisiesen"]})
assert_TenseMood("querer","SubFut",{s1:"quisiere",s2:"quisieres",s3:"quisiere",p1:"quisiéremos",p2:"quisiereis",p3:"quisieren"})
assert_TenseMood("querer", "CmdPos",  {s1:null,s2: "quiere",s3: "quiera",p1: "queramos",p2: "quered",p3: "quieran",vos: "queré"})
assert_TenseMood("querer", "CmdNeg",  {s1:null,s2: "quieras",s3: "quiera",p1: "queramos",p2: "queráis",p3: "quieran"})

assert_Participles("reunir", { pres: "reuniendo", past: "reunido" })
assert_TenseMood("reunir", "IndPres", {s1: "reúno", s2: "reúnes", s3: "reúne", p1: "reunimos", p2: "reunís", p3: "reúnen", vos: "reunís"})
assert_TenseMood("reunir", "IndImp",  {s1: "reunía", s2: "reunías", s3: "reunía", p1: "reuníamos", p2: "reuníais", p3: "reunían"})
assert_TenseMood("reunir", "IndPret", {s1: "reuní", s2: "reuniste", s3: "reunió", p1: "reunimos", p2: "reunisteis", p3: "reunieron"})
assert_TenseMood("reunir", "IndFut",  {s1: "reuniré", s2: "reunirás", s3: "reunirá", p1: "reuniremos", p2: "reuniréis", p3: "reunirán"})
assert_TenseMood("reunir", "IndCond", {s1: "reuniría", s2: "reunirías", s3: "reuniría", p1: "reuniríamos", p2: "reuniríais", p3: "reunirían"})
assert_TenseMood("reunir", "SubPres", {s1: "reúna", s2: "reúnas", s3: "reúna", p1: "reunamos", p2: "reunáis", p3: "reúnan"})
assert_TenseMood("reunir","SubImp",{s1:["reuniera","reuniese"],s2:["reunieras","reunieses"],s3:["reuniera","reuniese"],p1:["reuniéramos","reuniésemos"],p2:["reunierais","reunieseis"],p3:["reunieran","reuniesen"]})
assert_TenseMood("reunir","SubFut",{s1:"reuniere",s2:"reunieres",s3:"reuniere",p1:"reuniéremos",p2:"reuniereis",p3:"reunieren"})
assert_TenseMood("reunir", "CmdPos",  {s1:null, s2: "reúne", s3: "reúna", p1: "reunamos", p2: "reunid", p3: "reúnan", vos: "reuní"})
assert_TenseMood("reunir", "CmdNeg",  {s1:null, s2: "reúnas", s3: "reúna", p1: "reunamos", p2: "reunáis", p3: "reúnan"})

assert_Participles("saber", { pres: "sabiendo", past: "sabido" })
assert_TenseMood("saber", "IndPres", {s1: "sé",s2: "sabes",s3: "sabe",p1: "sabemos",p2: "sabéis",p3: "saben",vos: "sabés"})
assert_TenseMood("saber", "IndImp", {s1: "sabía",s2: "sabías",s3: "sabía",p1: "sabíamos",p2: "sabíais",p3: "sabían"})
assert_TenseMood("saber", "IndPret", {s1: "supe",s2: "supiste",s3: "supo",p1: "supimos",p2: "supisteis",p3: "supieron"})
assert_TenseMood("saber", "IndFut", {s1: "sabré",s2: "sabrás",s3: "sabrá",p1: "sabremos",p2: "sabréis",p3: "sabrán"})
assert_TenseMood("saber", "IndCond", {s1: "sabría",s2: "sabrías",s3: "sabría",p1: "sabríamos",p2: "sabríais",p3: "sabrían"})
assert_TenseMood("saber", "SubPres", {s1: "sepa",s2: "sepas",s3: "sepa",p1: "sepamos",p2: "sepáis",p3: "sepan"})
assert_TenseMood("saber", "SubImp",{s1:["supiera","supiese"],s2:["supieras","supieses"],s3:["supiera","supiese"],p1:["supiéramos","supiésemos"],p2:["supierais","supieseis"],p3:["supieran","supiesen"]})
assert_TenseMood("saber", "SubFut",{s1:"supiere",s2:"supieres",s3:"supiere",p1:"supiéremos",p2:"supiereis",p3:"supieren"})
assert_TenseMood("saber", "CmdPos", {s1:null,s2: "sabe",s3: "sepa",p1: "sepamos",p2: "sabed",p3: "sepan",vos: "sabé"})
assert_TenseMood("saber", "CmdNeg", {s1:null,s2: "sepas",s3: "sepa",p1: "sepamos",p2: "sepáis",p3: "sepan"})

assert_Participles("sacar", { pres: "sacando", past: "sacado" })
assert_TenseMood("sacar", "IndPres", {s1: "saco",s2: "sacas",s3: "saca",p1: "sacamos",p2: "sacáis",p3: "sacan",vos: "sacás"})
assert_TenseMood("sacar", "IndImp",  {s1: "sacaba",s2: "sacabas",s3: "sacaba",p1: "sacábamos",p2: "sacabais",p3: "sacaban"})
assert_TenseMood("sacar", "IndPret", {s1: "saqué",s2: "sacaste",s3: "sacó",p1: "sacamos",p2: "sacasteis",p3: "sacaron"})
assert_TenseMood("sacar", "IndFut",  {s1: "sacaré",s2: "sacarás",s3: "sacará",p1: "sacaremos",p2: "sacaréis",p3: "sacarán"})
assert_TenseMood("sacar", "IndCond", {s1: "sacaría",s2: "sacarías",s3: "sacaría",p1: "sacaríamos",p2: "sacaríais",p3: "sacarían"})
assert_TenseMood("sacar", "SubPres", {s1: "saque",s2: "saques",s3: "saque",p1: "saquemos",p2: "saquéis",p3: "saquen"})
assert_TenseMood("sacar","SubImp",{s1:["sacara","sacase"],s2:["sacaras","sacases"],s3:["sacara","sacase"],p1:["sacáramos","sacásemos"],p2:["sacarais","sacaseis"],p3:["sacaran","sacasen"]})
assert_TenseMood("sacar","SubFut",{s1:"sacare",s2:"sacares",s3:"sacare",p1:"sacáremos",p2:"sacareis",p3:"sacaren"})
assert_TenseMood("sacar", "CmdPos",  {s1:null,s2: "saca",s3: "saque",p1: "saquemos",p2: "sacad",p3: "saquen",vos: "sacá"})
assert_TenseMood("sacar", "CmdNeg",  {s1:null,s2: "saques",s3: "saque",p1: "saquemos",p2: "saquéis",p3: "saquen"})

assert_Participles("salir", { pres: "saliendo", past: "salido" })
assert_TenseMood("salir", "IndPres", {s1: "salgo",s2: "sales",s3: "sale",p1: "salimos",p2: "salís",p3: "salen",vos: "salís"})
assert_TenseMood("salir", "IndImp", {s1: "salía",s2: "salías",s3: "salía",p1: "salíamos",p2: "salíais",p3: "salían"})
assert_TenseMood("salir", "IndPret", {s1: "salí",s2: "saliste",s3: "salió",p1: "salimos",p2: "salisteis",p3: "salieron"})
assert_TenseMood("salir", "IndFut", {s1: "saldré",s2: "saldrás",s3: "saldrá",p1: "saldremos",p2: "saldréis",p3: "saldrán"})
assert_TenseMood("salir", "IndCond", {s1: "saldría",s2: "saldrías",s3: "saldría",p1: "saldríamos",p2: "saldríais",p3: "saldrían"})
assert_TenseMood("salir", "SubPres", {s1: "salga",s2: "salgas",s3: "salga",p1: "salgamos",p2: "salgáis",p3: "salgan"})
assert_TenseMood("salir","SubImp",{s1:["saliera","saliese"],s2:["salieras","salieses"],s3:["saliera","saliese"],p1:["saliéramos","saliésemos"],p2:["salierais","salieseis"],p3:["salieran","saliesen"]})
assert_TenseMood("salir","SubFut",{s1:"saliere",s2:"salieres",s3:"saliere",p1:"saliéremos",p2:"saliereis",p3:"salieren"})
assert_TenseMood("salir", "CmdPos", {s1:null,s2: "sal",s3: "salga",p1: "salgamos",p2: "salid",p3: "salgan",vos: "salí"})
assert_TenseMood("salir", "CmdNeg", {s1:null,s2: "salgas",s3: "salga",p1: "salgamos",p2: "salgáis",p3: "salgan"})

assert_Participles("seguir", { pres: "siguiendo", past: "seguido" })
assert_TenseMood("seguir", "IndPres", {s1: "sigo",s2: "sigues",s3: "sigue",p1: "seguimos",p2: "seguís",p3: "siguen",vos: "seguís"})
assert_TenseMood("seguir", "IndImp", {s1: "seguía",s2: "seguías",s3: "seguía",p1: "seguíamos",p2: "seguíais",p3: "seguían"})
assert_TenseMood("seguir", "IndPret", {s1: "seguí",s2: "seguiste",s3: "siguió",p1: "seguimos",p2: "seguisteis",p3: "siguieron"})
assert_TenseMood("seguir", "IndFut", {s1: "seguiré",s2: "seguirás",s3: "seguirá",p1: "seguiremos",p2: "seguiréis",p3: "seguirán"})
assert_TenseMood("seguir", "IndCond", {s1: "seguiría",s2: "seguirías",s3: "seguiría",p1: "seguiríamos",p2: "seguiríais",p3: "seguirían"})
assert_TenseMood("seguir", "SubPres", {s1: "siga",s2: "sigas",s3: "siga",p1: "sigamos",p2: "sigáis",p3: "sigan"})
assert_TenseMood("seguir","SubImp",{s1:["siguiera","siguiese"],s2:["siguieras","siguieses"],s3:["siguiera","siguiese"],p1:["siguiéramos","siguiésemos"],p2:["siguierais","siguieseis"],p3:["siguieran","siguiesen"]})
assert_TenseMood("seguir","SubFut",{s1:"siguiere",s2:"siguieres",s3:"siguiere",p1:"siguiéremos",p2:"siguiereis",p3:"siguieren"})
assert_TenseMood("seguir", "CmdPos", {s1:null,s2: "sigue",s3: "siga",p1: "sigamos",p2: "seguid",p3: "sigan",vos: "seguí"})
assert_TenseMood("seguir", "CmdNeg", {s1:null,s2: "sigas",s3: "siga",p1: "sigamos",p2: "sigáis",p3: "sigan"})

assert_Participles("ser", { pres: "siendo", past: "sido" })
assert_TenseMood("ser", "IndPres", {s1: "soy",s2: "eres",s3: "es",p1: "somos",p2: "sois",p3: "son",vos: "sos"})
assert_TenseMood("ser", "IndImp", {s1: "era",s2: "eras",s3: "era",p1: "éramos",p2: "erais",p3: "eran"})
assert_TenseMood("ser", "IndPret", {s1: "fui",s2: "fuiste",s3: "fue",p1: "fuimos",p2: "fuisteis",p3: "fueron"})
assert_TenseMood("ser", "IndFut",  {s1: "seré",s2: "serás",s3: "será",p1: "seremos",p2: "seréis",p3: "serán"})
assert_TenseMood("ser", "IndCond", {s1: "sería",s2: "serías",s3: "sería",p1: "seríamos",p2: "seríais",p3: "serían"})
assert_TenseMood("ser", "SubPres", {s1: "sea",s2: "seas",s3: "sea",p1: "seamos",p2: "seáis",p3: "sean"})
assert_TenseMood("ser","SubImp",{s1:["fuera","fuese"],s2:["fueras","fueses"],s3:["fuera","fuese"],p1:["fuéramos","fuésemos"],p2:["fuerais","fueseis"],p3:["fueran","fuesen"]})
assert_TenseMood("ser","SubFut",{s1:"fuere",s2:"fueres",s3:"fuere",p1:"fuéremos",p2:"fuereis",p3:"fueren"})
assert_TenseMood("ser", "CmdPos",  {s1:null,s2: "sé",s3: "sea",p1: "seamos",p2: "sed",p3: "sean",vos: "sé"})
assert_TenseMood("ser", "CmdNeg",  {s1:null,s2: "seas",s3: "sea",p1: "seamos",p2: "seáis",p3: "sean"})

assert_Participles("tener", { pres: "teniendo", past: "tenido" })
assert_TenseMood("tener", "IndPres", {s1: "tengo",s2: "tienes",s3: "tiene",p1: "tenemos",p2: "tenéis",p3: "tienen",vos: "tenés"})
assert_TenseMood("tener", "IndImp", {s1: "tenía",s2: "tenías",s3: "tenía",p1: "teníamos",p2: "teníais",p3: "tenían"})
assert_TenseMood("tener", "IndPret", {s1: "tuve",s2: "tuviste",s3: "tuvo",p1: "tuvimos",p2: "tuvisteis",p3: "tuvieron"})
assert_TenseMood("tener", "IndFut",  {s1: "tendré",s2: "tendrás",s3: "tendrá",p1: "tendremos",p2: "tendréis",p3: "tendrán"})
assert_TenseMood("tener", "IndCond", {s1: "tendría",s2: "tendrías",s3: "tendría",p1: "tendríamos",p2: "tendríais",p3: "tendrían"})
assert_TenseMood("tener", "SubPres", {s1: "tenga",s2: "tengas",s3: "tenga",p1: "tengamos",p2: "tengáis",p3: "tengan"})
assert_TenseMood("tener","SubImp",{s1:["tuviera","tuviese"],s2:["tuvieras","tuvieses"],s3:["tuviera","tuviese"],p1:["tuviéramos","tuviésemos"],p2:["tuvierais","tuvieseis"],p3:["tuvieran","tuviesen"]})
assert_TenseMood("tener","SubFut",{s1:"tuviere",s2:"tuvieres",s3:"tuviere",p1:"tuviéremos",p2:"tuviereis",p3:"tuvieren"})
assert_TenseMood("tener", "CmdPos",  {s1:null,s2: "ten",s3: "tenga",p1: "tengamos",p2: "tened",p3: "tengan",vos: "tené"})
assert_TenseMood("tener", "CmdNeg",  {s1:null,s2: "tengas",s3: "tenga",p1: "tengamos",p2: "tengáis",p3: "tengan"})

assert_Participles("traer", { pres: "trayendo", past: "traído" })
assert_TenseMood("traer", "IndPres", {s1: "traigo",s2: "traes",s3: "trae",p1: "traemos",p2: "traéis",p3: "traen",vos: "traés"})
assert_TenseMood("traer", "IndImp", {s1: "traía",s2: "traías",s3: "traía",p1: "traíamos",p2: "traíais",p3: "traían"})
assert_TenseMood("traer", "IndPret", {s1: "traje",s2: "trajiste",s3: "trajo",p1: "trajimos",p2: "trajisteis",p3: "trajeron"})
assert_TenseMood("traer", "IndFut", {s1: "traeré",s2: "traerás",s3: "traerá",p1: "traeremos",p2: "traeréis",p3: "traerán"})
assert_TenseMood("traer", "IndCond", {s1: "traería",s2: "traerías",s3: "traería",p1: "traeríamos",p2: "traeríais",p3: "traerían"})
assert_TenseMood("traer", "SubPres", {s1: "traiga",s2: "traigas",s3: "traiga",p1: "traigamos",p2: "traigáis",p3: "traigan"})
assert_TenseMood("traer","SubImp",{s1:["trajera","trajese"],s2:["trajeras","trajeses"],s3:["trajera","trajese"],p1:["trajéramos","trajésemos"],p2:["trajerais","trajeseis"],p3:["trajeran","trajesen"]})
assert_TenseMood("traer","SubFut",{s1:"trajere",s2:"trajeres",s3:"trajere",p1:"trajéremos",p2:"trajereis",p3:"trajeren"})
assert_TenseMood("traer", "CmdPos", {s1:null,s2: "trae",s3: "traiga",p1: "traigamos",p2: "traed",p3: "traigan",vos: "traé"})
assert_TenseMood("traer", "CmdNeg", {s1:null,s2: "traigas",s3: "traiga",p1: "traigamos",p2: "traigáis",p3: "traigan"})

assert_Participles("vaciar", { pres: "vaciando", past: "vaciado" })
assert_TenseMood("vaciar", "IndPres", {s1: "vacío",s2: "vacías",s3: "vacía",p1: "vaciamos",p2: "vaciáis",p3: "vacían",vos: "vaciás"})
assert_TenseMood("vaciar", "IndImp",  {s1: "vaciaba",s2: "vaciabas",s3: "vaciaba",p1: "vaciábamos",p2: "vaciabais",p3: "vaciaban"})
assert_TenseMood("vaciar", "IndPret", {s1: "vacié",s2: "vaciaste",s3: "vació",p1: "vaciamos",p2: "vaciasteis",p3: "vaciaron"})
assert_TenseMood("vaciar", "IndFut",  {s1: "vaciaré",s2: "vaciarás",s3: "vaciará",p1: "vaciaremos",p2: "vaciaréis",p3: "vaciarán"})
assert_TenseMood("vaciar", "IndCond", {s1: "vaciaría",s2: "vaciarías",s3: "vaciaría",p1: "vaciaríamos",p2: "vaciaríais",p3: "vaciarían"})
assert_TenseMood("vaciar", "SubPres", {s1: "vacíe",s2: "vacíes",s3: "vacíe",p1: "vaciemos",p2: "vaciéis",p3: "vacíen"})
assert_TenseMood("vaciar","SubImp",{s1:["vaciara","vaciase"],s2:["vaciaras","vaciases"],s3:["vaciara","vaciase"],p1:["vaciáramos","vaciásemos"],p2:["vaciarais","vaciaseis"],p3:["vaciaran","vaciasen"]})
assert_TenseMood("vaciar","SubFut",{s1:"vaciare",s2:"vaciares",s3:"vaciare",p1:"vaciáremos",p2:"vaciareis",p3:"vaciaren"})
assert_TenseMood("vaciar", "CmdPos",  {s1:null,s2: "vacía",s3: "vacíe",p1: "vaciemos",p2: "vaciad",p3: "vacíen",vos: "vaciá"})
assert_TenseMood("vaciar", "CmdNeg",  {s1:null,s2: "vacíes",s3: "vacíe",p1: "vaciemos",p2: "vaciéis",p3: "vacíen"})

assert_Participles("venir", { pres: "viniendo", past: "venido" })
assert_TenseMood("venir", "IndPres", {s1: "vengo",s2: "vienes",s3: "viene",p1: "venimos",p2: "venís",p3: "vienen",vos: "venís"})
assert_TenseMood("venir", "IndImp", {s1: "venía",s2: "venías",s3: "venía",p1: "veníamos",p2: "veníais",p3: "venían"})
assert_TenseMood("venir", "IndPret", {s1: "vine",s2: "viniste",s3: "vino",p1: "vinimos",p2: "vinisteis",p3: "vinieron"})
assert_TenseMood("venir", "IndFut",  {s1: "vendré",s2: "vendrás",s3: "vendrá",p1: "vendremos",p2: "vendréis",p3: "vendrán"})
assert_TenseMood("venir", "IndCond", {s1: "vendría",s2: "vendrías",s3: "vendría",p1: "vendríamos",p2: "vendríais",p3: "vendrían"})
assert_TenseMood("venir", "SubPres", {s1: "venga",s2: "vengas",s3: "venga",p1: "vengamos",p2: "vengáis",p3: "vengan"})
assert_TenseMood("venir","SubImp",{s1:["viniera","viniese"],s2:["vinieras","vinieses"],s3:["viniera","viniese"],p1:["viniéramos","viniésemos"],p2:["vinierais","vinieseis"],p3:["vinieran","viniesen"]})
assert_TenseMood("venir","SubFut",{s1:"viniere",s2:"vinieres",s3:"viniere",p1:"viniéremos",p2:"viniereis",p3:"vinieren"})
assert_TenseMood("venir", "CmdPos",  {s1:null,s2: "ven",s3: "venga",p1: "vengamos",p2: "venid",p3: "vengan",vos: "vení"})
assert_TenseMood("venir", "CmdNeg",  {s1:null,s2: "vengas",s3: "venga",p1: "vengamos",p2: "vengáis",p3: "vengan"})

assert_Participles("ver", { pres: "viendo", past: "visto" })
assert_TenseMood("ver", "IndPres", {s1: "veo",s2: "ves",s3: "ve",p1: "vemos",p2: "veis",p3: "ven"})
assert_TenseMood("ver", "IndImp", {s1: "veía",s2: "veías",s3: "veía",p1: "veíamos",p2: "veíais",p3: "veían"})
assert_TenseMood("ver", "IndPret", {s1: "vi",s2: "viste",s3: "vio",p1: "vimos",p2: "visteis",p3: "vieron"})
assert_TenseMood("ver", "IndFut", {s1: "veré",s2: "verás",s3: "verá",p1: "veremos",p2: "veréis",p3: "verán"})
assert_TenseMood("ver", "IndCond", {s1: "vería",s2: "verías",s3: "vería",p1: "veríamos",p2: "veríais",p3: "verían"})
assert_TenseMood("ver", "SubPres", {s1: "vea",s2: "veas",s3: "vea",p1: "veamos",p2: "veáis",p3: "vean"})
assert_TenseMood("ver","SubImp",{s1:["viera","viese"],s2:["vieras","vieses"],s3:["viera","viese"],p1:["viéramos","viésemos"],p2:["vierais","vieseis"],p3:["vieran","viesen"]})
assert_TenseMood("ver","SubFut",{s1:"viere",s2:"vieres",s3:"viere",p1:"viéremos",p2:"viereis",p3:"vieren"})
assert_TenseMood("ver", "CmdPos", {s1:null,s2: "ve",s3: "vea",p1: "veamos",p2: "ved",p3: "vean"})
assert_TenseMood("ver", "CmdNeg", {s1:null,s2: "veas",s3: "vea",p1: "veamos",p2: "veáis",p3: "vean"})



assert_typographicalChange({conjugated_form: "empezé", infinitive: "empezar"}, "empecé")
assert_typographicalChange({conjugated_form: "conoco", infinitive: "conocer"}, "conozco")
assert_typographicalChange({conjugated_form: "sacé", infinitive: "sacar"}, "saqué")
assert_typographicalChange({conjugated_form: "eligo", infinitive: "elegir"}, "elijo")
assert_typographicalChange({conjugated_form: "llegé", infinitive: "llegar"}, "llegué")
